### ISSUE TITLE
scep client error - Could not initialize NSS

### ISSUE THREAD

**Issue by tsvinoth** [xipki/xipki#100]
Hi Lijun Liao,

I am trying scep client from remote vm .. Every time when i run scep client in remote vm , i am seeing this error ..

karaf@root()>                                                                                                                                                                                                      
karaf@root()> xi:scep-cacert --url http://127.0.0.1:8181/ca/scep/ca/tls/pkiclient.exe --out output/certs/cacert.der                                                                                              
Error executing command: Could not initialize NSS
karaf@root()> 

could you please help me to fix this issue ..

Thanks,
Vinoth S

**Comment by xipki** [comment]
Please provide more info:
1. Which JDK (vendor and Version) 
2. XIPKI Version.
3. Log file in xipki data/log/karaf.log. Please set the log Level from Info to debug. 
4. Log file of CA logs/ca-<date>.log. Please set the log Level from Info to debug.

**Comment by xipki** [comment]
Do not forget to star this repository to keep track.

**Comment by tsvinoth** [comment]
Hi Lijun Liao,

**1.Java verison used is 1.8**

openjdk version "1.8.0_201"
OpenJDK Runtime Environment (IcedTea 3.11.0) (Alpine 8.201.08-r0)
OpenJDK 64-Bit Server VM (build 25.201-b08, mixed mode)

**2.XIPKI Version 5.0.0**

3.I have attached the karaf.log which is created after enabling the below parameter in etc/org.ops4j.pax.logging.cfg

**log4j2.logger.xipki.level = DEBUG**

[karaf.log](https://github.com/xipki/xipki/files/2982554/karaf.log)

Thanks,
Vinoth S

**Comment by xipki** [comment]
The cause is that the JRE is configured to use the SunPKCS11 security provider, however the SunPKCS11 provider cannot be started. To fix this, open the file `$JAVA_HOME/jre/lib/security/java.security` and comment the line
`security.provider.<n>=sun.security.pkcs11.SunPKCS11 ...` to 
`#security.provider.<n>=sun.security.pkcs11.SunPKCS11 ...`.

If this line is there by default, then this is a bug of the JDK, please report it to the JDK team.

**Comment by tsvinoth** [comment]
Hi Lijun Liao,

Thanks for the reply :) .. now it is working ..

Regards,
Vinoth S

**Comment by xipki** [comment]
Hi Vinoth,

colud you please try to use the original `java.security` (without the change mentioned above), and install the package `libnss3`? Maybe you are just missing some dependencies of the openjdk.

Best regards,

Lijun

**Comment by tsvinoth** [comment]
Hi Lijun Liao,

sorry for the delay ..

In which file i need to add this code .. FYI i have taken only the binaries from the release page .. I am not using the direct source code ..

https://github.com/xipki/xipki/releases/download/v5.0.0/xipki-cli-5.0.0.tar.gz

Thanks,
Vinoth S

**Comment by xipki** [comment]
Just create new java file and run it. You do not need xipki Code.

**Comment by tsvinoth** [comment]
Hi Lijun Liao,

Thanks for the reply .. currently I didn't have a setup with javac complier .. I am not able to run java code .. This error is seen only on my alphine based container image.. For time being i will go the solution commenting the below line

security.provider.<n>=sun.security.pkcs11.SunPKCS11 ... to
#security.provider.<n>=sun.security.pkcs11.SunPKCS11 ....

I will get back to you once i have proper setup ..

Regards,
Vinoth S
