### ISSUE TITLE
OCSP response cacher exhaust the database connections

### ISSUE THREAD

**Issue by ezzadeen** [xipki/xipki#102]
I'm running a fork of the OCSP responder. I see connection errors after running the OCSP responder for several days. I still get responses. Just the ResponseCache function seems to stop working.

19:56:13.276 [pool-15-thread-1] ERROR o.xipki.datasource.DataSourceWrapper - (getConnection 418) could not create connection to database, java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 10000ms.
19:56:13.277 [pool-15-thread-1] ERROR org.xipki.ocsp.server.ResponseCacher - (run 125) could not remove expired responses, org.xipki.datasource.DataAccessException: UncategorizedSql - HikariPool-1 - Connection is not available, request timed out after 10000ms.
19:57:53.280 [pool-15-thread-1] ERROR o.xipki.datasource.DataSourceWrapper - (getConnection 418) could not create connection to database, java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 10000ms.
19:57:53.280 [pool-15-thread-1] ERROR org.xipki.ocsp.server.ResponseCacher - (updateCacheStore0 448) could not executing updateCacheStore(), org.xipki.datasource.DataAccessException: UncategorizedSql - HikariPool-1 - Connection is not available, request timed out after 10000ms.
**19:57:53.280 [pool-15-thread-1] ERROR org.xipki.ocsp.server.ResponseCacher - OCSP response cacher is out of service**

These are the connection properties:

		autoCommit=true
		readOnly=false
		maximumPoolSize=30
		minimumIdle=10
		connectionTimeout=10000
		idleTimeout=600000
		maxLifetime=1800000
		transactionIsolation=TRANSACTION_READ_COMMITTED

I'll investigate this further, but if you can see the issue  that would be great.

**Comment by xipki** [comment]
This seems to be a database problem. Please check whether all database connection/session resources are exhausted? Does the database instance which manages the OCSP cache also  manage other database.?

**Comment by ezzadeen** [comment]
I think this is the code that is leaking resources:

 private boolean updateCacheStore0() {
...
      Set<String> ids = new HashSet<>();
      try {
        ps = datasource.prepareStatement(SQL_SELECT_ISSUER_ID);
        rs = ps.executeQuery();

        if (master) {
          // If in master mode, the issuers are always up-to-date. Here just to check
          // whether the database is accessible
          return true;
        }
...

      } finally {
        datasource.releaseResources(ps, rs, false);
      }


The finally clause is deliberately setting returnConnection to false (I couldn't understand why!). I have changed the thread period here to execute every 6 seconds instead of every 600 seconds:

this.issuerUpdater = scheduledThreadPoolExecutor.scheduleAtFixedRate(
        new IssuerUpdater(), 448, 6 /*00*/, TimeUnit.SECONDS);

and within a few minutes started seeing the connection pool entries running out and the errors mentioned above.

**Comment by xipki** [comment]
I will work on it tomorrow (GMT+2).

**Comment by ezzadeen** [comment]
I can see why the connection is not returned in other places such as the ResponseCacher::storeOcspResponse. There the connection is passed to datasource.prepareStatement(conn, sql) and used later for another datasource.prepareStatement(conn, sql). But in updateCacheStore0 with the field "master" set to true, the method updateCacheStore0 returns true without returning the connection.

**Comment by xipki** [comment]
Thanks for the analysis. Fixed in 2ee17f7.
