### ISSUE TITLE
unhandled critical extension

### ISSUE THREAD

**Issue by tsvinoth** [xipki/xipki#103]
Hi Lijun Liao,

I am trying to validate the signed certificate with root CA .. But i am getting the below error

[abeesh@mydomain certtest]$ openssl verify -CAfile cazts1.pem serverzts1.pem
C = DE, O = xipki, CN = cert.xipki.org
error 34 at 0 depth lookup: unhandled critical extension
error serverzts1.pem: verification failed
[abeesh@mydomain certtest]$

From this page https://superuser.com/questions/1158939/openssl-unhandled-critical-extension
i am trying to apply the fix by changing the "subjectKeyIdentifier" set to critical & required as false .. With this json file i am trying to configure the root CA but i am seeing below error

```
karaf@root()> source xipki/ca-setup/cacert-none/setup-ec-p12.script ztsca                                                                                                                                          
#################################################################
#                     Generate Key and CSR                      #
#################################################################
saved PKCS#12 keystore to file xipki/ca-setup/keycerts/ztsca.p12
saved CSR to file xipki/ca-setup/keycerts/ztsca.csr
#################################################################
#                       Load ca-conf.json                       #
#################################################################
Error executing command: could not load configuration xipki/ca-setup/cacert-none/ca-conf.json, error: could not add certprofile ocsp
karaf@root()> [root@ci-1812-control-01 ~]# 
```
Could you please help me to fix this ..

thanks,
Vinoth S

**Comment by xipki** [comment]
SubjectKeyIdentifier shall be required and non-critical. Why do you change it to critical?

**Comment by xipki** [comment]
1. SubjectKeyIdentifier should be set to required.
2. Please attach the certificates inputted to the openssl command above.

**Comment by tsvinoth** [comment]
Hi Lijun Liao,

I have attached the root (cacert.pem) and signed certificate (grpc.pem)
[cert.tar.gz](https://github.com/xipki/xipki/files/3107705/cert.tar.gz)

[root@ci-1812-control-01 ~]#  openssl verify -CAfile cacert.pem grpc.pem
grpc.pem: C = IN, O = xipki, CN = grpc.xipki.org
error 34 at 0 depth lookup:unhandled critical extension
OK
[root@ci-1812-control-01 ~]# 

Thanks,
Vinoth S

**Comment by xipki** [comment]
The reason is that openssl cannot process the critical extension 1.3.6.1.5.5.7.1.24 (tlsFeature). Removing this extension definition from the corresponding Certprofile definition should solve the problem.

**Comment by tsvinoth** [comment]
Hi Lijun Liao,

Thanks for the replay ..

I have made the change in profile file certprofile-tls.json ([certprofile-tls.json.txt](https://github.com/xipki/xipki/files/3124685/certprofile-tls.json.txt)).. I have re configured root CA and signed certificate ..But still i am seeing this error ..

```
causer@caserver-5d8b64bb85-z9hb2 certs]$ openssl verify -CAfile cacert.pem grpc.pem      
grpc.pem: C = IN, O = nokia, CN = grpc.nokia.org
error 34 at 0 depth lookup:unhandled critical extension
OK
[causer@caserver-5d8b64bb85-z9hb2 certs]$
```

Thanks,
Vinoth S

**Comment by xipki** [comment]
The attached certprofile still has the definition of the extension tls Feature. You need to remove it as I mentioned in the last comment.

**Comment by tsvinoth** [comment]
Hi Lijun Liao,

Thanks for the comment .. Now it is working ..

```
[causer@caserver-8c546685c-p46zc certs]$ openssl verify -CAfile cacert.pem grpc.pem
grpc.pem: OK
[causer@caserver-8c546685c-p46zc certs]$ 
[causer@caserver-8c546685c-p46zc certs]$
```

Regards,
Vinoth S
