### ISSUE TITLE
secure connection to external mariadb

### ISSUE THREAD

**Issue by tsvinoth** [xipki/xipki#104]
Hi Lijun Liao,

I am having a setup where mariadb is external (separate pod).. I want to make a secure connection (tls enabled) from xipki ca.war .. could you please help me on this ..

dataSource.url = jdbc:mariadb://ca-mariadb:3306/ca?user=XX&password=XXXXX

Thanks,
Vinoth S

**Comment by xipki** [comment]
This site https://www.cyberciti.biz/faq/how-to-setup-mariadb-ssl-and-secure-connections-from-clients/ may helps. I did not try the steps listed there.

**Comment by tsvinoth** [comment]
Hi Lijun Liao,

Thanks for the reply .. i have some default certificate with that i will bring the external mariadb .. But from xipki i want to connect the external mariadb with same default certificate so that my connection is secure ..

Could you please let me know how to pass certificate on the db configuration files (xipki/etc/ca/database/ca-db.properties) ?

Regards,
Vinoth S

**Comment by xipki** [comment]
The ca-db.properties is a HikariCP configuration. Xipki just forwards it to HikariCP. So if you may find solution there.

You may try to specify the SSL parameters in the URL. Details can be found under https://mariadb.com/kb/en/library/about-mariadb-connector-j/#tls-parameters
