### ISSUE TITLE
crl expiry

### ISSUE THREAD

**Issue by tsvinoth** [xipki/xipki#105]
Hi Lijun Liao,

By default the crl file generated is valid for 1 day.

```
/tmp/output/crl $ openssl crl -inform DER -in crl.crl -text -noout
Certificate Revocation List (CRL):
        Version 2 (0x1)
        Signature Algorithm: ecdsa-with-SHA256
        Issuer: C = IN, O = nokia, CN = ztsca
        Last Update: May 21 02:00:35 2019 GMT
        Next Update: May 22 03:00:00 2019 GMT
        CRL extensions:
            X509v3 Authority Key Identifier: 
                keyid:E7:93:E4:F5:0E:9F:5A:EB:2A:49:D0:0C:89:D9:8C:29:78:63:5C:EC

            X509v3 CRL Number: 
                3
No Revoked Certificates.
    Signature Algorithm: ecdsa-with-SHA256
         30:44:02:20:38:0a:91:b0:68:74:0d:03:b3:bb:92:a6:b7:89:
         e4:e8:96:e5:25:bd:af:01:ac:b2:35:96:23:6c:06:8d:8c:c9:
         02:20:3f:1a:37:28:81:6e:54:51:72:5b:9a:e8:b0:2e:12:81:
         66:8a:dd:9a:ca:9d:fa:f0:88:16:c1:81:0c:be:47:38
```
Could you please let me know is there a way to increase the validity. 

Thanks,
Vinoth S

**Comment by xipki** [comment]
1. Which xipki Version do you use?
2. What's the CRL control? The simplest method to retrieve it is to select the CRL_CONTROL column of table CA.

**Comment by tsvinoth** [comment]
Hi Lijun Liao,

I am using xipki version v5.0.0 (https://github.com/xipki/xipki/releases/tag/v5.0.0)

how do i change this column ?? From which configuration file the data got populated to db.. I need to increase the crl expiry or next update time .. Could you please help me on this ..

Thanks,
Vinoth S

**Comment by xipki** [comment]
Could you please post your CRL_CONTROL here? It does not contain any sensitive data.

**Comment by xipki** [comment]
You CA generates 1 CRL per day with the overlap time of 25 minutes. The frequency is controlled by the `fullcrl.intervals` which species the days between two fullCRLs (other than deltaCRL). You can also specify the overlap time via `overlap.minutes`.

The best way to change the CRL control is via the xipki-cli command `ca-up`.

**Comment by tsvinoth** [comment]
Hi Lijun Liao,

please find the below details

MariaDB [ca]> select CRL_CONTROL from CA;
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| CRL_CONTROL                                                                                                                                                                                                                                                                          |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ca.certs.only=false,deltacrl.intervals=0,exclude.reason=false,expiredcerts.included=false,fullcrl.extended.nextupdate=false,fullcrl.intervals=1,interval.time=02:00,invalidity.date=optional,update.mode=INTERVAL,user.certs.only=false,xipki.certset=false,xipki.certset.certs=true |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.000 sec)

MariaDB [ca]>

===============================================================================
CRL control:
  update mode: INTERVAL
  include expired certificates: false
  full CRL intervals: 1
  delta CRL intervals: 0
  overlap: 60 minutes
  use extended nextUpdate: false
  only user certificates: false
  only CA certificates: false
  exclude reason: false
  invalidity date mode: optional
  interval: generate CRL at 02:00
  XiPKI CertSet: not included

==============================================================================
I want to increase the validity of crl to 5 years .. If i make full CRL intervals: 1000 then the next the crl generation & the crl validity is 1000 days ?

Could you please help me on this  ..

Regards,
Vinoth S

**Comment by xipki** [comment]
Yes. 1000 days.

**Comment by tsvinoth** [comment]
Thanks Lijun Liao .. I will check and get back to you in case if i need any help ..

**Comment by tsvinoth** [comment]
Hi Lijun Liao,

I have increased full CRL intervals to 1000 .. with this i have generated new crl .. but i see the validity is not increased ..

```
MariaDB [ca]> select CRL_CONTROL from CA;
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| CRL_CONTROL                                                                                                                                                                                                                                                                             |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ca.certs.only=false,deltacrl.intervals=0,exclude.reason=false,expiredcerts.included=false,fullcrl.extended.nextupdate=false,fullcrl.intervals=1000,interval.time=02:00,invalidity.date=optional,update.mode=INTERVAL,user.certs.only=false,xipki.certset=false,xipki.certset.certs=true |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.000 sec)

MariaDB [ca]>
```



Could you please help me on this ..

Thanks,
Vinoth S

**Comment by tsvinoth** [comment]
Hi Lijun Liao,

After process restart , i can see the crl validity increased by 2 years for full CRL intervals chnaged to 1000 . .Hence closing this ticket ..

Thanks,
vVnoth S
