### ISSUE TITLE
log rotation

### ISSUE THREAD

**Issue by tsvinoth** [xipki/xipki#108]
Hi Lijun,

In tomcat logs folder ,  I can see the log files are appended with date . Whether old log files will be cleared automatically after some days ? 

Could you please confirm this .. If logs are not cleared automatically, then i will build a small logic to remove the old logs .. 

Thanks,
Vinoth S

**Comment by xipki** [comment]
The log mechanism is controlled by logback.xml. In the default configuration, the log files will be deleted later. You may change the configuration. 

BTW, you may need to change you input method for the dot (only one '.' is needed). 

B

**Comment by tsvinoth** [comment]
Hi Lijun,

In /opt/tomcat/webapps/ca/WEB-INF/classes/logback.xml , i have edited the below section

```
<rollingPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy">
      <!-- rollover daily -->
      <fileNamePattern>logs/ca-%d{yyyy-MM-dd}.%i.log</fileNamePattern>
      <!-- each file should be at most 64 MB, keep 60 days worth of history, but at most 20 GB -->
      <maxFileSize>5 MB</maxFileSize>
      <maxHistory>1</maxHistory>
      <totalSizeCap>10MB</totalSizeCap>
    </rollingPolicy>
```

I am exepcting this will delete log files older than a day .. But it is not deleting .. Could you please let me know if i miss anything ..

Thanks,
Vinoth S

**Comment by xipki** [comment]
I am not familiar with logback. Please refer to logback forum for more details.

**Comment by xipki** [comment]
I am not familiar with logback. Please refer to logback forum for more details.

**Comment by tsvinoth** [comment]
Thanks  Lijun .. I will check with logback forum ..
