### ISSUE TITLE
cnname ends with digit

### ISSUE THREAD

**Issue by tsvinoth** [xipki/xipki#109]
Hi Lijun Liao,

I am using the rest code client to get the signed certificate from ca server .. I am noticing whenever i give cnname which ends with a digit . then the output of tls enrolment is failed/not proper ..

**CN=caserverservice1**

```
openssl req -new -sha256 -key output/certs/cert-key.pem -outform der -out output/certs/cert.csr -subj "/CN=caserverservice1/O=nokia/C=IN" -addext

curl --insecure --user zts1ztssecret:123456 --header "Content-Type: application/pkcs10" --data-binary "@output/certs/cert.csr" --output output/certs/cert.der http://127.0.0.1:8181/ca/rest/ca/enroll-cert?profile=tls
```

when i try to convert the output der to pem format i am getting the below error

```
openssl x509 -inform der -in output/certs/cert.der -out output/certs/cert.pem
unable to load certificate
140507592137576:error:0D07207B:asn1 encoding routines:ASN1_get_object:header too long:crypto/asn1/asn1_lib.c:101:
```

When i see the log /opt/tomcat/logs/localhost_access_log.2019-06-06.txt ..

`127.0.0.1 - - [06/Jun/2019:12:03:39 +0000] "POST /ca/rest/ca/enroll-cert?profile=tls HTTP/1.1" 400 -`

Could you please help me on this ?  FYI i am using release v5.0.0

Thanks in Advance,
Vinoth S

**Comment by xipki** [comment]
The Common Name needs to be a FQDN.

**Comment by xipki** [comment]
Please update to the latest version 5.3.1.

**Comment by tsvinoth** [comment]
Thanks Lijun Liao.. I can't upgrade the version right now .. I understand CN Name should be FQDN .. I will avoid passing digits at the end of CN Name ..
