### ISSUE TITLE
Possible to enable logging to show XiPKI requests and responses?

### ISSUE THREAD

**Issue by ohaya** [xipki/xipki#114]
Hi,

I was wondering if it is possible to configure logging to show the XiPKI requests and responses?  I looked at the Tomcat conf/logging and that looks like it already set to FINE, but when I test XiPKI I don't seem to see much/any logging for XiPKI?

Thanks,
Jim

**Comment by xipki** [comment]
Currently the logging of raw request / responses is not supported due to the performance. I will come back to this issue this weekend.

**Comment by ohaya** [comment]
Hi,

Ok, thanks.

Ideally, this logging would be configurable (e.g., control it via log levels or something) as you would want to minimize impact to performance in production or even load test situations.

The reason (for my purpose) that it IS important to BE ABLE TO enable that logging is that I am working on load testing, and for example, my load testing sends out bunches of requests for a whole bunch of different serial numbers, but I do want to be able to verify that my load test is actually varying the serial numbers, and I want to be able to do that verification at both the client side and the server side during the load test development, to make sure that my testing is behaving correct. 

Right now, I can only check my client side testing is behaving correctly.

Thanks,
Jim

**Comment by xipki** [comment]
Features added in https://github.com/xipki/xipki/commit/fb77ccc202614babea9e4098ce552294837ac1d6

You need to change the logReqResp in web. xml from false to true, and also the log level to DEBUG.

**Comment by ohaya** [comment]
Hi,

THANKS!!  I will give it a try!

Jim

**Comment by xipki** [comment]
You can build it from source.
