### ISSUE TITLE
Documentation - Comparison with EJBCA

### ISSUE THREAD

**Issue by cdanger** [xipki/xipki#115]
It is difficult for users to choose between all the various open source PKIs out there. Could you explain - maybe in a FAQ - how does it compare to EJBCA Community edition in particular, which is also open source, implemented in Java, etc.  ? That would help. Thanks.

**Comment by xipki** [comment]
I am not familiar with EJBCA, so I cannot do such comparison.

You can find most features of xipki in the repo's README.

**Comment by cdanger** [comment]
Fair enough.
