### ISSUE TITLE
Question about importing CRLs into OCSP Responder

### ISSUE THREAD

**Issue by ohaya** [xipki/xipki#116]
Hi,

I am sorry, but this is more of quick question about XiPKI rather than an "issue", and I don't know if there is anywhere else to pose this. 

Anyway, so I know that to trigger XiPKI to import a CRL, I drop the CRL and CA cert file into a directory and then create a file in the same directory named "UPDATEME".  And then XiPKI changes the filename from "UPDATEME" to "UPDATEME.SUCC" or "UPDATEME.FAILED", at some later time.

The question I have is:  When the UPDATEME filename changes to UPDATEME.SUCC, does that mean that XiPKI has completely imported that CRL file and has already COMPLETELY updated the revocations internally, e.g., if I send an OCSP request after the UPDATEME filename has changed, will XiPKI be using the new CRL?

Or, does the UPDATEME filename change simply indicate that XiPKI has JUST STARTED processing the new CRL?

Thanks,
Jim

**Comment by xipki** [comment]
The file UPDATEME will be renamed at the end of importing process.

**Comment by ohaya** [comment]
Ok, thanks!
