### ISSUE TITLE
OCSP Responder question/problem? CRL Still working beyond validity period?

### ISSUE THREAD

**Issue by ohaya** [xipki/xipki#117]
Hi,

I have a CRL that I imported into XiPKI OCSP Responder awhile ago, and today, I started doing some additional testing.  I was kind of surprised that when I tested with an OCSP request, the XiPKI OCSP Responder was still responding with a "positive" response:

openssl ocsp -VAfile ocsp-signer.pem -url http://localhost:8080 -issuer XXXXXX.pem -serial 0x180002
Response verify OK
0x180002: revoked
        This Update: Jul  2 08:00:00 2019 GMT
        Next Update: Jul 30 15:29:03 2019 GMT
        Reason: keyCompromise
        Revocation Time: Sep 24 14:05:44 2018 GMT

So then, I checked the ca.crl using "openssl crl" and this is what it showed for that CRL:

Certificate Revocation List (CRL):
        Version 2 (0x1)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: xxxxxxx
        Last Update: Jul  2 08:00:00 2019 GMT
        Next Update: Jul  9 17:00:00 2019 GMT
        CRL extensions:
            X509v3 Authority Key Identifier:
                keyid:39:29:A8:08:64:E2:8F:83:AA:81:61:47:11:91:33:F8:5A:37:A6:E4

            X509v3 CRL Number:
                3180
.
.
.
    Serial Number: 180002
        Revocation Date: Sep 24 14:05:44 2018 GMT
        CRL entry extensions:
            X509v3 CRL Reason Code:
                Key Compromise
            Invalidity Date:
                Sep 24 13:59:43 2018 GMT
.
.
.

As can be seen from the "openssl crl" output:

        Last Update: Jul  2 08:00:00 2019 GMT
        Next Update: Jul  9 17:00:00 2019 GMT

i.e., that CRL's validity period was ONLY from July 2, 2019 until July 9, 2019, and yet the XiPKI OCSP Responder still "processed" the OCSP request and returned a response, acting AS IF THE CRL WAS STILL VALID!!

My understanding is that if a CRL is expired (the date/time of the OCSP request is outside of the CRL's validity period, i.e., after the CRL's "Next Update" date/time), then the OCSP responder should always respond with a "negative" response, i.e., it should treat that CRL as no longer valid.

Actually, I am not sure what "the standard" is, or even if there is "a standard", for this situation, but I think that the current behavior I was seeing is not correct.  In general, the OCSP Responder should not be using (or responding with) any information that is from the currently-expired/-invalid CRL?

Also, I am not sure where the XiPKI OCSP Responder EVEN GOT the "Last Update" and "Next Update" that it sent in the OCSP response message?  If I had to guess I am guessing that it got the "Last Update" from the CRL, and the "Next Update" for the current/today's date, which is definitely not accurate.

Please advise.

Thanks,
Jim

**Comment by xipki** [comment]
Once a certificate is revoked (not suspended), it cannot be unrevoked. So in this case the behavour of XiPKI OCSP responder to answer "revoked" is correct even if the CRL is expired. What may be problematic is that the certificates revoked after the expiration of the imported CRL. The responder may 1) answer with "tryLater" error or 2) still use the expired CRL. In case 1, services relying on the OCSP responder may be in trouble, which, in general, has much more impact than case 2.

I will add a configuration flag to make it configurable and case 1 as default.

**Comment by ohaya** [comment]
Hi,

Thanks for that!  We (our program) have had this same discussion before and I was re-reading the RFCs, and it's kind of unfortunate that those are "silent" about this scenario, but from our perspective, the way we look at it is that the dates on the CRL define the period of time for which that CRL "is valid", and, once you are out of that period (either before or after the period), that CRL is no longer to be trusted.  As I said, it's really unfortunate (== bad) that the RFCs are silent on this, but our "rule" is that we basically shutdown that access in this situation, since "invalid CRL" == "no CRL" == "no access".   What you are suggesting for the OPTION to answer with a tryLater ERROR is acceptable, I think.

Thanks,
Jim

**Comment by xipki** [comment]
Features add in commit a20ecafa779f62d7bfa9959c33a7510e625fabc9.
