### ISSUE TITLE
 Can this use HSM to  store private key of CA

### ISSUE THREAD

**Issue by meishijia** [xipki/xipki#119]
When I read the java class file XiKeyStoreSpi.java， it  seems that can only read private keys from PKCS#11 device, and the comment also says "keystore is read only".
I wonder whether xipki can store private key to PKCS#11 device. Thank you!

**Comment by xipki** [comment]
Xipki provides code / Tool to generate keypairs / key in HSM. See https://github.com/xipki/xipki/blob/master/shells/security-shell/src/main/java/org/xipki/security/shell/P11Actions.java

**Comment by xipki** [comment]
Any new comment? If not, I will close this issue in 48 hours.

**Comment by meishijia** [comment]
Thank you for your reply! Let me close this issue.
