### ISSUE TITLE
Any hints/suggestions for optimizing (speed) performance of XiPKI OCSP Responder?

### ISSUE THREAD

**Issue by ohaya** [xipki/xipki#120]
Hi,

I am running some load tests on XiPKI.  For this testing, we have a XiPKI instance deployed on an m4.large RHEL 6.10 instance on AWS, and:

- Tomcat is 9.0.20
- Database is Mysql 5.1.73
- We are hitting the XiPKI directly, i.e., we are not reverse-proxying anything in front of the Tomcat/XiPKI.

I was wondering if you have any recommendations or suggestions for optimizing the performance (mainly speed) with this configuration?

Thanks,
Jim

**Comment by xipki** [comment]
For tomcat and mysql, you may get help in the corresponding forum of tomcat and mysql, respectively.

For the OCSP response in XiPKI:
- Use efficient cryptographic algorithm if possible, e.g. ECDSA instead of RSA.
- Cache the OCSP responses (configurable in ocsp-responder.json).
- Do not log in DEBUG level.

**Comment by ohaya** [comment]
Hi,

I had mentioning that I am now doing load/performance testing the last several days.  We are running these tests with several products, including XiPKI.  

XiPKI was doing pretty well, but I had to update/import new CRLs today to all of the products, including XiPKI, and when I ran my perf tests after those new imports, something happened to the relative performances so now the numbers I am getting for XiPKI are not the best.

I know that one of the other products does caching already, so I want to try to enable the caching in XiPKI and also change the debug logging if I can.

- For the caching, you said that it is configurable in ocsp-responder.json?  But I thought there was something in the MySQL schema that had to also be done?

- For the logging, which config file should I check for that?

Thanks,
Jim

**Comment by ohaya** [comment]
Hi,
I think I figured how to enable caching (create the database, run the initdb.sh and uncomment the lines in ocsp-responder.json) and am running tests now and it seems much better response!

Can you explain how to implement what you mentioned, "Use efficient cryptographic algorithm if possible, e.g. ECDSA instead of RSA"?

I want to test that.

Thanks,
Jim

**Comment by xipki** [comment]
Related to "ECDSA/RSA":

Assumed that the following block is configured in your `ocsp-responder.json`:
```
	"signers":[{
		"name":"signer1",
		"type":"pkcs12",
		"algorithms":["SHA256withRSA"],
		"caCerts":[],
		"key":"password=1234,keystore=file:xipki/keycerts/ocsp1.p12"
	}],
```

You need to have an EC private key with corresponding certificate and save both in the file  `xipki/keycerts/ocsp1.p12` under the same alias, and change the `SHA256withRSA` to `SHA256withECDSA`.

**Comment by xipki** [comment]
Related memory usage, are you sure that the tomcat process causes the large memory usage?

I noticed that you have duplicated xipki wars (ROOT.war and ocsp.war). Please remove the ocsp.war.

To make sure that the large memory usage is caused by XiPKI, please remove all beides ROOT.war in the folder webapps.

**Comment by ohaya** [comment]
FYI, the XiPKI instance I am working with now is in our dev lab, so one of our deployers deployed that XiPKI.

This is what is NOW in /apps/apache-tomcat..../webapps:

[root@ip-192-168-255-5 makeCsvEjbca]# ls -al /apps/apache-tomcat-9.0.20/webapps/
total 11368
drwxr-x---  8 root root    4096 Jul 17 12:11 .
drwxr-xr-x 10 root root    4096 Jul 16 15:56 ..
drwxr-x--- 14 root root    4096 Jul 16 14:12 docs
drwxr-x---  6 root root    4096 Jul 16 14:12 examples
drwxr-x---  5 root root    4096 Jul 16 14:12 host-manager
drwxr-x---  5 root root    4096 Jul 16 14:12 manager
drwxr-x---  4 root root    4096 Jul 17 12:11 ocsp
-rw-r--r--  1 root root 5801869 Jul 16 14:31 ocsp.war
drwxr-x---  4 root root    4096 Jul 17 12:11 ROOT
-rw-r--r--  1 root root 5801869 Jul 16 14:35 ROOT.war
[root@ip-192-168-255-5 makeCsvEjbca]#

So I am confused about what you were suggesting?

Are you saying the the only thing that should be left in the /apps/apache-tomcat.../webapps directory should be the "ocsp" directory?

Thanks,
Jim



P.S.  About memory - no I am not sure if it was from XiPKI, but FYI, now, after several reboots, the memory usage seems to be back to what it was before, about <2GB.

**Comment by xipki** [comment]
```
webapps
   |
   +-- ROOT.war
   |
   +-- ocsp.war
   |
  ... 
```

Should be as follows
```
webapps
   |
   +-- ROOT.war
   |
   ... 
```

**Comment by ohaya** [comment]
Hi,
Sorry I am being careful.  The last thing I want to do is break our dev system at this point.
So just to be clear:  You are suggesting to remove ALL the files and dirs under webapps, except for ROOT.war.
Is that right?
I just double-checked, and did a diff of the ROOT.war and ocsp.war and both those files are identical.
So, now, if I do what you say, then Tomcat will deploy the ROOT.war and will thus create the webapps/ROOT directory and so then the webapps directory will have the FILE ROOT.war and the directory webapps/ROOT.  

Is that correct?
Like I said, I am just trying to be careful.
Jim

    On Saturday, August 10, 2019, 5:40:17 AM UTC, Lijun Liao <notifications@github.com> wrote:  
 
 webapps
   |
   +-- ROOT.war
   |
   +-- ocsp.war
   |
  ... 

Should be as follows
webapps
   |
   +-- ROOT.war
   |
   ...

**Comment by xipki** [comment]
Yes.

**Comment by ohaya** [comment]
Hi I think that you can close this issue.
Thanks!
