### ISSUE TITLE
May I ask something about how to use SoftHSM / HSM in your project?

### ISSUE THREAD

**Issue by VolcanoWCAN** [xipki/xipki#121]
Hi，
    Recently, I have been doing some work on a PKI system. And I want to use SoftHSM to protect the privacy of the private key in the PKI system.  But I have some trouble. When I want to store a key in the SoftHSM, we should provide a alia which is corresponding to the key. My question is  how to name the key and make the key differ from other keys which stored in the same softHSM. The alia must be unique and can't be duplicated.  And I know that if I use the same alia to store the key,  it makes the new content recover the old one .Should I offer a set of rules on choosing the alia?
   I have read you code,  the code is a s follows:

**Comment by VolcanoWCAN** [comment]
Hi，
Recently, I have been doing some work on a PKI system. And I want to use SoftHSM to protect the privacy of the private key in the PKI system. But I have some trouble. When I want to store a key in the SoftHSM, we should provide a alia which is corresponding to the key. My question is how to name the key and make the key differ from other keys which stored in the same softHSM. The alia must be unique and can't be duplicated. And I know that if I use the same alia to store the key, it makes the new content recover the old one .Should I offer a set of rules on choosing the alia?
I have read you code, the code is a s follows:
[image](https://user-images.githubusercontent.com/33406143/62452220-5333cf00-b7a2-11e9-8f86-5d967d4f4739.png)
Is this your rule on naming the alia?

**Comment by xipki** [comment]
The code you found above in xipki is not the key alias in PKCS#11 device. It specifies how to identify  an existing key in the device.

In general, there is no restriction on the label (namely alia in your comment) of key, you can even use the same label for different PKCS#11 objects. In XiPKI, I use the same label for the tuple (private key, public key, certificate). But you do not need to follow this rule.

**Comment by VolcanoWCAN** [comment]
Thank you very much ：）
