### ISSUE TITLE
Need info for approvals

### ISSUE THREAD

**Issue by ohaya** [xipki/xipki#122]
Hi,
Our process here requires that we get formal approvals for any software, down to specific version information, that we use, and so I want to ask if there is a specific version number for most current version (at this time).  

Is that 5.3.3, and does that include the changes that you have made recently such as the logging requests and the DELETEME file?

Also, if we download the ZIP file, can we build XiPKI without using Maven?

Thanks for ALL of your help!

Jim

**Comment by xipki** [comment]
All versions of XiPKI is managed in github.com, so you can checkout the version you need and build it.

**Comment by xipki** [comment]
BTW: Due to bug mentioned in #124, the OCSP server in version 5.3.3 does not work. Please use version 5.3.4.
