### ISSUE TITLE
xipki upgrade is failing

### ISSUE THREAD

**Issue by tsvinoth** [xipki/xipki#123]
Hi Lijun Liao,

I am using xipki version 5.0.0 with external mariadb .. I want to upgrade xipki to 5.3.2 without affecting the data in mariadb .. my helm upgrade shows successful but i am seeing some errors in log file (https://github.com/xipki/xipki/files/3500184/ca.log) and unable to fetch certificates 

```
2019-08-14 06:52:26,311 ERROR o.x.u.LogUtil [localhost-startStop-1] (createPublisher 2340) invalid configuration for the publisher (id=1, name=ocsp-publisher), org.xipki.ca.api.publisher.CertPublisherException: no datasource named 'ocsp' is specified
2019-08-14 06:52:26,312 ERROR o.x.u.LogUtil [localhost-startStop-1] (startCaSystem0 610), org.xipki.ca.api.mgmt.CaMgmtException: invalid configuration for the publisher (id=1, name=ocsp-publisher)
```
Could you please help me on this ..

Thanks,
Vinoth S

**Comment by xipki** [comment]
There are several changes related to the database and configuration since version 5.0.0. Before I start to find out a solution, could you please provide some details:
1. Which software uses the OCSP database?
2. How many entries are in the table CERT?
3. Where are the private CA keys saved?

**Comment by xipki** [comment]
You need to adapt the database schema of CA database:
```sql
ALTER TABLE CA ADD CTLOG_CONTROL VARCHAR(1000);
ALTER TABLE CA ADD REVOKE_SUSPENDED_CONTROL VARCHAR(500);
ALTER TABLE CA ADD DHPOC_CONTROL TEXT;
ALTER TABLE CA ADD CERTCHAIN TEXT;
ALTER TABLE CRL ADD CRL_SCOPE SMALLINT NOT NULL;
ALTER TABLE CERT ADD CRL_SCOPE SMALLINT NOT NULL;
```

**Comment by xipki** [comment]
And if you do not need the OCSP database, execute following SQL queries:
```sql
DELETE FROM CA_HAS_PUBLISHER
DELETE FROM PUBLISHER
```

**Comment by tsvinoth** [comment]
> There are several changes related to the database and configuration since version 5.0.0. Before I start to find out a solution, could you please provide some details:
> 
> 1. Which software uses the OCSP database?
> 2. Where are the private CA keys saved?

None of my software directly uses the OCSP database and the Private key is stored in CA table in ca database ..

**Comment by tsvinoth** [comment]
After i do upgrade i just ran the below queries in ca database

```
ALTER TABLE CA ADD CTLOG_CONTROL VARCHAR(1000);
ALTER TABLE CA ADD REVOKE_SUSPENDED_CONTROL VARCHAR(500);
ALTER TABLE CA ADD DHPOC_CONTROL LONGTEXT;
ALTER TABLE CA ADD CERTCHAIN LONGTEXT;
ALTER TABLE CRL ADD CRL_SCOPE SMALLINT NOT NULL;
ALTER TABLE CERT ADD CRL_SCOPE SMALLINT NOT NULL;
DELETE FROM CA_HAS_PUBLISHER;
DELETE FROM PUBLISHER;
delete from SYSTEM_EVENT;
```
But i still see the below error in ca.log file

`2019-08-16 06:28:31,113 ERROR o.x.u.LogUtil [localhost-startStop-1] (startCaSystem0 610), java.lang.IllegalArgumentException: serialNoBitLen may not be out of the range [71, 159]: 63`

[ca.log](https://github.com/xipki/xipki/files/3508353/ca.log)

**Comment by xipki** [comment]
Please change the SN_SIZE in table CA to a value between 71 and 159.

**Comment by tsvinoth** [comment]
Thanks Lijun Liao .. Now it is working fine I can able to get the certificates .. I need do these work around on database before performing upgrade ..
