### ISSUE TITLE
Adding an intermediate certificate

### ISSUE THREAD

**Issue by ashley-abdelsayed98** [xipki/xipki#125]
Hello!
It doesn't seem like there is support to add an intermediate certificate in the ocsp servers database. The structure only seems to support adding issuers (that do not have issuers themselves) or certificates that only reference the issuer ids in the issuer database, not another certificate id https://github.com/xipki/xipki/blob/v3.0.0/ca-server/src/main/resources/sql/ocsp-init.xml. I just wanted to make sure there is in fact no support for intermediate certificates and if not, if that would be added soon. 

Thank you!
Ashley

**Comment by xipki** [comment]
I am not sure what you exactly mean. Do you mean the intermediate CA's certificate of the OCSP responder?

The OCSP database contains the status information and meta data of all certificates. Their issuer (aka CA that issues these certificates) are containen in the table ISSUER.
