### ISSUE TITLE
ipv6 support

### ISSUE THREAD

**Issue by tsvinoth** [xipki/xipki#126]
Hi Lijun Liao,

Can you please confirm whether xipki suports ipv6 ? If yes what are the changes need to be done for that .. FYI i am using xipki version 5.0.0 .. I want to support both ipv4 and ipv6 as well ..

Thanks,
Vinoth S

**Comment by xipki** [comment]
Any feedback?

**Comment by tsvinoth** [comment]
Hi Lijun Liao,

Sorry for the delay in response ..

we are planning to retain xipki application to listen in ipv4 and let the network layer handle ipv6 traffic and redirect to application as ipv4 .. 

Due to time constraint , i am not able use xipki with ipv6 ..

Thanks,
Vinoth S
