### ISSUE TITLE
Readiness and Liveness probe

### ISSUE THREAD

**Issue by tsvinoth** [xipki/xipki#129]
Hi Lijun Liao,

I am using xipki version 5.0.0 with external mariadb .. Sometimes xipki is trying to access database and database is temporarily down or yet to come up .. To handle such situations is there any readiness and liveness check in xipki saying xipki process is up and running successfully and the connection between xipki and database is established properly ?  Is there any retry logic is there in xipki if first time xipki is not come up successfully ..

Thanks,
Vinoth S

**Comment by xipki** [comment]
Xipki accesses the database via HikariCP. If HikariCP provides such mechanism, then it should also work in Xipki.

**Comment by tsvinoth** [comment]
Hi Lijun Liao,

If xipki process is running without any issue .. Is there any liveliness url to make sure everything is working ? I want to add kubernetes health check so that if some thing is wrong then i will recover by restarting xipki process ..

Regards,
Vinoth S

**Comment by xipki** [comment]
Try the HTTP url: https://{host}:{port}/ca/health/{caname}. E.g. https://192.168.1.1:8443/ca/health/myca.

**Comment by tsvinoth** [comment]
Hi Lijun Liao,

Thanks for sharing the health check link .. I will get back to you if i need any thing ..

Regards,
Vinoth S
