### ISSUE TITLE
RandomDnCompleter.java

### ISSUE THREAD

**Issue by TakeMeNL** [xipki/xipki#13]
In /xipki/ca/ca-client-shell/src/main/java/org/xipki/pki/ca/client/shell/completer/
RandomDnCompleter.java exists with 2 files :
RandomDnCompleter.java and RandomDNCompleter.java.
Maven doens't compile and gives a error. Removing RandomDNCompleter.java fixes the issue

**Comment by xipki** [comment]
After checking the the branch master, I cannot find the file RandomDNCompleter.java. In which branch have you built the code?

**Comment by TakeMeNL** [comment]
https://github.com/xipki/xipki/tree/master/ca/ca-client-shell/src/main/java/org/xipki/pki/ca/client/shell/completer
