### ISSUE TITLE
Questions about XiPKI requirements (container and JDK)?

### ISSUE THREAD

**Issue by ohaya** [xipki/xipki#131]
Hi,

Sorry that it's been awhile, but we have a couple of questions about XiPKI requirements:

- Can XiPKI run under WebLogic 10.3.x?
- Is XiPKI compatible with JRE/JDK 1.7.x?

Thanks,
Jim

**Comment by xipki** [comment]
1. Jdk 7 is not supported. You need to use JDK 8(build 162+) or above.
2. It should work in weblogic. Please refer to Google for deploying war in web logic. I will test it later (however not in the next werks).

**Comment by ohaya** [comment]
Hi,

Ok, thanks for the information!  I will close this issue and we will try it with WebLogic and post back.

Thanks,
Jim
