### ISSUE TITLE
Enable Encryption in Database

### ISSUE THREAD

**Issue by tsvinoth** [xipki/xipki#133]
Hi Lijun Liao,

I am using xipki version 5.0.0 with external mariadb .. In database, i can see certificates in tables which is written as plain text not encrypted .. My use case is to encrypt the data and write to database so that even some one get into the database can get only encrypted data ..

Could you please help me on this ? Is there any way i can force xipki to encrypt data before it writes to database and decrypt while serving certificate ..

thanks,
Vinoth S

**Comment by xipki** [comment]
You can use the encryption funktion of database.

**Comment by kishankalyan** [comment]
Hi Lijun Liao,

Thanks for the input provided. But is it possible to do the encryption from xipki. Basically we want encryption and decryption to take place at xipki side.

Thanks
-Kishan

**Comment by xipki** [comment]
Xipki does not provide mechanism to encrypt non-sensitive data like the certificates. And in general encryption at the application side is very complicated.

Would you like to share the reason why the database encryption is not suitable for you?  You may drop me an email if you do not want to publish it here.
