### ISSUE TITLE
Strange problem:  java.security.cert.CertPathValidatorException: Response is unreliable: its validity interval is out-of-date

### ISSUE THREAD

**Issue by ohaya100** [xipki/xipki#139]
Hi,

I was doing some testing to use for our documentation and I am getting the above error when I test with our OAM and XiPKI OCSPD.

In the OAM logs, I am seeing this:

`certpath: Status of certificate (with serial number 3) is: GOOD
certpath: OCSP response is signed by a Trusted Responder
certpath: Constraints.permits(): SHA256withRSA Variant: generic
certpath: Verified signature of OCSP Response
certpath: OCSP response validity interval is from Thu Jan 09 04:00:01 UTC 2020 until Wed Jan 15 21:44:43 UTC 2020
certpath: Checking validity of OCSP response on: Thu Jan 16 01:16:46 UTC 2020
certpath: RevocationChecker.check() Response is unreliable: its validity interval is out-of-date
certpath: RevocationChecker.check() preparing to failover
`

Notice that that information above seems to be correct, i.e., the validity was being checked by the OAM server on 1/16/2020, and the validity period of the OCSP response was from Jan 09 04:00:01 UTC 2020 until Wed Jan 15 21:44:43 UTC 2020... so the OAM server was checking the validity of the OCSP response a day late.

BUT, it just doesn't make sense because I checked, and the system dates on the OAM server and on the XiPKI OCSPD machine are exactly the same!!

Also, since the system dates are on 1/16/2020, why IS the validity period of the OCSP response starting on 1/9/2020??  

It's like the OCSP Responder is going backwards in time (even though the system date is not)??

Could it be that the XiPKI is pulling out something from it's cache and sending an old response, with an old ocsp response validity period??

Thanks,
Jim

P.S.  I have even/already tried updating the CRL on the XiPKI just a few minutes ago.   I also bounced the Tomcat, but nothing seems to be bringing the XiPKI responses forward to the correct date/time.

**Comment by xipki** [comment]
Just checked the code, this is a bug in XiPKI. I will fix it in the next version.

To work around this bug, please remove the responseCache or uncomment (as in [ocsp-responder.json](https://github.com/xipki/xipki/blob/master/assemblies/ocsp-war/src/assembly/unfiltered/xipki/etc/ocsp/example/crl-store/ocsp-responder.json)) or remove the responseCache int the file ocsp-responder.json.

**Comment by xipki** [comment]
Related to #140.

**Comment by ohaya100** [comment]
Hi,

Yes, you are correct, we had the caching configured and I have commented out the responseCache lines in the ocsp-responder.json now and tested, and it seems to be working again now.

Thanks!

Jim

**Comment by xipki** [comment]
Released the new version v5.3.6. To use the cache feature, you must delete all entries in the cache database first, since the saved nextUpdate is in milliseconds.
