### ISSUE TITLE
OCSP response cacher saves time in (incorrect) milliseconds instead of (correct) seconds.

### ISSUE THREAD

**Issue by xipki** [xipki/xipki#140]
As result, outdated responses will be sent back to the OCSP requestor.

**Comment by ohaya100** [comment]
Hi,

Do you know when this change/fix will be in a release?  We are on V5.3.3 I think, but in our process, we need to get approvals for new releases, so we are asking.

Thanks,
Jim

**Comment by xipki** [comment]
Released. See the comment in #139.
