### ISSUE TITLE
Unknown database 'ca'

### ISSUE THREAD

**Issue by tlm38025** [xipki/xipki#141]
initdb.bat --db-conf  D:\study\pki\ca-war-5.3.6-SNAPSHOT\xipki\etc\ca\database\ca-db.properties --db-schema D:\study\pki\ca-war-5.3.6-SNAPSHOT\xipki\sql\ca-init.xml

--------------------------------------------
     driver: org.mariadb.jdbc.Driver
       user: root
        URL: jdbc:mariadb://127.0.0.1:3306/ca
schema file: D:\study\pki\ca-war-5.3.6-SNAPSHOT\xipki\sql\ca-init.xml

Do you wish to reset and initialize the database [yes/no] ?
yes
Error while initializing database: liquibase.exception.DatabaseException: java.sql.SQLSyntaxErrorException: Could not connect to address=(host=127.0.0.1)(port=3306)(type=master) : Unknown database 'ca'

**Comment by xipki** [comment]
You need to create the database 'ca', as specified in the section 'Install CA Server' of project's README.

**Comment by tlm38025** [comment]
End of session "**Install CA Server**" there is a command:
'ca-war-<version>/dbtool/bin/initdb.sh \
   --db-conf xipki/etc/ca/database/ca-db.properties \
   --db-schema xipki/sql/ca-init.xml'
It didn't contain the create ca db procedure? 

Hence,  I need follow the second step
"**2.Adapt the database configurations ${CONTAINER_ROOT}/xipki/etc/ca/database/ca-db.properties.**"
to create the 'ca' db separately and then run the command ?

Could you help give some suggestions?
 Thank you very much!

**Comment by tlm38025** [comment]
Thanks xipki, I have resolved it.

1. First use cmd to operate the mysql to create 'ca' db

`C:\Users\leehm>mysql -h localhost -u root -p
Enter password: ******
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 3
Server version: 5.5.62 MySQL Community Server (GPL)

Copyright (c) 2000, 2018, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> CREATE DATABASE ca;
Query OK, 1 row affected (0.01 sec)`

2. Then  run the command: end of session "Install CA Server" 

`D:\study\pki\ca-war-5.3.6-SNAPSHOT\dbtool\bin>initdb.bat --db-conf  D:\study\pki\ca-war-5.3.6-SNAPSHOT\xipki\etc\ca\database\ca-db.properties --db-schema D:\study\pki\ca-war-5.3.6-SNAPSHOT\xipki\sql\ca-init.xml

--------------------------------------------
     driver: org.mariadb.jdbc.Driver
       user: root
        URL: jdbc:mariadb://127.0.0.1:3306/ca
schema file: D:\study\pki\ca-war-5.3.6-SNAPSHOT\xipki\sql\ca-init.xml


Do you wish to reset and initialize the database [yes/no] ?
yes
successfully released the database
successfully  dropped the database
successfully  updated the database

D:\study\pki\ca-war-5.3.6-SNAPSHOT\dbtool\bin>`
