### ISSUE TITLE
jar file created from running maven build on lite-caclient-example throws "Please call "mvn generate-resources" first." message.

### ISSUE THREAD

**Issue by vishal549** [xipki/xipki#142]
jar file created from running maven build on lite-caclient-example throws "Please call "mvn generate-resources" first." message when jar is executed.

I am trying to create jar only from lite-caclient-example project as other codes are not required.
I have added dependencies and main function in pom.xml file.

**Comment by xipki** [comment]
Please describe the detailed step and error message. You may also add my wechat (specified in the project's README) for live chat.

**Comment by vishal549** [comment]
1. Created jar file using maven build command for lite-caclinet-example project.
   cmd: 
       mvn clean
       mvn clean install.
2. Copied all the dependent jar files along with the jar file created after maven build in a directory called "lib"
3. Ran command "java -cp "lib/*" org.xipki.litecaclient.example.PbmMacCmpCaClientExample" where PbmMacCmpCaClientExample is having main function.
4. After running the java -cp command "Please call "mvn generate-resources" first." message is displayed.

**Comment by xipki** [comment]
Just as the name says, it is just example. This class needs some keys and certificates under the folder ./target/tlskeys, which can be generated via the command 'mvn generate-resources'. For details please refer to the code.

**Comment by vishal549** [comment]
./target/tlskeys is getting generated after maven build but still after running the jar file it says "Please call "mvn generate-resources" first.".

**Comment by xipki** [comment]
Please read the code first and copy the folder tlskeys to the expected location.

**Comment by vishal549** [comment]
Checked the code. Thanks for the help
