### ISSUE TITLE
Does XiPKI OCSPD support CA with multiple CRLs?

### ISSUE THREAD

**Issue by ohaya100** [xipki/xipki#145]
Hi,

I am working on an app to migrate CRLs that we download for a previous OCSPD to XiPKI, and I am running some strange scenarios (to me). 

In particular, we have one CA where we have 3 CRLs that are identical except the CRLs have different Authority Key Identifier.

Can XiPKI handle such as situation, and if so how?  Do we just put all 3 CRLs into the same subdirectory, but if so, how do we name the 3 CRLs?

Thanks,
Jim

**Comment by xipki** [comment]
XiPKI does not support multiple CRLs for one CA.

>3 CRLs that are identical except the CRLs have different Authority Key Identifier
1. Do you mean the lists of revoked certificates in all CRLs are of the same?
2. Why does one CA has three different AKIs (Authority Key Identifier)?

**Comment by ohaya100** [comment]
Re. 1) I didn't check the entire CRL file contents, but from what I did look at, the 3 CRLs were identical except for the AKIDs.

Re. 2) I am trying to find out why, but right now I don't know why.


Now, so if there is only a single CA cert with a single Subject, and the 3 CRLs that have the same Issuer that is equal to the Subject in the single CA cert, how can we do that?

Do we put the same CA cert in all 3 directories, and each of the CRLs in one of those directories?

Thanks,
Jim

**Comment by xipki** [comment]
Could you please email me (lijun DOT liao AT gmail DOT com) the three CRLs and the CA certificate, and if in case of indirect CRL, the CRL signer certificate? I will evaluate the CRLs.

For your question, you need to put the same CA certificate to all 3 directories.

**Comment by ohaya100** [comment]
I will email them or post a link for you in a bit, but FYI, I got confirmation that in our existing OCSPD configuration, they actually have the 3 CRLs being served.  They said the OCSPD distinguishes them by the AKIDs (which are different for each.

So  are you saying for XiPKI we'd create 3 dirs, put the same CA cert into all 3 dirs, and put the separate CRLs in the separate dirs?  

Would OCSPD be able to distinguish OCSPD requests by the AKIDs?

Thanks,
Jim

**Comment by ohaya100** [comment]
FYI, I sent you a link for the files.

Thanks,
Jim

**Comment by xipki** [comment]
> So are you saying for XiPKI we'd create 3 dirs, put the same CA cert into all 3 dirs, and put the separate CRLs in the separate dirs?
You should have three different CA certificates with different public key, not the same CA cert.

> Would OCSPD be able to distinguish OCSPD requests by the AKIDs?
YES.
