### ISSUE TITLE
org.xipki.util.InvalidConfException: xipki/etc/ocsp/database/ejbca-db.properties

### ISSUE THREAD

**Issue by adeuxdev2** [xipki/xipki#146]
Hi,

Trying to set up a standalone ocsp responder linked to EJBCA CA.

system:
Tomcat 9.0.31
ocsp-war-5.3.6

Followed the steps in ocsp README.md.

Tomcat management page shows ocsp as running

However, ocsp.log shows the following error:
2020-02-19 16:53:07,296 ERROR o.x.o.s.OcspServerImpl [main] could not start OCSP responder
org.xipki.util.InvalidConfException: xipki/etc/ocsp/database/ejbca-db.properties

The file ejbca-db.properties does not exist.

xipki/etc/ocsp/database/ contains:
Directories:
db2  h2  hsqldb  mariadb  mysql  oracle  pgsql
Files:
ca-db.properties

So where can I find the ejbca-db.properties file?

**Comment by adeuxdev2** [comment]
As a follow up, I copied the existing ca-db.properties to ejbca-db properties to see if that would resolve the issue.  That went a little further then threw this error:

org.xipki.util.InvalidConfException: ObjectCreationException of store store1:unknown OCSP store type ejbca

**Comment by xipki** [comment]
The example configuration contains a typo. Please change the type from "ejbca" to "ejbca-db" in `xipki/etc/ocsp/ocsp-responder.json` as follows:
```
                "source":{
                        "datasource":"datasource1",
                        "type":"ejbca",
                        "conf":{
                        }
                }
```
to

```
                "source":{
                        "datasource":"datasource1",
                        "type":"ejbca-db",
                        "conf":{
                        }
                }
```
