### ISSUE TITLE
OCSP Validation "suddenly fails"

### ISSUE THREAD

**Issue by ohaya100** [xipki/xipki#150]
Hi,

We have been testing OCSP validation with Oracle OAM and it working well, except that we have noticed that it seems like after some time ("some time" is undefined at this point), OAM starts reporting that the OCSP validation is not longer working.  Here is part of the stacktrace in the OAM logging that we see when this happens:

Caused By: java.security.cert.CertPathValidatorException: Could not determine revocation status
at sun.security.provider.certpath.CrlRevocationChecker.buildToNewKey(CrlRevocationChecker.java:675)
at sun.security.provider.certpath.CrlRevocationChecker.verifyWithSeparateSigningKey(CrlRevocationChecker.java:487)
at sun.security.provider.certpath.CrlRevocationChecker.verifyRevocationStatus(CrlRevocationChecker.java:362)
at sun.security.provider.certpath.CrlRevocationChecker.verifyRevocationStatus(CrlRevocationChecker.java:270) 

When this happens, we seem to be able to get the OCSP validation to start working simply by changing a checkbox in OAM to not use OCSP, then changing that same checkbox for OAM to use OCSP again.

I have opened an SR (a case) at Oracle support on this problem also, but I wanted to post an issue here in case you have any suggestions, because I noticed that when I run netstat on port 8080 during our OAM OCSP validation testing (we are running load tests) I see maybe 4-5 connections from OAM to XiPKI, so I am wondering if maybe there is something in XiPKI that might account for this problem?  

FYI XiPKI seems to continue to listen to 8080 even when OAM is reporting the failure to do OCSP validation, so I don't think that is the case.

Thanks,
Jim

**Comment by ohaya** [comment]
Hi,

I have gotten feedback from the SR that I opened, and they are suggesting that the problem may be caused because OAM is unable to connect to XiPKI.  

As I mentioned earlier, when I run a load test, and then do "netstat -an | grep 8080" I see a bunch of connections (5 or 6, on the XiPKI side, ESTABLISHED) then after the load test, the connections are in TIME_WAIT for awhile.   

If I start another load test right away, that works ok, but it seems like, if I wait "awhile" after the load test ("awhile" is undefined) then the next time I do a load test, OAM is reporting it cannot determine revocation status.

Jim

**Comment by xipki** [comment]
This may be related to #151. As solution please delete the `maxKeepAliveRequests="-1"` in the file `conf/server.xml` and restart the tomcat server.

**Comment by ohaya** [comment]
Hi,

We are using Tomcat 9.0.20, and it looks like the out-of-box server.xml doesn't have "maxKeepAliveRequests" at all...

Jim

**Comment by ohaya** [comment]
Hi,

From this:  https://tomcat.apache.org/tomcat-9.0-doc/config/http.html

it looks like that param is set to 100 by default...

**Comment by ohaya** [comment]
Hi,

FYI, I just did the same test scenario with another OCSPD that we have been using for awhile now and that is having the same problem with OAM as XiPKI was showing, so this problem does not appear to be related to XiPKI exclusively.

If possible, and if OK, can we hold this issue open for awhile?

Thanks,
Jim

**Comment by xipki** [comment]
> If possible, and if OK, can we hold this issue open for awhile?

YES

To identify the problem, please use other tool, like openssl, to test whether XiPKI or other OCSPD can answer correctly.

**Comment by ohaya** [comment]
Hi,

After more discussions with Oracle, this problem appears to be a problem with OAM and OCSP validation, i.e., it is not a problem with XiPKI OCSPD, so we can close this issue
