### ISSUE TITLE
CRL is imported, Message in ocsp.log: "the folder xipki/crls/example-crls/certs does not exist, ignore it"?

### ISSUE THREAD

**Issue by ohaya** [xipki/xipki#152]
Hi,

I noticed that when a CRL is imported into XiPKI OCSPD, the following message appears in the ocsp.log file:

"the folder xipki/crls/example-crls/certs does not exist, ignore it"

The CRL import seems to be working, but why is that message appearing, and what is the "xipki/crls/example-crls/certs" folder?

SHOULD that folder exist, and if so, what should be in it?

Should I just create an empty "xipki/crls/example-crls/certs" folder?

Thanks,
Jim

**Comment by xipki** [comment]
This is related to #148. In your case just ignore this error message.
