### ISSUE TITLE
Can OCSP server not sign response when used as proxy OCSP responder ?

### ISSUE THREAD

**Issue by Samuel9270** [xipki/xipki#156]
Hello,

I am developing enterprise internal applications dealing with digitally signed document.
Signatures use x509 certificates issued by different partners CA certificates for which I do not own the private keys of course. The CAs all publish their respective CRLs.

I would like to centralize the signing certificates trust and revocation status validation using xipki ocsp responder server as an internal proxy OCSP responder.
I understand from your previous answers to issues that one can import external CRLs from external CAs in OCSP server database and xipki OCSP can generate OCSP response for validating the associated certificates without need to call the CA for signing the response.
All I need to do is configure my applications to trust xipki OCSP response.

My question is : 
Since the xipki OCSP instance is exclusively used by my applications which will be hard configured to call only this responder, can the OCSP response signature disable in xipki OCSP server in order to enhance response time ? There will be no trust issue between my applications and the OCSP response as they all run in an internal secure network.
Or saying it another way, what remote API can my applications (not installed on the same server as xipki OCSP server) call to validate certificate without need for signed response ?

Best regards
Samuel

**Comment by xipki** [comment]
An OCSP response must have signature, as defined in RFC 6960:
```
   BasicOCSPResponse       ::= SEQUENCE {
      tbsResponseData      ResponseData,
      signatureAlgorithm   AlgorithmIdentifier,
      signature            BIT STRING,
      certs            [0] EXPLICIT SEQUENCE OF Certificate OPTIONAL }
```
What you can do is to define you own signer, which just use random / fixed value as signature without computing it.

**Comment by Samuel9270** [comment]
Thank your for your answer. It makes sense.
