### ISSUE TITLE
querry: Expired certificate removal

### ISSUE THREAD

**Issue by tsvinoth** [xipki/xipki#158]
Hi Lijun Liao,

I am using xipki version 5.0.0 .. i just want to know how long the expired certificate information is stored in ca server .. I have a requirement to clean the certificates which are expired 60 days before from ca system .. 

Can you please let me know how this can be achieved .. Is there any configuration parameter i can set to achieve this ?

Thanks,
Vinoth S

**Comment by xipki** [comment]
The expired certificates will be removed from the database after a defined period, which is specified in the field `EXPIRATION_PERIOD` of the database table `CA`. The period is the number of days.

This field can be changed by the command `ca:ca-up` with the parameter `--keep-expired-certs`.

**Comment by tsvinoth** [comment]
Hi Lijun Liao,

Thanks for the reply .. I will try and get back to you ..

Thanks,
Vinoth S
