### ISSUE TITLE
Query : Deadlock: wsrep aborted transaction 

### ISSUE THREAD

**Issue by tsvinoth** [xipki/xipki#159]
Hi Lijun Liao,

I am using xipki version 5.0.0 .. i have a setup consist of 1 master and 2 slave mode with external mariadb .. sometimes i am seeing this error on log files .. But certificate fetch is happening after couple of retires ..

```
13:28:54.906 [http-nio-127.0.0.1-8181-exec-1] ERROR o.x.c.s.p.OcspStoreQueryExecutor - datasource ocsp could not add certificate with id 42632234238649730: (conn=982011) Deadlock: wsrep aborted transaction
13:28:55.457 [http-nio-127.0.0.1-8181-exec-1] ERROR o.x.c.s.publisher.OcspCertPublisher - could not save certificate (issuser='cn=ztsca,o=nokia,c=IN': subject='cn=configserverservice-zts1.service.dc1.default.svc.cluster.local,o=nokia,c=IN', serialNumber=0x5aca5a3f5df53d02). Message: DeadlockLoserDataAccess - SQL [INSERT INTO CERT (ID,LUPDATE,SN,NBEFORE,NAFTER,REV,IID,HASH,SUBJECT) VALUES (?,?,?,?,?,?,?,?,?)]; (conn=982011) Deadlock: wsrep aborted transaction
```
Can you please help me on this ..

[ca-2020-04-21.0.log](https://github.com/xipki/xipki/files/4519866/ca-2020-04-21.0.log)
[ca-2020-04-22.0.log](https://github.com/xipki/xipki/files/4519867/ca-2020-04-22.0.log)

Thanks,
Vinoth S

**Comment by xipki** [comment]
You seem to use MariaDb Galera Cluster. This seems to be a database issue. Please refer to the corresponding group / forum.

**Comment by tsvinoth** [comment]
Hi Lijun Liao,

Thanks for the reply .. I will check the mariadb side ..

Thanks,
Vinoth S
