### ISSUE TITLE
How to tell whether cache was deployed or not?

### ISSUE THREAD

**Issue by ohaya** [xipki/xipki#163]
Hi,

I was looking at the copies of ocsp-responder.json and it looks like about Jan 16, we disabled the cache and I labelled that version of the ocsp-responder.json to indicate that version was "disable cache to try to fix the cache problem".

Do you remember what that "cache problem" was, and is it fixed now?

We are doing performance tests again, and we are seeing somewhat slow response times, so I believe the cache is commented out in the ocsp-responder.json, but I don't remember why we did that.

Thanks,
Jim

EDIT 1: I went back in Issues and see that we ran into a problem on 1/17/19 and that problem was subsequently fixed.  So can you tell me (a) which version has the fix and (b) how do we tell which XiPKIK version we have?

**Comment by xipki** [comment]
The cache bug is reported in #140. It is fixed in v5.3.6.

**Comment by ohaya** [comment]
Hi,

Thanks for that info.  Unfortunately, on the environment that I have to test on, it is at 5.3.1(!).  I tried to re-enable the cache, but when I do that I get errors during my load testing (due to time related things), so I think that is the same errors I was seeing for that earlier issue.  I will see if someone can re-run the tests with the cache enabled after they bring the XiPKI to a newer version.

Jim

**Comment by ohaya** [comment]
Info received.  Thanks
