### ISSUE TITLE
OCSP Cache enabled, but not working!

### ISSUE THREAD

**Issue by ohaya** [xipki/xipki#167]
Hi,

So I got the cache schema rectified and I think that cache is working:

216b669
2020-05-27 11:37:54,275 INFO o.x.s.SignerFactoryRegisterImpl [main] added SignerFactory binding for org.xipki.security.pkcs11.P11SignerFactory@3a577be3
2020-05-27 11:37:54,287 INFO o.x.o.s.OcspServerImpl [main] starting OCSPResponder server ...
2020-05-27 11:37:54,323 INFO c.z.h.HikariDataSource [main] HikariPool-3 - Starting...
2020-05-27 11:37:54,346 INFO c.z.h.HikariDataSource [main] HikariPool-3 - Start completed.
2020-05-27 11:37:54,372 INFO o.x.o.s.s.ResponseCacher [main] OCSP response cacher is on service
2020-05-27 11:37:54,642 INFO c.z.h.HikariDataSource [main] HikariPool-4 - Starting...
2020-05-27 11:37:54,647 INFO c.z.h.HikariDataSource [main] HikariPool-4 - Start completed.
2020-05-27 11:37:54,650 INFO o.x.o.s.s.CrlDbCertStatusStore [main] CertStore store1 not changed
2020-05-27 11:37:54,660 INFO o.x.o.s.s.DbCertStatusStore [main] Updated issuers of store store1
2020-05-27 11:37:54,664 INFO o.x.o.s.s.DbCertStatusStore [main] Updated CRL_INFOs of store store1
2020-05-27 11:37:54,665 INFO o.x.o.s.OcspServerImpl [main] started OCSPResponder server
2020-05-27 11:37:54,667 INFO o.x.o.s.OcspServletFilter [main] remote management is disabled
2020-05-27 11:42:55,247 INFO o.x.o.s.s.ResponseCacher$ExpiredResponsesCleaner [pool-2-thread-1] removed 0 response with thisUpdate < 1590493375
2020-05-27 11:43:42,375 INFO o.x.o.s.s.ResponseCacher$ExpiredResponsesCleaner [pool-5-thread-1] removed 0 response with thisUpdate < 1590493422
2020-05-27 11:44:35,247 INFO o.x.o.s.s.ResponseCacher [pool-2-thread-1] OCSP response cacher is on service
2020-05-27 11:45:22,374 INFO o.x.o.s.s.ResponseCacher [pool-5-thread-1] OCSP response cacher is on service

but when I load test, it is REALLY SLOW...

So I checked the ocspcache tables, and they seem to be empty?

Is there something else that I need to change in order to get the OCSP cache working?

Thanks,
Jim

**Comment by ohaya** [comment]
Nothing is getting populated into the ocspcache tables:

mysql> show tables;
+---------------------+
| Tables_in_ocspcache |
+---------------------+
| ISSUER              |
| OCSP                |
+---------------------+
2 rows in set (0.01 sec)

mysql> select count(*) from ISSUER;
+----------+
| count(*) |
+----------+
|        0 |
+----------+
1 row in set (0.00 sec)

mysql> select count(*) from OCSP;
+----------+
| count(*) |
+----------+
|        0 |
+----------+
1 row in set (0.00 sec)

**Comment by ohaya** [comment]
Hi - this is ocsp-responder.json:

{
        "responseCache":{
                "datasource":{
                        "name":"datasource-cache",
                        "conf":{
                                "file":"etc/ocsp/database/ocsp-cache-db.properties"
                        }
                },
                "validity":"1d"
        },
        "master":true,
        "unknownIssuerBehaviour":"malformedRequest",
        "datasources":[{
                "name":"datasource1",
                "conf":{
                        "file":"etc/ocsp/database/ocsp-crl-db.properties"
                }
        }],
        "requestOptions":[{
                "name":"request1",
                "hashAlgorithms":["SHA1","SHA256","SHA384","SHA512"],
                "maxRequestListCount":10,
                "maxRequestSize":4096,
                "nonce":{
                        "maxLen":32,
                        "minLen":4,
                        "occurrence":"optional"
                },
                "signatureRequired":false,
                "supportsHttpGet":true,
                "validateSignature":false,
                "versions":["v1"]
        }],
        "responders":[{
                "name":"responder1",
                "inheritCaRevocation":true,
                "mode":"RFC2560",
                "request":"request1",
                "response":"response1",
                "servletPaths":["/"],
                "signer":"signer1",
                "stores":["store1"]
        }],
        "responseOptions":[{
                "name":"response1",
                "embedCertsMode":"SIGNER",
                "includeCerthash":false,
                "includeInvalidityDate":false,
                "includeRevReason":true,
                "responderIdByName":true
        }],
        "signers":[{
                "name":"signer1",
                "type":"pkcs12",
                "algorithms":["SHA256withRSA"],
                "caCerts":[],
                "key":"password=XXXX,keystore=file:keycerts/ocsp1.p12"
        }],
        "stores":[{
                "name":"store1",
                "ignoreExpiredCert":true,
                "ignoreNotYetValidCert":true,
                "includeArchiveCutoff":false,
                "includeCrlId":false,
                "retentionInterval":-1,
                "minNextUpdatePeriod":"1d",
                "unknownCertBehaviour":"good",
                "updateInterval":"10m",
                "source":{
                        "datasource":"datasource1",
                        "type":"crl",
                        "conf":{
                                "dir":"crls/template",
                                "ignoreExpiredCrls":true,
                                "sqlBatchCommit":1000
                        }
                }
        }]
}

**Comment by xipki** [comment]
Currently only responses for requests without nonce are cached. If the request contains nonce, but response not, some verification software will not accept the response.

But in the next release, I will add option to not include nonce in the response so that they can be cached. 

In you cases, if you still want to use the cache, you need to not embed nonce in the request or wait for the next release.

**Comment by ohaya** [comment]
Oh.  So for the load test I am doing, it is an Oracle product, Oracle Access Manager (OAM) that is sending the OCSP requests to XiPKI, so I don't think that we have any control of whether or not they send a nonce with the OCSP requests, nor can we control whether or not OAM expects the nonce on the response.  

Also, I am a little confused by your response.  I think that what you are saying is;

- Right now, XiPKI only will only cache a response if the original incoming request did NOT have a nonce.  So, I think that you are also saying that you are guessing that the requests that OAM are sending to XiPKI HAVE nonces, and you are guessing that THAT is why we are not seeing anything being saved in the XiPKI cache database.  Is that correct?

- And regarding what you are thinking of doing/adding is the ability for XiPKI to receive a request that HAS A NONCE, and then store the response in the cache db, BUT WITHOUT THE/A nonce, and you are assuming that the OAM will accept that response (which doesn't have the/a nonce).  Is that correct?

Thanks,
Jim

**Comment by xipki** [comment]
> Right now, ... Is that correct?

YES.

> And regarding. ... Is that correct?

I will add also a flag to control it. If your client does not accept the response, you can just disable the cache for such case.

**Comment by ohaya** [comment]
Hi,

Sorry for being such a pain, but I've been thinking about what has been said and it is giving me a serious headache :)!!

So I think we need to think about two separate things:

1) What happens with nonce vis-a-vis request/response
2) What determines whether response gets cached by XiPKI

So for (1), am I correct that RIGHT NOW, the way that XiPKI works is:

- If request has a nonce, then XiPKI will ALWAYS include the nonce with the corresponding response, and
- If request does not have nonce, then XiPKI will send response (with no nonce).

And, for (2), am I correct that RIGHT NOW, the way that XiPKI works is:

- If request has a nonce, XiPKI will not cache the corresponding response, and
- If request does not have a nonce, will cache the corresponding response


Finally, and separately, I think that you were saying that some clients will not verify a response if the client sent a request with a nonce, but the response that came back to the client does not have a nonce, right?

**Comment by ohaya** [comment]
I was wondering if we enable the request logging and set the logging properties file to DEBUG, can we tell from the output of that, whether the request has a nonce?

Here's an example of the debug output in ocsp.log:

2020-05-27 16:30:16,567 DEBUG o.x.o.s.OcspServlet [http-nio-8080-exec-3] HTTP POST OCSP path: /
Request:
MEIwQDA+MDwwOjAJBgUrDgMCGgUABBSJpgryMXdQ1lkbCUsALZhbQa5QzQQUZLGdh0OtWmz29HfS
lgz5oIoEskwCAQo=
Response:
MIIE9QoBAKCCBO4wggTqBgkrBgEFBQcwAQEEggTbMIIE1zCBqKEvMC0xCzAJBgNVBAYTAkRFMQ4w
DAYDVQQKDAV4aXBraTEOMAwGA1UEAwwFT0NTUDEYDzIwMjAwNTI3MTYzMDE2WjBkMGIwOjAJBgUr
DgMCGgUABBSJpgryMXdQ1lkbCUsALZhbQa5QzQQUZLGdh0OtWmz29HfSlgz5oIoEskwCAQqAABgP
MjAxOTEyMDUwMDE5MTdaoBEYDzIwMjAxMjA0MDAxOTE3WjANBgkqhkiG9w0BAQsFAAOCAQEAekdx
.
.
.
bmRlcjEwVQYDVR0jBE4wTIAU3MzFcPQurPQP1qzaqb6WQNf7hoehMaQvMC0xCzAJBgNVBAYTAkRF
MQ4wDAYDVQQKDAV4aXBraTEOMAwGA1UEAwwFbXljYTGCAQEwHQYDVR0OBBYEFP8DqSecXlRvgD4W
6VZElJwx0xOjMA4GA1UdDwEB/wQEAwIGQDATBgNVHSUEDDAKBggrBgEFBQcDCTAKBggqhkjOPQQD
AgNJADBGAiEAlLq96N9F1eL2+Rgw7S5g8GYfwkitV5fY7lPNmVuMpb4CIQCKaOGFJEibchj65Ogv
/lDv7SxKWzzgeNP4PY2N3lDdiQ==

I am asking because I am willing to ask Oracle if there is a way to cause OAM to send a request without a nonce, but I would like to find out if we know for sure that the requests from OAM do include a nonce first.

Thanks,
Jim

**Comment by xipki** [comment]
The request you posted above does not contain the nonce.

**Comment by xipki** [comment]
Just tested with v5.3.7, the cache of OCSP response works.

**Comment by xipki** [comment]
BTW: the nonce of request can be ignored by setting the `occurrence`  of `nonce` to `ignore`.
Namely:
```
                "nonce":{
                        "occurrence":"ignore"
                }
```

This feature is available in all 5.x versions.

**Comment by ohaya** [comment]
Hi Lijun,

As requested, I have sent the log and ocsp-responder.json.

Jim

**Comment by xipki** [comment]
Please checked the email. According to your log, the caching should work.

**Comment by xipki** [comment]
Does the problem still exist? If not, I will close this issue.
