### ISSUE TITLE
sub ca

### ISSUE THREAD

**Issue by sanjiths** [xipki/xipki#168]
Hi, 

I have a created a root ca (self signed) and also  1 sub ca (ztsca.p12) ..I have copied ztsca.p12 to xipki/ca-setup/cacert-present and i want to configure sub ca using xipki .. when i tried to load the config file i am getting below error ..

```
karaf@root()> source xipki/ca-setup/cacert-present/setup-ec-p12.script ztsca                                                                                                                                       
#################################################################
#                       Load ca-conf.json                       #
#################################################################
Error executing command: could not load configuration xipki/ca-setup/cacert-present/ca-conf.json, error: could not add CA ztsca
karaf@root()>  
```
FYI i have attached the configuration file which i am loading ..Kindly request you for your help! ..I am not sure whether i am doing it correctly .. My goal is to start xipki as sub ca of my own root ca ..

ca-conf.json.txt
Also, attaching logs
[ca-2020-05-30.0.log](https://github.com/xipki/xipki/files/4705141/ca-2020-05-30.0.log)

Thanks,
Sanjith S
[ca-2020-05-30.0.log](https://github.com/xipki/xipki/files/4705143/ca-2020-05-30.0.log)
[ca-conf.json.txt](https://github.com/xipki/xipki/files/4705144/ca-conf.json.txt)

**Comment by xipki** [comment]
`"ca.signerConf":"algo=SHA256withECDSA,password=...,keystore=file:xipki/ca-setup/keycerts/ztsca.p12"`

As the log indicates, CA cannot create signer for the configuration above. Please make sure
1. The password is correct.
2. The algo and keystore match (In your case, EC key is expected).

**Comment by sanjiths** [comment]
Hi Lijun Liao,

I have verified the password and also if the algo & keystore match. They seem to be fine but I am still getting the same error.

**Comment by xipki** [comment]
1. Which version of XiPKI do you use?
2. If the keystore is only for test purpose, please upload the keystore file here or drop me an email.

**Comment by sanjiths** [comment]
xipki version: 5.0.0v 

I have shared the keystore file via email.

**Comment by sanjiths** [comment]
Hi Liao,

xipki version: 5.0.0v

I am sharing the keystore file here.

Thanks,
Sanjith S

**Comment by xipki** [comment]
I did not receive any email from you.

**Comment by sanjiths** [comment]
Can I have your mail  id ?

**Comment by xipki** [comment]
lijun.liao AT gmail DOT com

**Comment by sanjiths** [comment]
i have sent mail.

Thanks,
Sanjith S

**Comment by xipki** [comment]
Just checked the PKCS#12 file. It contains RSA key. But you configure SHA256withECDSA, which requires EC key,  as signature algorithm.  You need to change the signature algorithm to SHA256withRSA.

BTW: The issue system is not only for consulting purpose like this issue.
