### ISSUE TITLE
CSR failing when using Registered Id in Subject Alternative Name

### ISSUE THREAD

**Issue by subyphilip** [xipki/xipki#173]
CSR is failing when using Registered Id in Subject Alternative Name.When it is removed, CSR is working. Could you please help in resolving this issue
1.  part of succesful and failed CSR. Only relevant section is pasted below.
openssl req -text -noout -verify -inform DER -in output/certs/cert.csr
Not working
 Attributes:
        Requested Extensions:
            X509v3 Subject Alternative Name: 
                DNS:elasticsearch, Registered ID:1.2.3.4.5.5
Working
 Attributes:
        Requested Extensions:
            X509v3 Subject Alternative Name: 
                DNS:elasticsearch
2. XIPKI version used : 5.0.0
3. Error in catalina.out
13:56:57.740 [http-nio-127.0.0.1-8181-exec-4] ERROR org.xipki.ca.server.RestResponder - Throwable thrown, this should not happen!
java.lang.IllegalArgumentException: failed to construct sequence from byte[]: unknown tag 13 encountered
        at org.bouncycastle.asn1.ASN1Sequence.getInstance(Unknown Source)
        at org.bouncycastle.asn1.pkcs.CertificationRequest.getInstance(Unknown Source)
        at org.xipki.ca.server.RestResponder.service(RestResponder.java:285)
        at org.xipki.ca.servlet.HttpRestServlet.service0(HttpRestServlet.java:83)
        at org.xipki.ca.servlet.HttpRestServlet.doPost(HttpRestServlet.java:70)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
     …..
 4. /ca/rest/ca/enroll-cert?profile=tls returns an empty DER file

**Comment by xipki** [comment]
Please update one example CSR.

**Comment by subyphilip** [comment]
[CSRwithRegisteredId.txt](https://github.com/xipki/xipki/files/4792149/CSRwithRegisteredId.txt)

**Comment by subyphilip** [comment]
I have uploaded a sample CSR. Please check.

**Comment by xipki** [comment]
Please upload the original CSR in PEM or DER format. Not the text representation.

**Comment by xipki** [comment]
You seems to forward the PEM encoded CSR to the CA, expected is DER encoded.

**Comment by subyphilip** [comment]
1)	We create a certificate key using the command below

openssl genrsa -out output/certs/cert-key.pem 2048

2)	Then we create the CSR (Certificate Signing Request) using the above key with the command below.
openssl req -new -sha256 -key output/certs/cert-key.pem **-outform der -out** output/certs/cert.csr -subj "/CN=zts/O=nokia/C=IN" -reqexts req_ext -config <(cat output/certs/my_oids.conf <(printf "DNS.1=elasticsearch\nRID.1=sgID"))

Output file is attached and as you can see from the highlighted part this is generated in der format
3)	We verify the file contents of csr in der format using the following command

openssl req -text -noout -verify **-inform DER
[cert.zip](https://github.com/xipki/xipki/files/4812529/cert.zip)

** -in output/certs/cert.csr


4)	Request the certificate from CA Service using the curl below

curl --insecure --globoff --user <<username>>:<<password>> --header "Content-Type: application/pkcs10" --data-binary "@output/certs/cert.csr" --output output/certs/cert.der https://<IP>:<Port>/ca/rest/ca/enroll-cert?profile=tls

**Comment by xipki** [comment]
Very strange. Please use tools like wireshark to capture the request, and then check whether it is DER or PEM encoded. BTW, please provie the log entry, corresponding to the curl request mentioned above, in logs/<host>_access_log.<date>.txt.

**Comment by subyphilip** [comment]
Please find access log, ca log and ca-audit-log attached for the failure case

Access log
127.0.0.1 - - [22/Jun/2020:13:24:21 +0000] "POST /ca/rest/ca/enroll-cert?profile=tls HTTP/1.1" 400 -

ca log
13:24:21.901 [http-nio-127.0.0.1-8181-exec-10] INFO  org.xipki.ca.server.X509Ca -      START generateCertificate: CA=ztsca, profile=tls, subject='cn=zts,o=nokia,c=IN'
13:24:21.903 [http-nio-127.0.0.1-8181-exec-10] WARN  org.xipki.ca.server.X509Ca -     FAILED generateCertificate: CA=ztsca, profile=tls, subject='cn=zts,o=nokia,c=IN'
13:24:21.903 [http-nio-127.0.0.1-8181-exec-10] ERROR org.xipki.ca.server.X509Ca - could not generate certificate for request[0], reverted all generated certificates
13:24:21.903 [http-nio-127.0.0.1-8181-exec-10] ERROR org.xipki.ca.server.X509Ca - (generateCerts 1749), org.xipki.ca.server.OperationExceptionWithIndex: error code: BAD_CERT_TEMPLATE
13:24:21.904 [http-nio-127.0.0.1-8181-exec-10] WARN  org.xipki.ca.server.RestResponder - (service 427) generate certificate, OperationException: code=BAD_CERT_TEMPLATE, message=BadCertTemplateException: generalName tag 8 is not allowed, org.xipki.ca.server.OperationExceptionWithIndex: error code: BAD_CERT_TEMPLATE

ca-audit-log
13:24:21.903 [http-nio-127.0.0.1-8181-exec-10] INFO  xipki.audit.slf4j - ERROR | ca - perf:     status: FAILED  duration: 2     ca: ztsca       event_type: gen_cert      mid: 4729033513f68f78   req_subject: c=IN,o=nokia,cn=zts        certprofile: tls        not_before: 20200622132421      not_after: 20250622132420
13:24:21.904 [http-nio-127.0.0.1-8181-exec-10] INFO  xipki.audit.slf4j - INFO  | ca - perf:     status: SUCCESSFUL      duration: 10    req_type: REST  mid: 4729033513f68f78     ca: ztsca       event_type: enroll-cert requestor: by-user      message: BAD_CERT_TEMPLATE, BAD_CERT_TEMPLATE: BadCertTemplateException: generalName tag 8 is not allowed

**Comment by subyphilip** [comment]
Also attaching the succesful CSR without Registered Id in Subject Alternative Name.
[Succesful_CSR.zip](https://github.com/xipki/xipki/files/4813975/Succesful_CSR.zip)

**Comment by xipki** [comment]
The error description at the beginning (unknown tag 13) was incorrect. This indicates that the CSR is PEM encoded.

The last error description (generalName tag 8 is not allowed) is expected. The certificate profile tls does not allow registeredID (tag 8). You need to change the profile configuration file. Since you use very old version, you need to find a method by yourself to modify it.

**Comment by subyphilip** [comment]
Thank you for your input. Once the certificate profile file is updated, registeredId's could be passed for CSR.
We have an upgrade scenario where certificate profile file cannot be modified. Database table PROFILE need to be altered to add registeredId. The subjectaltname is part of a row in the table. Are there any scripts available for this kind of alteration.
About the old version used in the product, I have joined the team recently and I will plan the version upgrade in our upcoming release.

**Comment by subyphilip** [comment]
I am checking if I am able to do some workaround. Kindly ignore my request for sometime.
