### ISSUE TITLE
causer addition failing in slave mode

### ISSUE THREAD

**Issue by subyphilip** [xipki/xipki#174]
Unable to add user on the slave node. We are running 3 node Tomcat cluster in which Xipki ca war is deployed.  User addition is working from the master node. Could you please have a check.

Xipki version 5.0.0

Slave node output
karaf@root()> ca:user-add --name vnf99
Password:**********
Error executing command: could not add user vnf99, error: operation not allowed in slave mode

karaf@root()> ca:causer-add --user vnf99 --ca ztsca --permission all --profile all
Error executing command: could not add user vnf99 to CA ztsca, error: operation not allowed in slave mode
karaf@root()>

**Comment by xipki** [comment]
You need to do add user in the master node.

**Comment by subyphilip** [comment]
Just to reconfirm, is this the behaviour in the latest release as well?

**Comment by xipki** [comment]
Yes. In all versions.
