### ISSUE TITLE
No CA was activated

### ISSUE THREAD

**Issue by MaxGeorgeBlack** [xipki/xipki#183]
In tomcat manager
![image](https://user-images.githubusercontent.com/27467188/89255797-27695480-d655-11ea-8d63-79a7a6cb8207.png)
the application ca was successfully deployed, but in the karaf cli I can not get any CA information.
![image](https://user-images.githubusercontent.com/27467188/89255840-4cf65e00-d655-11ea-9d8f-b7d1001fd312.png)
And sometimes I saw one error line like " CA system is not initialized yet“.

Could you tell me which step might be wrong?

**Comment by xipki** [comment]
Please provide detailed information as mentioned in the project's README related to new issue.

**Comment by MaxGeorgeBlack** [comment]
Sorry, something wrong with the related images.

the file **${CATALINA_HOME}conf/server.xml** was configured like metioned in the README file ,using NIO connector.

**ca-conf.json** and **ca.json** remain unchanged.

**ca-db.properties** was configured as following.
```
################## MySQL/MariaDB via MariaDB Connector #################

dataSourceClassName = org.mariadb.jdbc.MariaDbDataSource

# choice 1
dataSource.serverName = 127.0.0.1
dataSource.port = 3306
dataSource.databaseName = xipki_ca

# choice 2
#dataSource.url = jdbc:mariadb://localhost:3306/ca

#dataSource.properties = key1=value1&key2=value2
dataSource.user = root
dataSource.password = 15954031572
dataSource.passwordCharacterEncoding = utf8
```

When excuting this command I got one error like this.
```
karaf@root()> source xipki/client-script/cmp-client.script
#################################################################
# Reset CMP client (only required if CA changed the             #
# configuration since last reset / initialization               #
#################################################################
CA client initialization failed
#################################################################
#                 Manage certificate via CMP                    #
#################################################################
# Get CA certificate
Error executing command: initialization of CA client failed
```

**Comment by xipki** [comment]
It seems that you do not setup the CA.
