### ISSUE TITLE
Removal of a ca-user

### ISSUE THREAD

**Issue by subyphilip** [xipki/xipki#184]
Hi Lijun,
We are using 5.3.8. Could you please let me know is there an option to remove causer completely from the system?

We are doing the following steps
1. ca:user-add --name testuser
//testuser is created
2. ca:causer-add --user testuser --ca testca --permission all --profile all
//User testuser is added to ca <testca>
3.  ca:causer-rm  --user testuser --ca testca -f
//testuser is removed from ca <testca>

We wanted an opposite of command #1. i.e. remove the user from the system. Please let us know is there a command for the same?

**Comment by xipki** [comment]
try `ca:user-rm`.
