### ISSUE TITLE
Configuration of rootCA fails some times

### ISSUE THREAD

**Issue by subyphilip** [xipki/xipki#187]
Sometimes rootCA configuration fails.
karaf@root()> source xipki/ca-setup/cacert-none/setup-ec-p12.script ztsca
#################################################################
#                     Generate Key and CSR                      #
#################################################################
Command not found: xi:ec-p12
karaf@root()>
We are running 5.3.8

But on reattempts it succeeds. Can you pls suggest what could be the reason?

karaf@root()> source xipki/ca-setup/cacert-none/setup-ec-p12.script ztsca
#################################################################
#                     Generate Key and CSR                      #
#################################################################
saved PKCS#12 keystore to file xipki/ca-setup/keycerts/ztsca.p12
saved CSR to file xipki/ca-setup/keycerts/ztsca.csr
#################################################################
#                       Load ca-conf.json                       #
#################################################################

loaded configuration xipki/ca-setup/cacert-none/ca-conf.json
saved certificate of root CA ztsca to xipki/ca-setup/keycerts/ca-ztsca.crt

**Comment by xipki** [comment]
XiPKI CLI uses apache karaf as the base, it may takes some time to load the commands. Just wait for several seconds.
