### ISSUE TITLE
Configuring of CA fails

### ISSUE THREAD

**Issue by subyphilip** [xipki/xipki#192]
Hi Lijun,
CA configuration is failing with following error in ca.log
2020.10.23-13:26:31.189 https-openssl-nio-8443-exec-9 ERROR: HttpMgmtServlet.doPost() CaMgmtException: org.xipki.ca.api.mgmt.CaMgmtException: uknown CA ztsca
	at org.xipki.ca.server.CaManagerQueryExecutor.createCaInfo(CaManagerQueryExecutor.java:522)
	at org.xipki.ca.server.CaManagerImpl.createCa(CaManagerImpl.java:1146)
	at org.xipki.ca.server.CaManagerImpl.addCa(CaManagerImpl.java:1237)
        at org.xipki.ca.server.CaManagerImpl.generateRootCa(CaManagerImpl.java:2354)
	at org.xipki.ca.server.CaManagerImpl.loadConf(CaManagerImpl.java:2841)

2020.10.23-13:26:50.688 http-nio-127.0.0.1-8181-exec-9 WARN: RestResponder.service() unknown CA 'ca'

After this we are seeing CA is restarted, but it is not recovering

2020.10.23-13:27:44.765 main INFO: CaManagerImpl.startCaSystem0() started CA ztsca
2020.10.23-13:27:44.767 main INFO: CaManagerImpl.startCaSystem0() started CA system with following CAs: ztsca
2020.10.23-13:27:44.773 main INFO: CaServletFilter.init() remote management is enabled
2020.10.23-13:27:51.181 http-nio-127.0.0.1-8181-exec-1 WARN: RestResponder.service() unknown CA 'ca'

Alias setting which happens as part of successful start is not appearing in ca.log

We are seeing such issues after intake of 5.3.10. We were not seeing these issues with 5.3.8

We attempted to clean the db using initdb.sh and reconfigure ca. But we are facing the following error in karaf CLI

Error executing command: could not load configuration xipki/ca-setup/cacert-none/ca-conf.json, error: uknown CA ztsca

Attaching the ca.log, CA configuration log,catalina.out and ca-conf.json
[ca_2020.10.23_0.log](https://github.com/xipki/xipki/files/5430520/ca_2020.10.23_0.log)
[configuration.log](https://github.com/xipki/xipki/files/5430521/configuration.log)

**Comment by xipki** [comment]
Did you use master-slave database? Please use only the master instance for the CA configuration. After the configuration, configure the CA to use both master and slave instances, and then restart the CA.

**Comment by subyphilip** [comment]
We use mariadb in maxscale configuration. That is caserver write to maxscale pod which always write the data into master mariadb . Slave mariadb's will get the data from master mariadb.
I have done the following

1. Stopped slave CAservers.
2. Ran the initdb.sh to clean the database in master CAserver.
3. Started tomcat
3. After tomcat is started succesfully, source xipki/ca-setup/cacert-none/setup-ec-p12.script ztsca

Sourcing failed with following error on the console "Error executing command: could not load configuration xipki/ca-setup/cacert-none/ca-conf.json, error: uknown CA ztsca"
The same error is thrown as exception in ca.log 

2020.10.25-16:24:55.698 https-openssl-nio-8443-exec-9 ERROR: HttpMgmtServlet.doPost() CaMgmtException: org.xipki.ca.api.mgmt.CaMgmtException: uknown CA ztsca
        at org.xipki.ca.server.CaManagerQueryExecutor.createCaInfo(CaManagerQueryExecutor.java:522)
        at org.xipki.ca.server.CaManagerImpl.createCa(CaManagerImpl.java:1146)
        at org.xipki.ca.server.CaManagerImpl.addCa(CaManagerImpl.java:1237)
        at org.xipki.ca.server.CaManagerImpl.generateRootCa(CaManagerImpl.java:2354)
        at org.xipki.ca.server.CaManagerImpl.loadConf(CaManagerImpl.java:2841)
        at org.xipki.ca.servlet.HttpMgmtServlet.doPost(HttpMgmtServlet.java:496)

The issue was not seen when we were using mariadb galera cluster mode. We started hitting this from the time we moved to xipki 5.3.10 (old 5.3.8) and mariadb maxscale mode.

Attaching the ca.log, audit.logs, configuration console log.
[audit_2020.10.23_0.log](https://github.com/xipki/xipki/files/5435371/audit_2020.10.23_0.log)
[ca_2020.10.25_0.log](https://github.com/xipki/xipki/files/5435373/ca_2020.10.25_0.log)
[catalina.2020-10-25.log](https://github.com/xipki/xipki/files/5435374/catalina.2020-10-25.log)
[configuration.log](https://github.com/xipki/xipki/files/5435375/configuration.log)
[localhost_access_log.2020-10-25.txt](https://github.com/xipki/xipki/files/5435376/localhost_access_log.2020-10-25.txt)

**Comment by xipki** [comment]
XiPKI uses HikariCP as the database pool. As in [this issue] (https://github.com/brettwooldridge/HikariCP/issues/625) discussed, MySQL / MariaDB Replication Driver does not work with HikariCP.

As [this site](https://mariadb.com/kb/en/failover-and-high-availability-with-mariadb-connector-j/) describes, write-query will access master node, and read-query the slave node. This should be the reason why an entry is added to the database, but the read query says that such an entry does not exist. The replication mode seems to be NOT suitable for the use in XiPKI.
