### ISSUE TITLE
DB user mismatch 

### ISSUE THREAD

**Issue by meghana-svg** [xipki/xipki#197]
[catalina.2021-01-21.log](https://github.com/xipki/xipki/files/5855105/catalina.2021-01-21.log)
[audit_2021.01.21_0.log](https://github.com/xipki/xipki/files/5855106/audit_2021.01.21_0.log)

Hi Lijun,

We are using xipki-5.3.10 and we have hit an issue with user addition in the DB.

In the DB we are able to see that the user "udm61" has been added as below:

    
MariaDB [ca]> select * from TUSER where NAME="udm61";
+----+-------+--------+-------------------------------------------------------------------------------------------------------------------------+
| ID | NAME | ACTIVE | PASSWORD |
+----+-------+--------+-------------------------------------------------------------------------------------------------------------------------+
| 9 | udm61 | 1 | 10000:e64223a2413dcfe2a7ea14c70fed1a41fdc54305f8aac51a:a533503bc51791cd9da9938d18d33466d4b79c8b8f9f47051eb02cfa63690f9c |
+----+-------+--------+-------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.006 sec)

    
MariaDB [ca]> select * from CA_HAS_USER where USER_ID=9;
+----+-------+---------+------------+----------+
| ID | CA_ID | USER_ID | PERMISSION | PROFILES |
+----+-------+---------+------------+----------+
| 9 | 1 | 9 | 511 | all |
+----+-------+---------+------------+----------+
1 row in set (0.007 sec)

MariaDB [ca]>

But when we try to get the info using karaf prompt we get the error as:

karaf@root()> ca:user-info udm61
Error executing command: unknown user udm61

Another issue is that user "udm199" is not present in the DB, But when we execute get user info we get the following output:

MariaDB [ca]> select * from TUSER where NAME="udm199";
Empty set (0.002 sec)

MariaDB [ca]> 

karaf@root()> ca:user-info udm199
id: 5
name: udm199
active: true
password: *****

----- CA zts1-----
profiles: [all]
permission: key_update|gen_crl|get_crl|enroll_cross|gen_keypair|enroll_cert|revoke_cert|unrevoke_cert|remove_cert
karaf@root()>

Can you please suggest a workaround for this.

Also attaching the logs for reference.

Thanks,
Meghana
[ca_log.txt](https://github.com/xipki/xipki/files/5854927/ca_log.txt)

**Comment by xipki** [comment]
As shown in the attached ca_log.txt:
```
2021.01.21-15:35:25.216 https-openssl-nio-8443-exec-6 INFO: CaManagerQueryExecutor.addUser() added user 'udm199'
2021.01.21-15:35:25.725 https-openssl-nio-8443-exec-7 INFO: CaManagerQueryExecutor.addUserToCa() added user '(id=5, name=udm199)' to CA '(id=1, name=zts1)': permission: 511; profile: all
```
You added the user `
udm99` but not `udm61`.

Please make sure that you are working on the correct database.

**Comment by subyphilip** [comment]
Hi Lijun,
The system has got into wrong state from where we couldn't recover.
udm61 got added into DB. We don't have any direct interface to MariaDB. But we are not seeing the udm61 added line in the ca_log
udm199 even though we are seeing the "added" line in the ca_log. It is not showing in the mariaDB. 
We have restarted the mariaDB, restarted Xipki, but the system remained in the same state. Karaf CLI says user doesn't exist even though it is part of DB and the users shown in Karaf CLI is not part of the DB. 
We are using Xipki 5.3.10. If the issue re-occur in our environment, can you please suggest what logs we need to collect? Is there any command to recover that is force-read from MariaDB and reset.

**Comment by xipki** [comment]
Just checked all code. I cannot find any reason why this should happen if the database configuration is correct. Please double check your database configuration.

**Comment by meghana-svg** [comment]
Closing the issue as we are not hitting the similar issue with redeployment.
