### ISSUE TITLE
[query] : crl update types supported in xipki

### ISSUE THREAD

**Issue by WheeskyJack** [xipki/xipki#199]
Hi Lijun,
We are trying to use the crl feature from the xipki.
We saw that if any cert is reoked, the crl was not updated automatically.
If we call the rest api to generate new crl, we saw that crl is updated with revoked cert.
So  i wanted to know the ways in which crl list can be updated.
For example :
is there any flag present to set the behaviour of crl auto update on revokation.
is there any flag present to set the behaviour of crl update at periodic interval? if so, can the interval be set by user or is it fixed?
Thanks in advance for the reply!!!
@xipki 
Br.

**Comment by xipki** [comment]
In general, the CRL will be generated with configured interval. This can be set via the command in the xipki-cli:
```
ca:ca-up --name <ca-name> --crl-control 'fullcrl.intervals=7,interval.time=02:00,overlap.days=3'
```

The full.intervals specify the interval in days to generate the CRL. You may use lower value like 2 for two days.

You can confirm your configuration via the command `ca:ca-info <ca-name>` under the section 'CRL control'.

**Comment by WheeskyJack** [comment]
Thanks for the reply.
So, the crl is generated at periodic interval and the interval can be set using xipki-cli.
Is crl auto-update on revocation of cert present? (this is in addition to periodic interval publish method)

**Comment by xipki** [comment]
> Is crl auto-update on revocation of cert present?
No.
