### ISSUE TITLE
CA and OCSP can be installed in the same servlet container

### ISSUE THREAD

**Issue by plpzg** [xipki/xipki#200]
"CA and OCSP can be installed in the same servlet container"
How to do that ? How to set setenv.sh / setenv.bat for both .war file - ca.war/ocsp.war ?

**Comment by xipki** [comment]
If you operate both CA and OCSP in the same servlet container (tomcat), they have to use the same the XIPKI_DIR, as configured in the setenv.(sh|bat) script.
