### ISSUE TITLE
Encryption mechanism of user password

### ISSUE THREAD

**Issue by subyphilip** [xipki/xipki#202]
Hi,
Could you please let me know is there any a way I can view the user password? Below commands mask the username
ca:user-info username
user-info username

In the TUSER table, the password is encrypted.  Can you please tell how the password can be decrypted? This information is for troubleshooting in a live deployment whether the user entered password is matching with the password stored in the system.
| ID | NAME          | ACTIVE | PASSWORD                                                                                                             
  6 | user       |      1 | 10000:bc42e11f4a1576e6f6b8e7d911058ad36a0507b0e0d88f5f:f067405c02282a2935fed646b1d39574260268af3b5b8d26c42353da69dc3ff6 |

**Comment by xipki** [comment]
The text in database is not the encrypted form of password, so you cannot get the password in cleartext.

The text in database is constructed as follows:
`iteration count ':' salt ':' PKCS#5-Scheme2_SHA256 result`.

Where the result is computed using the PKCS#5 Scheme2 with underlying hash algorithm SHA256, the input is the password, the iteration count and the salt.

In other words, if you have password, iteration count and salt, you can compute the result and comparing it with the saved one. If they are of the same, the password is correct. But you cannot extract password from the text saved in database.

**Comment by subyphilip** [comment]
Thanks for the inputs.

**Comment by subyphilip** [comment]
We have an application which want to validate the incoming user password with the password stored TUSER table.  For this request, from where I can get the iteration count and salt?
My aim is I will generate the hash using SHA256 algorithm using incoming password, salt and iteration count and use that to compare with database

**Comment by xipki** [comment]
See my first comment.

**Comment by subyphilip** [comment]
While migrating from Xipki 5 to Xipki 6, we need the user and password data to be ported from Xipki to external source. So that existing devices/users connected to the CA can continue to get certificates with already fetched credentials.

You have already commented in the ticket that it is not possible to decrypt the encrypted password
Please let us know if there is any updates to this over theseyears. i.e with salt and iteration count, can we decrypt the encrypted password.
