### ISSUE TITLE
[Query] Custom expiry for generated certs

### ISSUE THREAD

**Issue by meghana-svg** [xipki/xipki#203]
Hi Lijun,

We are using xipki version 5.3.10.
We have multiple clients requesting the certs and we have a requirement to set the different expiry date for each of the certificates
Is there an option/input in xipki to set the expiry date for the requested certs?

Thank you,
Meghana

**Comment by xipki** [comment]
Yes, you can specify the notBefore and/or notAfter explicitly via request. If you use REST API, you can specify them via `not-before` and `not-after` respectively. The value is UTC time of format `YYYYMMDDhhmmss`.

**Comment by meghana-svg** [comment]
Thank you for your quick response.
