### ISSUE TITLE
[Query] Append "DNS" and "IP" to to SAN (subjectAltName) in the cert

### ISSUE THREAD

**Issue by meghana-svg** [xipki/xipki#204]
Hi Lijun,

We are using xipki version 5.3.10.

We are appending **DNS** and **IP** in the SubjectAltName for fetching the cert. 
For example:
            X509v3 Subject Alternative Name: 
                DNS:nokia.com, IP Address:192.168.11.241, DNS:caserverservice.ztsb2.svc.cluster.local

We are also using other ExternalCA where the SAN is **"nokia.com, IP Address:192.168.11.241,caserverservice.ztsb2.svc.cluster.local"**  during cert fetch and DNS and IP Address will be appended in the certs fetched automatically. And for xipki we are explicitly appending during cert fetch.
Is it compulsory to append DNS and IP in the cert fetch request? or will it append during cert fetch?

Can you please confirm.

Thanks,
Meghana

**Comment by xipki** [comment]
Please describe the question with more details. Who should fill out the SAN entries?

**Comment by subyphilip** [comment]
For other CA's when we give the SAN in the format "abc.com,10.10.10.10,def.com,20.20.20.20",  it is accepted.
But for Xipki, the same SAN doesn't work, cert fetch fails. Only if we prefix "DNS:" and "IP:" respectively, certificate fetch happens.

That means, "abc.com,10.10.10.10,def.com,20.20.20.20" is not accepted, where as
"DNS:abc.com,IP:10.10.10.10,DNS:def.com,IP:20.20.20.20" works

Please note that it is a query only. As we know the workaround, it is not necessary to fix this.

**Comment by xipki** [comment]
In general you can create a PKCS#10 request containing the SAN entries, and then forwards this request to the CA.

**Comment by xipki** [comment]
This issue seems to be solved. Close it.
