### ISSUE TITLE
export-ca command fails from CLI

### ISSUE THREAD

**Issue by plnb** [xipki/xipki#206]
Hello,

we are trying to export existing ca from CLI client:
export-ca --out-dir output/dbexport/ca-test --db-conf /opt/xipki/etc/ca/database/ca-db.properties

but it fails with:
 Error executing command: java.lang.ClassNotFoundException: org.mariadb.jdbc.MariaDbDataSource not found by com.zaxxer.HikariCP [33]

configured database is mysql v8, datasource in ca-db.properties is configured as:
dataSourceClassName = org.mariadb.jdbc.MariaDbDataSource
dataSource.serverName = localhost
dataSource.port = 3306
dataSource.databaseName = ca

db-tool initdb and ca configuration was successful, certificate enrollment too.

Where should we put the jdbc driver (mariadb-java-client-2.6.1.jar) for the CLI client to load it correctly?
We couldn't figure that out from the examples in the repo.

Thanks in advance,
Plamen

**Comment by xipki** [comment]
Which XiPKI version?

**Comment by plnb** [comment]
XIPKI version is 5.3.11, java v11.0.10.

With the attached jdbc driver and configuration file export-ca command now works without problem.

Thank you!
