### ISSUE TITLE
Communication Failure with fetched CRL

### ISSUE THREAD

**Issue by meghana-svg** [xipki/xipki#207]
Hi Lijun,

We are using xipki version 5.3.10. We are facing issue with the fetched CRL and communication fails. We have a backup/Restore mechanism for disaster recovery where the following steps are followed
1. Perform CA configuration
2. Take a backup of MariaDB Xipki configuration
3. Scratch install the machine
4. Restore the backed up MariaDB Xipki configuration
4. Restart Tomcat so that it comes up with new configuration

 After restart, we are able to fetch cert.pem,cacert.pem and crl.pem. But the below command for certificate validation against CRL fails and communication using the certificates fail. :

 [root@qd05-cluster1-masterbm-0 ~]# openssl verify -verbose -crl_check -CRLfile crl.pem -CAfile cacert.pem cert.pem
cert.pem: C = IN, O = nokia, CN = nokia.com
error 3 at 0 depth lookup:unable to get certificate CRL
[root@qd05-cluster1-masterbm-0 ~]#

The same steps were followed in many other labs where it is working fine.So this is some run-time issue.

We have restarted tomcat and fetched new cert and CRL, still the issue persists.

Could please suggest us some work around if any. Attaching the ca,tomcat log and problematic cert.pem,cacert.pem,key.pem and crl.pem

Thanks,
Meghana
[caserver_0.tar.gz](https://github.com/xipki/xipki/files/6449316/caserver_0.tar.gz)
[certs.zip](https://github.com/xipki/xipki/files/6449320/certs.zip)

**Comment by xipki** [comment]
If you take a detailed look at attached crl.pem and cacert.pem, you will find out the they do not match (Authority Key Identifier in crl.pem != 69:28:98:82:8C:27:41:88:A5:EB:73:A1:7D:AC:A2:E3:1E:AE:10:FF in cacert.pem)

```
lliao@hp430:~/source/xipki/tmp/certs$ openssl crl -noout -text -in crl.pem 
Certificate Revocation List (CRL):
        Version 2 (0x1)
        Signature Algorithm: ecdsa-with-SHA256
        Issuer: C = IN, O = nokia, CN = zts6
        Last Update: May  7 11:18:47 2021 GMT
        Next Update: May 17 02:00:00 2021 GMT
        CRL extensions:
            X509v3 Authority Key Identifier: 
                keyid:B9:0D:A1:E1:33:D5:20:98:06:C6:62:4C:3E:52:B8:87:D4:9E:33:82

            X509v3 CRL Number: 
                3
           ...

lliao@hp430:~/source/xipki/tmp/certs$ openssl x509 -noout -text -in cacert.pem 
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 1 (0x1)
        Signature Algorithm: ecdsa-with-SHA256
        Issuer: C = IN, O = nokia, CN = zts6
        Validity
            Not Before: Apr 23 15:40:56 2021 GMT
            Not After : Apr 23 15:40:56 2031 GMT
        Subject: C = IN, O = nokia, CN = zts6
        Subject Public Key Info: ...
        X509v3 extensions: ...
            X509v3 Subject Key Identifier: 
                69:28:98:82:8C:27:41:88:A5:EB:73:A1:7D:AC:A2:E3:1E:AE:10:FF
```

**Comment by xipki** [comment]
This issue seems to be solved. Close it.
