### ISSUE TITLE
Supported profile types

### ISSUE THREAD

**Issue by acbrun0** [xipki/xipki#208]
Hello,

I am currently trying to create a new profile using the `profile-add` command on the CLI. It asks for a _type_, but I cannot figure out what types are accepted. Is there any way to get a list of possible profile types?
Also, I made the profile configuration file by copying one of the available examples and making the necessary changes. Is there another, more streamlined way, or must it be done by hand?

Kind regards,
Bruno

**Comment by xipki** [comment]
In your case the type is xijson.

**Comment by acbrun0** [comment]
Thank you for the quick response.
