### ISSUE TITLE
KeyUsage nonRepudiation

### ISSUE THREAD

**Issue by Dulive** [xipki/xipki#209]
Hello,

I need to create a new profile that only has nonRepudiation as keyUsage, however xipki can't load it and in the logs appears `Exception: java.lang.NullPointerException: keyUsage may not be null` do you know what can it be?

Regards.

**Comment by xipki** [comment]
In general, for such issue, please specify the XiPKI version, the log file, and in your case, also the certificate profile file.

**Comment by Dulive** [comment]
Yep that fixed it.

Thank you very much.
