### ISSUE TITLE
[Query] Support for KMS as an alternative to HSM

### ISSUE THREAD

**Issue by MaheshRudrachar** [xipki/xipki#210]
From compliance and FIPS  can AWS KMS or other KMS solution can be integrated instead of HSM. Thoughts and any plans to support this feature.

**Comment by xipki** [comment]
XiPKI supports the addition of new token types via plugin mechanism. Currently, two token types are supported, PKCS#11 (e.g. for HSM) and PKCS#12 (file based keystore). New token type, e.g. AWS-KMS, may be implemented and added to XiPKI via configuration, and no change in XiPKI is needed.
Support of KMS is not on my roadmap in the next 12 months. You can commit your implementation here and I will merge it.

**Comment by MaheshRudrachar** [comment]
Thanks for your reply. will plan to implement the proposed plugin and then raise PR.

**Comment by xipki** [comment]
You need to implement the interfaces [ConcurrentContentSigner](https://github.com/xipki/xipki/blob/master/security/src/main/java/org/xipki/security/ConcurrentContentSigner.java) and [SignerFactory](https://github.com/xipki/xipki/blob/master/security/src/main/java/org/xipki/security/SignerFactory.java).

**Comment by xipki** [comment]
@MaheshRudrachar Do you have any roadmap for this issue?

**Comment by xipki** [comment]
No update since almost 2 months. Close it first.
