### ISSUE TITLE
[Query] Support for MongoDB

### ISSUE THREAD

**Issue by MaheshRudrachar** [xipki/xipki#211]
Given multi tenancy and large scale deployments in cloud how complex it is to support NoSql like MongoDB.  From architecture and design, does it even possible plz comment?

**Comment by xipki** [comment]
By design, XiPKI requires relational database management system. In theory, one can take XiPKI as base and modify it to use NoSQL. This is, however, not on my roadmap.

**Comment by xipki** [comment]
Related to your requirements "Given multi tenancy and large scale deployments in cloud ", all can be satisfied with the current XiPKI. BTW, I added the performance data to project's README.
