### ISSUE TITLE
All certificate request fail with new XiPKI version

### ISSUE THREAD

**Issue by Dulive** [xipki/xipki#213]
Hello,

with the new XiPKI release all certificate requests fail, and the same XiPKI configuration was working fine with the version 5.3.11 and i just adapted it to the new version.

It gives `ERROR: LogUtil.error() could not generate certificate: java.lang.NullPointerException: Cannot invoke "org.xipki.ca.api.profile.SubjectKeyIdentifierControl.getTruncateMethod()" because "control" is null`

Log file: [ca_2021.06.22_0.log](https://github.com/xipki/xipki/files/6696923/ca_2021.06.22_0.log)

I was curious so i looked at the code and isn't the variable `control` always null since the method `getSubjectKeyIdentifierControl` always returns null, and then there is the attempt to invoke a method?

I'm sorry if I'm wrong, I was just curious.

Regards.

**Comment by xipki** [comment]
Released v5.3.13. Please use this one.

**Comment by Dulive** [comment]
Yep, it's fixed.

Thank you.
