### ISSUE TITLE
[Request]: Add a **max**NextUpdatePeriod parameter

### ISSUE THREAD

**Issue by CampinCarl** [xipki/xipki#215]
Would it be possible to add a `maxNextUpdatePeriod` parameter to limit the _maximum_ `nextUpdate` value, similar to the `minNextUpdatePeriod` parameter? I'm looking to artificially limit the maximum value returned by the responder without having to issue frequent CRLs from an offline CA.

**Comment by xipki** [comment]
Implemented in https://github.com/xipki/xipki/commit/e722ff5ed9e2bfb2e65273d131506fd2c4bc7ac6.

**Comment by CampinCarl** [comment]
Thank you! I'll try to find time to build and test this today on my end.

**Comment by CampinCarl** [comment]
This didn't work for me (or more likely I've done something incorrectly). I built the app from source per the README file and deployed a CRL-type responder, i.e., `xipki/etc/ocsp/example/crl-store/ocsp-responder.json`. I set `maxNextUpdatePeriod` to `7d` in that file, but I'm still seeing dates beyond that.

Any advice? Thanks for your help.

Excerpt from `ocsp-responder.json`
```
{
  "stores": [{
      "name": "store1",
      "ignoreExpiredCert": true,
      "ignoreNotYetValidCert": true,
      "includeArchiveCutoff": false,
      "includeCrlId": false,
      "retentionInterval": -1,
      "minNextUpdatePeriod": "1d",
      "maxNextUpdatePeriod": "7d",    // <- New key here
      "unknownCertBehaviour": "good",
      "updateInterval": "10m",
      "source": {
        "datasource": "datasource1",
        "type": "crl",
        "conf": {
          "dir": "crls",
          "ignoreExpiredCrls": true,
          "sqlBatchCommit": 1000
        }
      }
    }
  ]
}
```

**Comment by xipki** [comment]
Fixed and tested. Please try the up-to-date code.

**Comment by CampinCarl** [comment]
This worked, thank you so much!

---

I found a potential bug you may be interested in, though I was able to work around it.

This configuration:
```
{
  "minNextUpdatePeriod": "1d",
  "maxNextUpdatePeriod": "14d"
}
```
Throws this unexpected error:

> 2021.07.18-12:28:38.838 main ERROR: OcspServerImpl.init() could not start OCSP responder: org.xipki.util.InvalidConfException: minNextUpdatePeriod (1d) > maxNextUpdatePeriod (14d) is not allowed

I'm not a Java dev but I suspect this could be a lexical string comparison problem, i.e., the string `1d` is greater than the string `14d` in a lexical compare. I was able to work around it by setting `maxNextUpdatePeriod` to something else like `2w`. I'm basing this guess on these methods:

- [xipki/OcspStore.java at 66008a3901d9b9d537d423b32f5625609f8cd235 · xipki/xipki](https://github.com/xipki/xipki/blob/66008a3901d9b9d537d423b32f5625609f8cd235/ocsp-api/src/main/java/org/xipki/ocsp/api/OcspStore.java#L240)
    - `if (minNextUpdatePeriod.compareTo(maxNextUpdatePeriod) > 0) {`
- [xipki/Validity.java at 66008a3901d9b9d537d423b32f5625609f8cd235 · xipki/xipki](https://github.com/xipki/xipki/blob/66008a3901d9b9d537d423b32f5625609f8cd235/util/src/main/java/org/xipki/util/Validity.java#L190)
    - `return (validity < obj.validity) ? -1 : 1;`

Hope this is helpful.

**Comment by xipki** [comment]
Thanks for the bug report. Now it should work.

**Comment by CampinCarl** [comment]
Confirmed, thanks again!
