### ISSUE TITLE
[Feature Request] Docker container Image with xipki, tomcat and java installed

### ISSUE THREAD

**Issue by meghana-svg** [xipki/xipki#216]
Hi Lijun,

Currently we are installing xipki, tomcat and java into docker container image manually. This is a tedious task as we need to rebuild the image each time xipki is upgraded. 
We are raising this feature request to explore the possibility of providing the standalone docker container image with xipki installed as a part of every xipki release. This will help us in test and integrate xipki faster in our systems.

Please note: This is a request only.

Thanks,
Meghana

**Comment by xipki** [comment]
Hi Meghana,

could you tell me your whatsapp account via E-Mail (if you have it) or linkedin? We can discuss such issue much more efficient there.

Lijun

**Comment by xipki** [comment]
Please refer to #205.
