### ISSUE TITLE
Confusion about configuration of OCSP db properties.

### ISSUE THREAD

**Issue by PalosChen** [xipki/xipki#228]
Hi @xipki :
   I'm intended to deploy xipki-ocsp. However, I found that the two shell command for CRL and cache OCSP using the same db schema( One file is xipki-ocsp-5.3.13/xipki/etc/ocsp/database/mysql/ocsp-crl-db.properties, the other is xipki-ocsp-5.3.13/xipki/etc/ocsp/database/mysql/ocsp-cache-db.properties). They are different in the directory mariadb. Would you please check it? Thanks a lot!

**Comment by xipki** [comment]
Thanks for the report. Fixed.
