### ISSUE TITLE
Document question

### ISSUE THREAD

**Issue by huang714669** [xipki/xipki#234]
Hi xipki,
I am just follow the guide to install xipki system,  and get confused about the description of Setup CA Server and OCSP Responder
#Start the servlet container.
I don't know about Thales preload or preload script, is this a necessary step or a optional one?
If it is necessary, can you give me some more detail messages about this? Why use this? How to do this step by step?

Thanks

**Comment by xipki** [comment]
Currently please follow README.md, and if you have any questions, please create issue or start a discussion.

**Comment by huang714669** [comment]
Thank you @xipki for your kindly help!
