### ISSUE TITLE
OCSP return 400

### ISSUE THREAD

**Issue by huang714669** [xipki/xipki#235]
Hi Xipki,
By following the readme guide, and install the development version. I have install ca server and ocsp responder without any error message(according to tomcat logs). But when using CLI to execute ocsp request,and get a 400 error(by uncomment the ocsp part of xipki/client-script/rest-client.script and execute this script)
Error message: **Error executing command: IOException: Server returned HTTP response code: 400 for URL: http://localhost:8080/ocsp/**

```
OCSP config:
{
//	"responseCache":{
//		"datasource":{
//			"name":"datasource-cache",
//			"conf":{
//				"file":"etc/ocsp/database/ocsp-cache-db.properties"
//			}
//		},
//		"validity":"1d"
//	},
	"master":true,
	"unknownIssuerBehaviour":"malformedRequest",
	"datasources":[{
		"name":"datasource1",
		"conf":{
			"file":"etc/ocsp/database/ocsp-crl-db.properties"
		}
	}],
	"requestOptions":[{
		"name":"request1",
		"hashAlgorithms":["SHA1","SHA256","SHA384","SHA512"],
		"maxRequestListCount":10,
		"maxRequestSize":4096,
		"nonce":{
			"maxLen":32,
			"minLen":4,
			// valid values are ignore, forbidden, optional and required.
			// in case of ignore and forbidded, maxLen and minLen will be ignored.
			"occurrence":"optional"
		},
		"signatureRequired":false,
		"supportsHttpGet":true,
		"validateSignature":false,
		"versions":["v1"]
	}],
	"responders":[{
		"name":"responder1",
		"inheritCaRevocation":true,
		"mode":"RFC2560",
		"request":"request1",
		"response":"response1",
		"servletPaths":["/"],
		"signer":"signer1",
		"stores":["store1"]
	}],
	"responseOptions":[{
		"name":"response1",
		"embedCertsMode":"SIGNER",
		"includeCerthash":false,
		"includeInvalidityDate":false,
		"includeRevReason":true,
		"responderIdByName":true
	}],
	"signers":[{
		"name":"signer1",
		"type":"pkcs12",
		"algorithms":["SHA256withRSA"],
		"caCerts":[],
		"key":"password=1234,keystore=file:keycerts/ocsp1.p12"
	}],
	"stores":[{
		"name":"store1",
		"ignoreExpiredCert":true,
		"ignoreNotYetValidCert":true,
		"includeArchiveCutoff":false,
		"includeCrlId":false,
		"retentionInterval":-1,
		"minNextUpdatePeriod":"1d",
		"unknownCertBehaviour":"good",
		"updateInterval":"10m",
		"source":{
			"datasource":"datasource1",
			"type":"crl",
			"conf":{
				// please copy the folder crls/template to a new folder, e.g. crls/example-crlstore,
				// and configure it in the following property "dir".
				"dir":"crls/example-crls",
				"ignoreExpiredCrls":true,
				"sqlBatchCommit":1000
			}
		}
	}]
}
```

```
CA INFO:
started: true
aliases: {myca}
id: 1
name: myca1
status: active
max. validity: 10y
expiration period: 365d
signer type: pkcs12
signer conf: algo=SHA256WITHDSA,password=<sensitive>,keystore=base64:MIACAQMwgAYJKoZIhvcNAQcBoIAkgASCA+gwgDCAB...
DHPoc control: null
CMP control:
  confirm cert: false
  send CA cert: true
  send CA cert chain: false
  message time required: true
  send responder cert: true
  message time bias: 300s
  confirm waiting time: 300s
  group enroll: true
  AKI in revocation request required: true
  signature algorithms: [SHA256WITHECDSA, SHA256WITHRSA]
  POPO algorithms: [DHPOP-X25519, DHPOP-X448, ED25519, ED448, SHA256WITHDSA, SHA256WITHECDSA, SHA256WITHRSA, SM3WITHSM2]
CRL control:
  full CRL intervals: 7
  delta CRL intervals: 0
  overlap: 3 days
  use extended nextUpdate: false
  exclude reason: false
  include expired certs: false
  invalidity date mode: optional
  intervalDayTime: generate CRL at 02:00
SCEP control: 
  include CA cert: true
  include certchain: false
  include signer cert: true
  operation GetCRL: supported
CTLog control: 
  null
revoke suspended certificates control: 
  enabled: false
  target reason: CESSATION_OF_OPERATION
  unchanged since: 15d
CMP responder name: responder1
SCEP responder name: scep-responder1
CRL signer name: null
supported protocols:
  CMP: true
  REST: true
  SCEP: true
save request: false
validity mode: CUTOFF
permission:
  enroll_cert
  enroll_cross
  gen_crl
  gen_keypair
  get_crl
  key_update
  remove_cert
  revoke_cert
  unrevoke_cert
keep expired certs: forever
extra control: null
serial number length: 20 bytes
next CRL number: 3
CA URIs:
  CACert URIs:
  OCSP URIs:
    http://localhost:8080/ocsp
  CRL URIs:
    http://ca.myorg.org/crl
  DeltaCRL URIs:
revocation: not revoked
cert: 
  issuer:  cn=myca1,o=myorg,c=DE
  serialNumber: 0x01
  subject: cn=myca1,o=myorg,c=DE
  notBefore: Wed Dec 29 17:35:22 CST 2021
  notAfter:  Mon Dec 29 17:35:22 CST 2031
certchain: null
```
could you please help on this?

**Comment by huang714669** [comment]
I also tried the latest release version v5.3.14, and get the same 400 error when request ocsp by the commands in rest.client.sh, I have leave all the configurations as default, only one place is different:
set signers.algorithms value to "SHA256withRSA"

By the way, I notice that in the readme.md file chapter **Setup CA Server and OCSP Responder**,  seems there is no step for setup ocsp responder, so i am not sure if i have setup ocsp responder correctly?

**Comment by xipki** [comment]
You configured CRLs as the certificate status store. Maybe you forget to copy the needed files to the folder `crls/example-crls`.

In your case, since you have also an XiPKI CA, you may configure the CA database as the certificate status store. Please follow the unpacked README.md of the xipki-ocsp-version.zip.

If you still have problem, you may reach me via wechat xipki9.

**Comment by xipki** [comment]
I added more details about the setup of CRL as status source. See https://github.com/xipki/xipki/commit/42a19245ef223861965af6012d29e11fb05ff9d3.

**Comment by huang714669** [comment]
Have set up both ca and ocsp successfully using latest version 5.3.15-SNAPSHOT, thank you @xipki for your guidance!

**Comment by huang714669** [comment]
`openssl ocsp -nonce -CAfile cacert.pem -url http://localhost:8080/ocsp/ -issuer cacert.pem -cert tls-20220111-133847.pem -text
OCSP Request Data:
    Version: 1 (0x0)
    Requestor List:
        Certificate ID:
          Hash Algorithm: sha1
          Issuer Name Hash: B2878147B384425155A7DAF1769E7E064796BC7A
          Issuer Key Hash: 1A72E0D682D73A5AEF81C46CE008953F0CB5EBAF
          Serial Number: 7CDC88BF14282DAA94293C124E7C5773EAC3709C
    Request Extensions:
        OCSP Nonce: 
            0410B1614CA427D417A4042A070EEDE4690B
OCSP Response Data:
    OCSP Response Status: successful (0x0)
    Response Type: Basic OCSP Response
    Version: 1 (0x0)
    Responder Id: C = DE, O = myorg, CN = OCSP Responder 1
    Produced At: Jan 11 06:24:42 2022 GMT
    Responses:
    Certificate ID:
      Hash Algorithm: sha1
      Issuer Name Hash: B2878147B384425155A7DAF1769E7E064796BC7A
      Issuer Key Hash: 1A72E0D682D73A5AEF81C46CE008953F0CB5EBAF
      Serial Number: 7CDC88BF14282DAA94293C124E7C5773EAC3709C
    Cert Status: revoked
    Revocation Time: Jan 11 05:38:47 2022 GMT
    Revocation Reason: keyCompromise (0x1)
    This Update: Jan 11 06:24:42 2022 GMT
    Next Update: Jan 12 06:24:42 2022 GMT

    Response Extensions:
        OCSP Nonce: 
            0410B1614CA427D417A4042A070EEDE4690B
    Signature Algorithm: ecdsa-with-SHA256
         30:44:02:20:7d:f0:f8:9d:2e:7f:8e:ef:b3:b5:45:d2:8a:70:
         ac:08:9a:a2:94:21:68:85:35:25:34:f9:7a:92:89:18:17:22:
         02:20:18:0f:68:4d:45:b1:cf:8b:8f:97:34:10:84:73:8c:98:
         6a:af:90:1d:00:37:49:b3:0f:fb:02:52:f0:38:f1:8c
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            68:1e:4c:6b:e1:31:ac:28:4e:77:2f:88:1f:9d:09:2f:f8:0b:9d:25
        Signature Algorithm: ecdsa-with-SHA256
        Issuer: C=DE, O=myorg, CN=myca1
        Validity
            Not Before: Jan  5 07:20:57 2022 GMT
            Not After : Jan  5 07:20:57 2027 GMT
        Subject: C=DE, O=myorg, CN=OCSP Responder 1
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    04:b2:d5:e8:0c:01:63:a4:7d:e5:32:57:9e:88:02:
                    ff:de:46:85:ba:c6:12:42:28:53:8f:10:3c:6b:f2:
                    ce:05:6c:1e:31:04:6d:85:d5:94:21:bb:a7:cf:7d:
                    81:38:fc:f9:05:4d:ea:ac:21:b5:46:b2:ba:df:c1:
                    62:2d:f1:f2:a3
                ASN1 OID: prime256v1
                NIST CURVE: P-256
        X509v3 extensions:
            X509v3 Basic Constraints: critical
                CA:FALSE
            Authority Information Access: 
                OCSP - URI:http://localhost:8080/ocsp/

            OCSP No Check: 

            X509v3 CRL Distribution Points: 

                Full Name:
                  URI:http://ca.myorg.org/crl/myca1

            X509v3 Authority Key Identifier: 
                keyid:50:EF:D9:5F:CF:5F:FF:ED:07:5E:11:DC:0A:03:05:AB:FA:4A:E9:CA

            X509v3 Subject Key Identifier: 
                CB:42:97:B7:80:1F:D4:F4:62:A7:C6:8C:11:A5:3D:27:33:DC:8D:14
            X509v3 Key Usage: critical
                Non Repudiation
            X509v3 Extended Key Usage: 
                OCSP Signing
    Signature Algorithm: ecdsa-with-SHA256
         30:46:02:21:00:df:61:a2:8c:eb:fb:f2:1e:65:5a:23:69:4a:
         e5:55:7e:a2:b2:af:e1:47:09:db:49:13:09:ff:3b:35:23:d2:
         a4:02:21:00:a0:45:57:13:3f:2e:16:fc:3b:0d:42:6c:03:91:
         d9:7c:d9:9f:a5:7f:ac:55:7d:e6:30:b5:2c:19:aa:13:1b:b7
-----BEGIN CERTIFICATE-----
MIICWTCCAf6gAwIBAgIUaB5Ma+ExrChOdy+IH50JL/gLnSUwCgYIKoZIzj0EAwIw
LTELMAkGA1UEBhMCREUxDjAMBgNVBAoTBW15b3JnMQ4wDAYDVQQDEwVteWNhMTAe
Fw0yMjAxMDUwNzIwNTdaFw0yNzAxMDUwNzIwNTdaMDgxCzAJBgNVBAYTAkRFMQ4w
DAYDVQQKEwVteW9yZzEZMBcGA1UEAxMQT0NTUCBSZXNwb25kZXIgMTBZMBMGByqG
SM49AgEGCCqGSM49AwEHA0IABLLV6AwBY6R95TJXnogC/95GhbrGEkIoU48QPGvy
zgVsHjEEbYXVlCG7p899gTj8+QVN6qwhtUayut/BYi3x8qOjgfAwge0wDAYDVR0T
AQH/BAIwADA3BggrBgEFBQcBAQQrMCkwJwYIKwYBBQUHMAGGG2h0dHA6Ly9sb2Nh
bGhvc3Q6ODA4MC9vY3NwLzAPBgkrBgEFBQcwAQUEAgUAMC4GA1UdHwQnMCUwI6Ah
oB+GHWh0dHA6Ly9jYS5teW9yZy5vcmcvY3JsL215Y2ExMB8GA1UdIwQYMBaAFFDv
2V/PX//tB14R3AoDBav6SunKMB0GA1UdDgQWBBTLQpe3gB/U9GKnxowRpT0nM9yN
FDAOBgNVHQ8BAf8EBAMCBkAwEwYDVR0lBAwwCgYIKwYBBQUHAwkwCgYIKoZIzj0E
AwIDSQAwRgIhAN9hoozr+/IeZVojaUrlVX6isq/hRwnbSRMJ/zs1I9KkAiEAoEVX
Ez8uFvw7DUJsA5HZfNmfpX+sVX3mMLUsGaoTG7c=
-----END CERTIFICATE-----
Response Verify Failure
4556111296:error:27069065:OCSP routines:OCSP_basic_verify:certificate verify error:crypto/ocsp/ocsp_vfy.c:93:Verify error:unable to get local issuer certificate
4556111296:error:27069065:OCSP routines:OCSP_basic_verify:certificate verify error:crypto/ocsp/ocsp_vfy.c:93:Verify error:unable to get local issuer certificate
tls-20220111-133847.pem: revoked
	This Update: Jan 11 06:24:42 2022 GMT
	Next Update: Jan 12 06:24:42 2022 GMT
	Reason: keyCompromise
	Revocation Time: Jan 11 05:38:47 2022 GMT
`
