### ISSUE TITLE
failed CAs:myca1

### ISSUE THREAD

**Issue by learnSH** [xipki/xipki#236]
After restarting Tomcat, execute the command ca-info with karaf to display the failed ca. What are the possible reasons for the failure?

**Comment by xipki** [comment]
In general, I need the log files of the CA and the client. And in your case, please also provide the console output.

**Comment by learnSH** [comment]
![1641102278(1)](https://user-images.githubusercontent.com/49184447/147867428-8770f0db-e085-45e5-805f-685934391d11.jpg)

**Comment by learnSH** [comment]
[karaf.log](https://github.com/xipki/xipki/files/7798619/karaf.log)

**Comment by learnSH** [comment]
[catalina.log](https://github.com/xipki/xipki/files/7798620/catalina.log)

**Comment by xipki** [comment]
Please upload the log file ca_*.log.

**Comment by learnSH** [comment]
[ca_2022.01.02_0.log](https://github.com/xipki/xipki/files/7798804/ca_2022.01.02_0.log)

**Comment by xipki** [comment]
Did you delete the folder /root/.xipki/pkcs11-emulator after the installation? What is the tree structure now (use command tree)?

**Comment by learnSH** [comment]
After initializing the database, I ran the command

**Comment by learnSH** [comment]
After initializing the database, I ran the command    **xi:delete-key-p11 --label myca1-dsa**      AND  **xi:delete-objects-p11 --label myca1-dsa**   AND    **source xipki/ca-setup/cacert-none/setup-dsa-p11.script**   At this time, everything is normal,Until I restarted tomcat.I seem to understand something................

**Comment by learnSH** [comment]
![image](https://user-images.githubusercontent.com/49184447/147873564-37517d3f-ff56-47ec-89e1-3499ada0c03b.png)
Does this have anything to do with other files?

**Comment by learnSH** [comment]
I found out why.I'll take care of it. Wait a minute. I'll see if it's what I thought.

**Comment by learnSH** [comment]
![image](https://user-images.githubusercontent.com/49184447/147877536-1327789d-398d-4d4f-addf-33e13fd99947.png)
Initialize the ca certificate, the document is source xipki/ca-setup/cacert-one/setup-*.script, should I execute all the scripts here?

**Comment by xipki** [comment]
Just one of them. The file name has the pattern `setup-<keytype>-<tokentype>`, where keytype is dsa, ec, rsa, and sm2, and tokentype is p11 (for PKCS#11), and p12 (for PKCS#12).

**Comment by learnSH** [comment]
![image](https://user-images.githubusercontent.com/49184447/147878356-298fd3d8-ad4d-4bba-a12c-c6479d782ea6.png)
I compared my previous ones, did I use it wrong? I should have used 12

**Comment by learnSH** [comment]
Hey brother,I solved the big problem,Thank you for your guidance,I love you!!!!!!!!!!!!!!!!!!!!!!!!!!
