### ISSUE TITLE
xipki-5.3.14 : Unable to configure CA

### ISSUE THREAD

**Issue by meghana-svg** [xipki/xipki#237]
Hi Lijun,

We have upgraded the xipki version from 5.3.13 to 5.3.14.

We are facing one issue while executing the "setup-ec-p12.script".

In the previous versios below command was executed in the karaf prompt to test if the ca was getting configured using setup-ec-p12.script.

source xipki/ca-setup/cacert-none/setup-ec-p12.script

With xipki 5.3.14 version we are getting the below error:

karaf@root()> source xipki/ca-setup/cacert-none/setup-ec-p12.script zts1                                                                         
#################################################################
#                     Generate Key and CSR                      #
#################################################################
A file named 'xipki/ca-setup/keycerts/myca1.p12' already exists. Do you want to replace it [Yes/No]? Yes
saved PKCS#12 keystore to file xipki/ca-setup/keycerts/myca1.p12
#################################################################
#                       Load ca-conf.json                       #
#################################################################
Error executing command: subject may not be null

We tried to execute each of the commands in the setup-ec-p12.script. Following is the result.

karaf@root()> xi:ec-p12 --password 1234 --out ${KEYCERTS_DIR}/myca1.p12 --curve secp256r1
A file named 'xipki/ca-setup/keycerts/myca1.p12' already exists. Do you want to replace it [Yes/No]? Yes
saved PKCS#12 keystore to file xipki/ca-setup/keycerts/myca1.p12
karaf@root()>                                                                                                                                    
karaf@root()>                                                                                                                                    
karaf@root()> xi:copy-file -f xipki/ca-setup/cacert-none/template.ca-conf.json xipki/ca-setup/cacert-none/ca-conf.json
karaf@root()>                                                                                                                                    
karaf@root()> xi:replace --old "REPLACEME-SUBJECT" --new "CN=myca1,O=myorg,C=DE" xipki/ca-setup/cacert-none/ca-conf.json
karaf@root()>                                                                                                                                    
karaf@root()>                                                                                                                                    
karaf@root()> xi:replace --old "REPLACEME-TOKEN_TYPE" --new "pkcs12" xipki/ca-setup/cacert-none/ca-conf.json
karaf@root()>                                                                                                                                    
karaf@root()>                                                                                                                                    
karaf@root()> xi:replace --old "REPLACEME-CA_SIGNERCONF" --new "algo=${HASH}withECDSA,password=1234,keystore=file:xipki/ca-setup/keycerts/myca1.p12" xipki/ca-setup/cacert-none/ca-conf.json
karaf@root()>                                                                                                                                    
karaf@root()>                                                                                                                                    
karaf@root()> ca:load-conf --conf-file xipki/ca-setup/cacert-none/ca-conf.json --out-dir xipki/ca-setup/keycerts
Error executing command: subject may not be null

We have not made any modifications to the setup-ec-p12.script.

Could you please help us resolve this issue.

Thanks,
Meghana

**Comment by xipki** [comment]
There is a change in the ca-conf.json. Till 5.3.13 you need to genenate a CSR and forward this CSR to the CA. Since 5.3.14 only subject instead CSR is required. So please 

Change
```
			"genSelfIssued":{
				"certOutform":"der",
				"csr":{
					"file":"xipki/ca-setup/keycerts/myca1.csr"
				},
				"profile":"rootca",
				"serialNumber":"1"
			},
```
to
```
			"genSelfIssued":{
				"certOutform":"der",
				"subject":"REPLACEME-SUBJECT",
				"profile":"rootca",
				"serialNumber":"1"
			},
```

**Comment by meghana-svg** [comment]
Thanks a lot for the quick feedback. Issue is resolved now.
