### ISSUE TITLE
xipki-5.3.14 :cert.pem having validity section for date as nil

### ISSUE THREAD

**Issue by meghana-svg** [xipki/xipki#238]
Hi Lijun,

We have upgraded the xipki version from 5.3.13 to 5.3.14.

We are facing issue with the validity section in the cert.pem file.
Hour, minutes and secods are coming as nil. Below is the section from cert.pem for your reference.

[causer@3bb42e5a7a35 cert]$ openssl x509 -in cert.pem -noout -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            70:2d:63:81:c2:d1:eb:e8:54:21:1f:05:6a:c8:58:91:27:6e:c8:92
        Signature Algorithm: ecdsa-with-SHA256
        Issuer: C = FI, O = nokia, CN = zts1
        Validity
            Not Before: Jan  8 00:00:00 2022 GMT
            Not After : Jan  8 00:00:00 2027 GMT
            
         

Due to this certificate validation is failing.

[causer@3bb42e5a7a35 cert]$ openssl verify -CAfile ./cacert.pem ./cert.pem
C = IN, O = nokia, CN = nokia.com
error 9 at 0 depth lookup: certificate is not yet valid
error ./cert.pem: verification failed

audit.log file has the below line which shows the validity as nil.

2022.01.07-09:55:27.608: INFO  | ca - perf:     status: SUCCESSFUL      duration: 18    ca: zts1        event_type: gen_cert    mid: 97fa243019e994b    req_subject: c=IN,o=nokia,cn=nokia.com  certprofile: tls        not_before: 20220108000000      not_after: 20270108000000

Attaching the ca.log, audit.log , cert.pem and cacert.pem  files in the ticket for your reference.

Could you please check this and let us know if there is any WA or if we are missing any configuration.
[ca_2022.01.07_0.log](https://github.com/xipki/xipki/files/7829568/ca_2022.01.07_0.log)
[certs.zip](https://github.com/xipki/xipki/files/7829574/certs.zip)

[audit_2022.01.07_0.log](https://github.com/xipki/xipki/files/7829566/audit_2022.01.07_0.log)

Thanks,
Meghana

**Comment by xipki** [comment]
This is as expected. When the certprofile specify `"notBeforeTime":"midnight",`, then the certificate will have the next midnight time as notBefore. At the time point verification via openssl, the certificate is not not valid (before notBefore). You can change the behavour to use the current time as notBefore via setting `"notBeforeTime":"current",`.

**Comment by meghana-svg** [comment]
Hi Lijun,

Thanks a lot for the feedback. Issue is fixed now.
