### ISSUE TITLE
xipki-5.3.14: pem files removal from the package

### ISSUE THREAD

**Issue by meghana-svg** [xipki/xipki#239]
Hi Lijun,

We are using xipki version to 5.3.14.

Is it save to remove the below files from the package or is there any dependency on these files for configuring CA?? Scans are showing that presence of key files in the package as a vulnerability.

xipki-ca-5.3.14/xipki/keycerts/tlskeys/server/tls-server-key.pem
xipki-cli-5.3.14/xipki/keycerts/tlskeys/client/tls-client-key.pem
xipki-cli-5.3.14/xipki/keycerts/tlskeys/client2/tls-client2-key.pem
xipki-cli-5.3.14/xipki/keycerts/tlskeys/client3/tls-client3-key.pem
xipki-ca-5.3.14/xipki/keycerts/tlskeys/server/tls-server-key.pem

Let us know your feedback on this.

Thanks,
Meghana

**Comment by xipki** [comment]
If they are not referenced in any script and configuration file, they can be deleted.

In general, all keys and certificates delivered MUST NOT be used in the product environment. You need to replace them with your own ones.
