### ISSUE TITLE
Cannot setup CA with HSM

### ISSUE THREAD

**Issue by mahendrahendi** [xipki/xipki#242]
Hi

i'm currently trying to setup CA with HSM, i ran setup-rsa-p11.script 

this is the output

`Error executing command: could not load configuration xipki/ca-setup/cacert-none/ca-conf.json, error: org.xipki.ca.api.OperationException: error code: SYSTEM_FAILURE, error message: ObjectCreationException: could not find slot with index 0
`
this is token-info-p11 output

```
module: default
PKCS#11 IAIK
	Path: /opt/nfast/toolkits/pkcs11/libcknfast.so
	Cryptoki Version: 2.01
	ManufacturerID: nCipher Corp. Ltd               
	Library Description: nCipher PKCS#11 12.60.11-837-510
	Library Version: 12.60
1 slot is configured
	slot[0]: 76140661
```

**Comment by xipki** [comment]
There are two pkcs11.json to configure. The one is in tomcat folder, which will be used by the CA server. The other one is in the xipki-cli, which will be used by the xipki-cli. You need to configure both (you can simple configure one and copy it).

**Comment by mahendrahendi** [comment]
Hi Lijun Liao , thanks for the respond its worked now,

now at the end of the script, when tried to update the certificate to HSM, this error show up
```

#################################################################
#                     Generate Key and CSR                      #
#################################################################
generated RSA key "slot (index = 0, id = 761406613), key (id = 0bab574df3ab6e5d, label = myca1-rsa)"
refreshed token for signer type pkcs11
#################################################################
#                       Load ca-conf.json                       #
#################################################################
loaded configuration xipki/ca-setup/cacert-none/ca-conf.json
saved certificate of root CA myca1 to xipki/ca-setup/keycerts/ca-myca1.crt
removed certificate profile rootca
Do you want to override the file xipki/ca-setup/keycerts/myca1.der (Yes/No)? yes
# Update the certificate in the device
Error executing command: could not createObject: CKR_TEMPLATE_INCONSISTENT
```

**Comment by xipki** [comment]
Please try to delete the lines
```
"CKA_START_DATE",
"CKA_END_DATE",
```
from the file pkcs11.json.

If still not work, please upload the logfile data/log/karaf.log.

**Comment by mahendrahendi** [comment]
> With CKA_START_DATE and CKA_END_DATE the PKCS#11 Certificate Object will be associated with these two attributes. It seems that the nfast HSM does not like them.

i see
i'm studying xipki,and ocsp concept right now, i've tried xipki OCSP with CA database

if i use CRL file for OCSP , do i need generate OCSP key/cert ?

thanks

**Comment by mahendrahendi** [comment]
can it work with my CA? sorry i still study these things
i mean is it necessary to use OCSP key/cert that signed with my CA? or we can use standalone OCSP key/cert

**Comment by xipki** [comment]
This depends on your trust policy. For the test purpose you can use any key/cert that may have no relations with the certificate to be requested.

**Comment by xipki** [comment]
Just changed the code to ignore the "CKA_START_DATE" and "CKA_END_DATE" attributes if the (NFAST) HSM returns CKR_TEMPLATE_INCOSISTENT error. With this change, you do not need to change the configuration file pkcs11.json.
