### ISSUE TITLE
Purge mechanism for issued certificates from the database

### ISSUE THREAD

**Issue by subyphilip** [xipki/xipki#243]
All the certificates  issued by CA are getting stored in the database and they can be viewed using the following command.
ca:list-cert --ca <CAname>

If the CA gets very large number of certificates, it could eventually result in disk full scenario. Can you pls suggest if the following options are available
1. Purge the older certificates based on time-stamp
2. Do not store the certificates in the disk at all. I understand that the CRL functionality need the certificates in disk. But in case, if we decide not to use CRL capability, can we avoid storing certificates in disk 
3. Are the certificates removed from storage once expired/revoked?

**Comment by xipki** [comment]
- `ca:list-cert` will list maximal the first 1000 matching certificates, if there are more than 1000, then not all.
- Point 1: Already supported. The CA can be configured to delete the expired certificates.
- Point 2: Have never seen an enterprise CA that does not save the certificate.
- Point 3: Revoked certificates MUST NOT be removed.

**Comment by subyphilip** [comment]
Purge the older certificates based on time-stamp
Point 1: Already supported. The CA can be configured to delete the expired certificates.
Could you please share the info how this can be configured?

We have an architecture on restart of the pod, pod don't cache the certificate and fetch a new certificate. We are looking at how to avoid CA's disk getting full if there are too many requests, in case if pods continuously restart . 
Qn 4 - Can we remove the older certificates forcefully from the CA system which are not yet expired? For e.g. issued more than 3 years ago. Is there any command or API that can do this? Can we remove certificates from DB directly with Xipki server running/turned off.

**Comment by xipki** [comment]
Related to point 2: I added an option to disable the save of certificates in the database. See https://github.com/xipki/xipki/commit/7e8c16d395128c071fd8435d10fa64c8f7be7a3b for more details.

**Comment by xipki** [comment]
Please update to the latest release v5.3.15.
