### ISSUE TITLE
CRL as OCSP store

### ISSUE THREAD

**Issue by mahendrahendi** [xipki/xipki#250]
Hi

i'm trying xipki-5.3.15  and trying to setup ocsp with crl as store, but i can not find ocsp-crl-init.xml file

> 
![image](https://user-images.githubusercontent.com/45249326/153989862-fd16183b-1a58-44b7-8971-d465d9f9c225.png)

thanks

**Comment by xipki** [comment]
Use ocsp-init.xml instead. Corrected in README.md (see [3175dfa](https://github.com/xipki/xipki/commit/3175dfac4e78952d5de66cb20469c3b77163c2b0)).

**Comment by mahendrahendi** [comment]
Hi Lijun Liao

thanks for reply

can i ask another question,  

if i have rootCA and intermediate , should i bundle it and then put it in crl folder , or only copy intermediate CA to crl folder

because right now,  the response is malformedrequest

i already tried with CA&CRL genareted from xipki and its working, but i tried with another CA&CRL(non xipki )it does not work, why is it


thanks

**Comment by xipki** [comment]
No.
