### ISSUE TITLE
Support for openjdk-11

### ISSUE THREAD

**Issue by subyphilip** [xipki/xipki#252]
I see that Xipki 5.3.15 has 2 packages for Xipki CLI xipki-cli-5.3.15-jdk8.tar.gz and xipki-cli-5.3.15.tar.gz(jdk17). We are using openjdk-11. For jdk-11, please suggest which CLI package should be used ?

**Comment by xipki** [comment]
Please use xipki-cli-5.3.15.tar.gz.
