### ISSUE TITLE
Cannot start CA after HSM migration to common criteria firmware

### ISSUE THREAD

**Issue by NecroX6** [xipki/xipki#254]
Hi

He have 2 nTrust nShield Connect XC HSMs 
one is on old firmware 12.40 FIPS2 world FIPS firmware with no issues to run xipki CA
the second we have in a test lab because we needed to migrate firmware to 12.60.15 Common criteria firmware and common criteria world.
On the second HSM we are unable to run CA because of the CA is unable to load CA signer

`2022.03.30-09:02:01.035 main INFO: IaikP11Slot.close() close all sessions on token: 492971158
2022.03.30-09:02:01.038 main ERROR: LogUtil.error() (<init> 166) security.createSigner caSigner for CA (id=1, name=nfqesca1), org.xipki.security.XiSecurityException: could not initialize the CA signer
2022.03.30-09:02:01.038 main DEBUG: LogUtil.error() security.createSigner caSigner for CA (id=1, name=nfqesca1): org.xipki.security.XiSecurityException: could not initialize the CA signer
        at org.xipki.ca.server.CaInfo.initSigner(CaInfo.java:398)
        at org.xipki.ca.server.X509Ca.<init>(X509Ca.java:164)
        at org.xipki.ca.server.mgmt.Ca2Manager.startCa(Ca2Manager.java:156)
        at org.xipki.ca.server.mgmt.CaManagerImpl.startCaSystem0(CaManagerImpl.java:608)
        at org.xipki.ca.server.mgmt.CaManagerImpl.startCaSystem(CaManagerImpl.java:560)`

[XiPKi_error_CA.txt](https://github.com/xipki/xipki/files/8379951/XiPKi_error_CA.txt)

**Comment by xipki** [comment]
As in the project's README:

For bug-report please upload the testdata and log files, describe the version of XiPKI, OS and JRE/JDK, and the steps to reproduce the bug.

**Comment by xipki** [comment]
No response since 2 months. Please re-open it if needed.
