### ISSUE TITLE
Enabling mutual TLS for Xipki - Maria DB connection.

### ISSUE THREAD

**Issue by adershrp** [xipki/xipki#256]
Hi,
We are planning to enable mTls between Xipki and MariaDB.

Currently our datasource is configurion looks like this.

```
dataSourceClassName = org.mariadb.jdbc.MariaDbDataSource
dataSource.url = jdbc:mariadb://ca-mariadb:3306/ca?user=<dbuser>&password=<dbpasswd>
```

Based on below link, a Java Application can connect with MariaDB using mTls.
https://mariadb.com/kb/en/using-tls-ssl-with-mariadb-java-connector/#mutual-2-way-authentication

Following are the certs file we have at Xipki.

```
key.pem
cert.pem
cacert.pem
```

From these mentioned parameters (https://mariadb.com/kb/en/about-mariadb-connector-j/#tls-parameters), we are not sure what all we should use to configure.

Kindly advice, if there is a best practice/recommendations or documentation available to establish mTls between Xipki and MariaDB.

**Comment by xipki** [comment]
XiPKI uses https://github.com/brettwooldridge/HikariCP for the database connection. Please refer to HikariCP for more information.

**Comment by subyphilip** [comment]
Are the certificates in xipki-ca-5.3.14/xipki/keycerts/tlskeys/  path meant for database connection? I see some of the certs are used for CLI.

**Comment by xipki** [comment]
The certificates and keys there are only for demo purpose. For production environment, you MUST not use them. But in test purpose, you can use them also for the database connection.
