### ISSUE TITLE
Replacing hardcoded certificates with longer validity

### ISSUE THREAD

**Issue by subyphilip** [xipki/xipki#259]
[tlskeys.zip](https://github.com/xipki/xipki/files/8920735/tlskeys.zip)
Xipki version - 5.3.15
Following paths xipki-cli-5.3.15/xipki/keycerts/tlskeys/ and  xipki-ca-5.3.15/xipki/keycerts/tlskeys has hardcoded certificates, xipki/keycerts/tlskeys/client2 is expiring in 2023.
Can you please help us with one of the below options
a. Can the files in keycerts/tlskeys/client2 which is expiring in 2023 be replaced with validity of 2038 same as the other certificates in the tlskeys path. Can these files be provided ?
b. Can the new release from Xipki include longer validity tlskeys certificates including the cacert ~ 100 years to be safe? Keep the older certs in the truststore for backward compatibility
c. We are looking for a procedure to replace them with longer validity certs. How the certificate can be created with longer validity and used?
OR
d. Can the certificates be removed altogether?

Impacted certs folders
xipki-ca-5.3.15/xipki/keycerts/tlskeys
xipki-cli-5.3.15/xipki/keycerts/tlskeys/ 

Error during CA configuration with longer validity certs.

IOException while sending message to the server: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

 xipki/ca-setup/cacert-none/setup-ec-p12.script fz1
l#################################################################
#                     Generate Key and CSR                      #
#################################################################
saved PKCS#12 keystore to file xipki/ca-setup/keycerts/myca1.p12
#################################################################
#                       Load ca-conf.json                       #
#################################################################
Error executing command: could not load configuration xipki/ca-setup/cacert-none/ca-conf.json, error: IOException while sending message to the server: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Following are the command used to generate certs.  

 Can you pls share the commands you have used to generate certs in the above folder. We can use it to create certs with longer validity.
1.  Create private-key.pem
            openssl ecparam -genkey -name prime256v1 -noout -out private-key.pem
2. Create certificate in certificate.pem.
            openssl req -new -x509 -key private-key.pem -out certificate.pem -days 900000 -subj "/C=PL/ST=Silesia/L=Katowice/O=MyOrganization/CN=CommonName"
3.  Combine private key and certificate into a new certificate-private.pem file. Open up command line, move to the folder where your files exist.
           cat private-key.pem certificate.pem > certificate-private.pem
4. Create p12 certificate from certificate-private.pem.
   openssl pkcs12 -export -inkey  private-key.pem  -in certificate-private.pem -out certificate-private.p12
5. The files generated are used to over-ride keycerts/tlskey. The same cert.pem,key.pem and p12 are used to replace all the files - clients,server, cacert folders

Added the certificate into keystore using the following command

keytool -import -cacerts -file /home/causer-temp/xipki-cli-5.3.15/xipki/keycerts/tlskeys/client/tls-client-cert.der -alias xipkicerts

**Comment by subyphilip** [comment]
Hi Lijun,
Can you please help here as we are blocked. Original description above is updated with our findings.

a. We are looking for a procedure to replace them with longer validity certs. How the certificate can be created with longer validity and used? 
b. Is there a way to remove this tlskeys alltogether. Which all files need to be modified for that.
c. Can the new release from Xipki include longer validity tlskeys certificates ~ 100 years to be safe?

**Comment by xipki** [comment]
The keys delivered in the binaries are only for demo purpose, they MUST be replaced by your own.

**Comment by subyphilip** [comment]
We could replace the certificates in  keycerts/tlskeys/client2 with  certificates in keycerts/tlskeys/client. Now there is validity until 2038. We still couldn't replace with our own certificates. Will try it again.
