### ISSUE TITLE
Unable to extend the validity of CA certificate

### ISSUE THREAD

**Issue by subyphilip** [xipki/xipki#260]
As mentioned in https://github.com/xipki/xipki/issues/229, unable to increase the validity of CA certificate even after following the suggested steps in that ticket. Steps suggested in the ticket are mentioned below

Increase the maximal validity of the certificates issued by the given CA by modifying the template.ca-conf.json:

"maxValidity":"20y",  (Default is 10y)

After CA configuration, I see that CA table in the mariadb is modified to 20y, but still the CA certificate has the validity as 10y the default value
/certs $ openssl x509 -in cacert.pem -noout -text
Certificate:
        Validity
            Not Before: Jul  6 08:15:23 2022 GMT
            Not After : Jul  6 08:15:23 2032 GMT

/certs $ openssl x509 -in cert.pem -noout -text
Certificate:
        Validity
            Not Before: Jul  6 08:55:11 2022 GMT
            Not After : Jul  6 08:15:23 2032 GMT

karaf@root()> ca:ca-info ux1                                                                             
started: true
aliases: {ca}
id: 1
name: zts1
status: active
max. validity: 20y

MariaDB [ca]> 
MariaDB [ca]> select MAX_VALIDITY from CA;
+--------------+
| MAX_VALIDITY |
+--------------+
| 20y          |
+--------------+

Tried modifying the CA configuration using CLI  
ca:ca-up
, even that command is increasing the validity in the database and CLI, but not modifying the CAcert and issued certificates.

**Comment by xipki** [comment]
The validity in the certificates issued before can not be modified. The modification of the configuration has only effect on the new certificates.
