### ISSUE TITLE
Queries about NEW Xipki Version: 6.0.0

### ISSUE THREAD

**Issue by manonver121** [xipki/xipki#269]
HI
We are using xipki-6.0.0 and seeing that many scripts are missing in this new version. Like: xipki-cli-6.0.0/xipki/ doesn't have these directories: ca-setup and cmpclient.

Have you added any other files instead of those files which were contained by above mentioned directories ?

**Comment by xipki** [comment]
In version 6.0.0, a new binary (xipki-mgmt-cli) is introduced. All CA management functions can be found in this new binary. The cmp-client component is still in the binary xipki-cli ( the configuration is ./xipki/etc/cmp-client.json, and an example script is under ./xipki/client-script/cmp-client.script).

**Comment by manonver121** [comment]
Hi

Thanks for this information.
Wanted to ask you about some more queries:
1. where can i get the configuration which was present in this file xipki-cli-5.3.15/xipki/ca-setup/cacert-none/template.ca-conf.json
2. where can i check configuration of this file: xipki-cli-5.3.15/xipki/ca-setup/certprofile/certprofile-tls.json

As in every upgrade we make some manual changes and with this latest version we are not able to make those changes.
Could you please help me with this ?

Thanks

**Comment by manonver121** [comment]
Hi 

We are seeing this error:

2022.12.20-10:35:18.742 main ERROR: LogUtil.error() (org.xipki.ca.server.mgmt.CaManagerImpl.startCaSystem0 663) error initializing CA system, org.xipki.ca.api.mgmt.CaMgmtException: DB version < 7 is not supported: 6
2022.12.20-10:35:18.742 main ERROR: CaManagerImpl.startCaSystem() could not start CA system
2022.12.20-10:35:18.746 main INFO: CaServletFilter.init() ca.noRA: false
2022.12.20-10:35:18.838 main INFO: CaServletFilter.init() remote management is enabled

and DS version which we have:

MariaDB [(none)]> SELECT VERSION;
ERROR 1054 (42S22): Unknown column 'VERSION' in 'field list'
MariaDB [(none)]> SELECT VERSION();
+--------------------+
| VERSION()          |
+--------------------+
| 10.6.9-MariaDB-log |
+--------------------+
1 row in set (0.000 sec)

Could you please help us resolve this issue.
Thanks

**Comment by manonver121** [comment]
Hi

Could you please give an update on this issue ?

Thanks

**Comment by xipki** [comment]
- The file template.ca-conf.json is in the folders xipki/ca-setup/cacert-none and xipki/ca-setup/cacert-present.
- The file certprofile.json is in the folder xipki/ca-setup/certprofile.
- This version is not the version of the database software. It is the XiPKI's proprietary syntax version of tables. It is specified in the table DBSCHEMA, you will find a record with NAME='VERSION' and VALUE='<version>'. XiPKI v6.0.0 supports only version 7+. If you use the existing database from XiPKI v5.3.x (vesion 6), you need to export the import the database content with the commands (see Section 'Database Commands' under https://github.com/xipki/xipki/blob/master/commands.md) provided in the binary xipki-mgmt-cli.

**Comment by manonver121** [comment]
Hi 
we are seeing this error in logs :
Could you please help us to resolve this error:
2023.01.13-07:34:54.233 main INFO: CaManagerImpl.init() associate datasource ca to the file etc/ca/database/ca-db.properties
2023.01.13-07:34:54.305 main INFO: HikariDataSource.<init>() HikariPool-1 - Starting...
2023.01.13-07:34:54.421 main INFO: HikariDataSource.<init>() HikariPool-1 - Start completed.
2023.01.13-07:34:54.435 main INFO: CaManagerImpl.loadDatasource() loaded datasource.ca
2023.01.13-07:34:54.506 main ERROR: LogUtil.error() (org.xipki.ca.server.mgmt.CaManagerImpl.startCaSystem0 663) error initializing CA system, org.xipki.ca.api.mgmt.CaMgmtException: BadSqlGrammar - SQL [SELECT NAME,VALUE2 FROM DBSCHEMA]; (conn=2635) Table 'ca.DBSCHEMA' doesn't exist
2023.01.13-07:34:54.507 main ERROR: CaManagerImpl.startCaSystem() could not start CA system

**Comment by xipki** [comment]
It seems that the database is not initialized. Please follow https://github.com/xipki/xipki/blob/v6.0.0/assemblies/xipki-ca/README.md (in your case Steps 4 to 6).

**Comment by xipki** [comment]
This issue seems to be inactive. Please re-open it if needed.
