### ISSUE TITLE
Build fails with being unable to resolve dependency org.xipki:jpkcs11wrapper

### ISSUE THREAD

**Issue by mputz86** [xipki/xipki#270]
The currently latest master commit does not build (for me).

The first error was that the Apache snapshot repository must have a `https://` URL from Maven 3.8.1 onwards (see [here](https://stackoverflow.com/questions/69400875/maven-stuck-downloading-maven-default-http-blocker)); in `pom.xml`.

The next issue is that `org.xipki:jpkcs111wrapper` is missing. Since it is not part of the Apache snapshot repo and no maven repo which I have checked, I dont know how the build actually "should" get the dependency.

Any hints what I am doing wrong? :)

Maven version: 3.8.6
Java version: 11.0.15
Used commit of xipki: `66008f9a7`

The full error:
![image](https://user-images.githubusercontent.com/3016731/211687284-e8be881b-b168-4a8d-b8d7-568910956c76.png)

**Comment by mputz86** [comment]
Blocks the PR https://github.com/xipki/xipki/pull/271 since I cannot verify completly that all is good.

**Comment by xipki** [comment]
Sorry, I forgot to deploy the jpkcs11wrapper. Now it should work.
