### ISSUE TITLE
Would it be possible to extend the 10days validity period of the crl so they would not expire? 

### ISSUE THREAD

**Issue by manonver121** [xipki/xipki#274]
Hi
We are using xipki 5.3.15. 
Would it be possible to extend the 10 days validity period of the crl so they would not expire? If yes, please share us the procedure. 
Could you please let us know why crl has validity of 10 days ?

Thanks

**Comment by xipki** [comment]
The validity, together with other properties, of CRL is controlled by the CRL-control. You will get the configuration via the karaf command (in xipki-cli) 'ca:ca-info --verbose'. With command ca:ca-up you can modify the CRL-control.

**Comment by sanjiths** [comment]
Kindly request to share an example command with correct options to extend the crl validity!
we tried to execute the following command but the configured CA got removed from the mariaDB.

```
karaf@root()> ca:ca-info
successful CAs:
  **nc1230zts23drop3 (aliases [ca])** // "nc1230zts23drop3 "CA was configured
failed CAs:
  -
inactive CAs:

karaf@root()> ca:ca-up --crl-control --name nc1230zts23drop3
Error executing command ca:ca-up: too many arguments specified
karaf@root()> ca:ca-up --name nc1230zts23drop3
Error executing command: could not update CA nc1230zts23drop3, error: server returns 404
karaf@root()> ca:ca-up --name nc1230zts23drop3 --crl-control
Error executing command ca:ca-up: missing value for option --crl-control
karaf@root()> ca:ca-up --crl-control 10 --name nc1230zts23drop3
updated CA nc1230zts23drop3

karaf@root()> ca:ca-info
**successful CAs:**  //configured CA got removed
  -
failed CAs:
  -
inactive CAs:
  -

```

We could not find the options to be provided in the command to extend crl validity.So, kindly request for your support.

Thank you very much,
Sanjith S

**Comment by xipki** [comment]
Please share the output of `ca:ca-info --verbose nc1230zts23drop3`.

**Comment by sanjiths** [comment]
Thank you very much for your prompt response! We will try this procedure and provide an update!

**Comment by xipki** [comment]
I close this issue due to inactivity.  Please re-open it if needed.
