### ISSUE TITLE
Unable to initialize database in xipki-6.1.0v 

### ISSUE THREAD

**Issue by manonver121** [xipki/xipki#276]
We are facing errors while initializing database using mgmt-cli in xipki-6.1.0v
Database used for xipki backend Storage: mariadb
mariadb version: 10.6.11v 
Command run to initialize database:
1) Exec: /home/causer/xipki-mgmt-cli-6.1.0/bin/karaf
2)In karaf prompt, we ran the below command:

```
karaf@root()> ca:sql --db-conf /opt/tomcat/xipki/etc/ca/database/ca-db.properties /home/causer/xipki-mgmt-cli-6.1.0/xipki/sql/liquibase/ca-init.xml

Start executing script /home/causer/xipki-mgmt-cli-6.1.0/xipki/sql/liquibase/ca-init.xml
[ WARN] (pipe-ca:sql --db-conf /opt/tomcat/xipki/etc/ca/database/ca-db.properties /home/causer/xipki-mgmt-cli-6.1.0/xipki/sql/liquibase/ca-init.xml) Error: 1064-42000: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
Maximal column s...' at line 1
Error executing '<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
Maximal column size: 4k

```
Attaching the ca-db.properties with mariadb servicename, user credentials configured. The same ca-db.properties file is working fine with xipki-5.3.15v

We have done no changes to the "xipki-mgmt-cli-6.1.0/xipki/sql/liquibase/ca-init.xml" file. Also tried to initialize database using the following files provided in xipki-mgmtcli-6.1.0 package:

./xipki/sql/liquibase/ca-init-v4.xml
./xipki/sql/liquibase/ca-init-v5.xml
./xipki/sql/liquibase/ca-init-v6.xml

 

Kindly request for your support.

**Comment by xipki** [comment]
Please use `ca:sql --db-conf /opt/tomcat/xipki/etc/ca/database/ca-db.properties /home/causer/xipki-mgmt-cli-6.1.0/xipki/sql/ca-init.sql insstead`.

**Comment by xipki** [comment]
I close this issue due to inactivity.  Please re-open it if needed.
