### ISSUE TITLE
SdkClient.cacerts() only returns cacert

### ISSUE THREAD

**Issue by hargut** [xipki/xipki#277]
Hello Lijun Liao,

during some EST tests it was noticed that the /cacert**s** endpoint within the ESTResponder does only serve the certificate and not the full chain. As per the [EST RFC](https://www.rfc-editor.org/rfc/rfc7030#section-4.1) the full chain must be served on this endpoint.

Looking into the details I've gained the impression that there might be an issue within the "SDKClient.cacert**s**(String ca)" method. The send call issues a "CMD_cacert" command instead of a "CMD_cacert**s**". The SDKResponder will only return the cert on the "CMD_cacert" endpoint.

As I'm not sure if changing the command would have other side effects that I'm not aware of I've created the ticket instead of a PR.

https://github.com/xipki/xipki/blob/ddd335d854bb12da053a439713c941441669c6b7/ca-gateway/est-gateway/src/main/java/org/xipki/ca/gateway/est/EstResponder.java#L253-L257
https://github.com/xipki/xipki/blob/ddd335d854bb12da053a439713c941441669c6b7/ca-sdk/src/main/java/org/xipki/ca/sdk/SdkClient.java#L88-L92
https://github.com/xipki/xipki/blob/ddd335d854bb12da053a439713c941441669c6b7/ca-server/src/main/java/org/xipki/ca/server/SdkResponder.java#L194-L215

Many thanks for your consideration.

Best regards,
Harald

**Comment by xipki** [comment]
Hi Harald,
thank you for the bug report and code analysis. Yes you are right. Fixed this bug in the commit 371b72c.

**Comment by hargut** [comment]
Hi Lijun,

I've tested the change and the EST `/cacerts` endpoint works now as expected.
Many thanks for the fast fix and your work on xipki. :+1: 

Have a great weekend.

Kind regards,
Harald

**Comment by xipki** [comment]
HI Harald,

if you use your own code to parse the EST response, please consider the XiPKI-extended  commands `ucacerts`, `ucacert`, `ucrl`, `ucacerts`, `usimpleenroll`, `usimplereenroll`, and `userverkeygen` as specified in https://github.com/xipki/xipki/blob/master/ca-gateway/est-gateway/src/main/java/org/xipki/ca/gateway/est/EstResponder.java#L106

**Comment by hargut** [comment]
Hi Lijun,

thank you for the hint with the custom `u` endpoints. I have already seen the `ucacert` endpoint.
Currently the EST standard endpoints are being used. I'll keep the additional endpoints in mind.

Best regards,
Harald
