### ISSUE TITLE
Configure TLS listerner port to listen only on localHost(127.0.0.1)

### ISSUE THREAD

**Issue by sanjiths** [xipki/xipki#288]
We have configured the TLS listerner port to listen only on localHost(127.0.0.1) in the tomcat/conf/server.xml as below:
<Connector port="8181" protocol="HTTP/1.1"
               address="127.0.0.1"
               connectionTimeout="20000"
               redirectPort="8443" />

But after configuring CA, 8443 is listening on all addresses.
/Envoy $  netstat -lapn|grep 8443
tcp        0      0 :::8443                 :::*                    LISTEN      -
/Envoy $  netstat -lapn|grep 8181
tcp        0      0 ::ffff:127.0.0.1:8181   :::*                    LISTEN      -

Could you pls tell me how to configure this port to make it listen only on localHost?

**Comment by xipki** [comment]
Sorry, I am not an expert in this area, please ask this in the tomcat community.

**Comment by ralienpp** [comment]
@sanjiths, it would help if you posted your configuration file here.

Also, just by looking at the output you provided - you can see that port 8443 is open on al interfaces, but are you sure it is the CA that does this, rather than some other process?

**Comment by xipki** [comment]
Close this issue due to inactivity. Please re-open if needed.
