### ISSUE TITLE
Unable to access Karaf tool

### ISSUE THREAD

**Issue by aameen8080** [xipki/xipki#292]
Xipki Version- 5.3.15
Hi, we are unable to access karaf tool , while accessing the tool it got stuck , 
![image](https://github.com/xipki/xipki/assets/69054448/c27e4ca5-e848-4db5-8726-32c07159f130)

We have tried accessing it number of times , even tried restarting tomcat , still its stuck and a large number of exceptions we can see in the karaf logs. Please find the tomcat and karaf logs attached below. Can you please help in checking this issue?
Karaf logs:-
[karaf.log](https://github.com/xipki/xipki/files/12289369/karaf.log)
Tomcat logs:- 
[tomcat.zip](https://github.com/xipki/xipki/files/12289382/tomcat.zip)

**Comment by xipki** [comment]
Please do a new unpack of the karaf tool,
