### ISSUE TITLE
est-gw: audit id ordering issue

### ISSUE THREAD

**Issue by hargut** [xipki/xipki#294]
Hello Lijun Liao,

on xipki 6.1 we have seen issues within the auditdb (mac database) related to est-gw and audit ids.

An example problem looked like this within the DB:
| shard_id | id   | time                    | level | event_type | previous_id | message                                                                                                                        | tag                                                              |
|----------|------|-------------------------|-------|------------|-------------|--------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------|
| 0        | 1675 | 2023.08.28-13:07:31.073 | ERROR | 1          | 1674        | est-gw; status: FAILED  duration: 55    message: invalid path /security.txt                                                    | v1:1:xipki_audit_db:sp4SBfiw9HLJAE8b4AANxVdceTbeo5F2gdAFUQhs4x4= |
| 0        | 1675 | 2023.08.28-09:05:59.871 | INFO  | 2          | 1674        | CA-SYSTEM START 2023/08/28 09:05:59 SUCCESSFUL 172.20.1.124 CORE                                                               | v1:1:xipki_audit_db:EEa3PXgsXwSCG2+VyZ2m3ornlJvimnbDLoU2kZ4A2Ro= |
| 0        | 1674 | 2023.08.27-01:56:16.830 | INFO  | 2          | 1673        | CA-SYSTEM START 2023/08/27 01:56:16 SUCCESSFUL 172.20.1.124 CORE                                                               | v1:1:xipki_audit_db:KHBwC6kdNMd7IqBJtI3oVa9ETkzBScOd+KGLXp1EmAY= |

This lead to a startup error:
```
30-Aug-2023 09:07:31.180 SEVERE [main] org.apache.catalina.core.StandardContext.filterStart Exception starting filter [ca-filter]
	org.xipki.audit.AuditServiceRuntimeException: tag in integrityText does not match the audit entry.
		at org.xipki.audit.Audits.init(Audits.java:123)
		at org.xipki.ca.servlet.CaServletFilter.init(CaServletFilter.java:107)
		at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:262)
```
The ORDER by `id` was returning the entry for `CA-SYSTEM START`, ORDER by `time` would return the `est-gw: status: FAILED`.

Digging a bit further into the error scenario the following could be found:
- after a startup of xipki an error on the est-gw ends up with wrong ids in the audit db
- it looks like the audit ids on `est-gw` are initialized correctly but not updated afterwards

| shard_id | id   | time                    | level | event_type | previous_id | message                                                                                                                                                        | tag                                                              |
|----------|------|-------------------------|-------|------------|-------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------|
| 0        | 1679 | 2023.08.30-10:49:53.657 | INFO  | 2          | 1678        | CA-SYSTEM START 2023/08/30 10:49:53 SUCCESSFUL 172.20.1.26 CORE                                                                                                | v1:1:xipki_audit_db:fSBomprdzM9sUa/ATSY4CZNcPhfvJjER5Ow45IOaFAA= |
| 0        | 1676 | 2023.08.30-10:48:41.565 | ERROR | 1          | 1675        | est-gw; status: FAILED  duration: 3     message: invalid path /security.txt                                                                                    | v1:1:xipki_audit_db:u1j4lgqjwPOgTQCKKXjvVvB13K+/gkFsK1OsJFGubOg= |
| 0        | 1678 | 2023.08.30-10:44:14.717 | INFO  | 1          | 1677        | ca;     status: SUCCESSFUL      duration: 57    ca: myca1       event_type: gen_crl     crl_type: FULL_CRL      next_update: 20230909020000     crl_number: 25 | v1:1:xipki_audit_db:ZpT0rjWfi44l+j7SA9TOFQTAdrpJ5wOcskcWpg5/j0Q= |
| 0        | 1677 | 2023.08.30-10:44:14.710 | INFO  | 1          | 1676        | ca;     status: SUCCESSFUL      duration: 2     ca: myca1       event_type: cleanup_crl num: 0                                                                 | v1:1:xipki_audit_db:IGZwSiJGXpbNz8TNQ6K60iRNT9j4qVC8V/XaTkJLKkA= |
| 0        | 1676 | 2023.08.30-10:42:46.654 | INFO  | 2          | 1675        | CA-SYSTEM START 2023/08/30 10:42:46 SUCCESSFUL 172.20.1.25 CORE                                                                                                | v1:1:xipki_audit_db:x2UDAk/39PtiYpCoCEQjXkVRTkrLBId9tBypopQmNFE= |

Many thanks in advance for your consideration.

Kind regards,
Harald

**Comment by xipki** [comment]
It seems you have configured to use the same audit database for both the CA and EST-GW. Due to the performance issue, the logger will not check the up-to--date largest id in the database. Instead, each application manages its own id sequence and initialize it when the applications starts. That is the reason why you have two entries (one of CA, one of EST-GW) with the same id.re

You may 1) configure 1 audit DB for the CA, and 1 for the EST-GW, 2) or configure the `audit` with shard-id (via `shard-id` in `audit` -> `conf`) different than CA.

**Comment by hargut** [comment]
Thank you for the fast feedback. Indeed the configuration currently uses the same DB without a specific shared-id configuration.
Many thanks for your help in this matter. :+1:
