### ISSUE TITLE
ocsp.json, OCSP

### ISSUE THREAD

**Issue by WilliamM7** [xipki/xipki#296]
Do you have your own JSON-parser or why did you comment lines with `//`  when comments are not permitted in JSON?
In the README files you say to start tomcat with `start.sh` but the script is called `startup.sh` and you also say to navigate to` xipki-install` but there is no such folder except `xipki-setup`
My second question is. The README files say "copy `lib`, ... to `${CATALINA_HOME}`". Do you mean copy and append or copy and overwrite?
My last question is. Is it possible to start only the OSCP server, or should all three components CA Server, OCSP Responder and Protocol Gateway get installed? And how does the OCSP responder retrieve the revocation status of a certificate without a CRL as its (OCSPSore? did you mean OCSPStore?)?

For the CA part. I set up all needed things using the described steps but I still get an 404 server error

**Comment by xipki** [comment]
1. Most popular JSON parsers allows comments, e.g. the jackson used in this project.
2. I updated README to cover the tomcat related instructions. (see the commit 32b9117).
3. OCSP responder
  -  Works with the databases created by the XiPKI-CA and EJBCA, and the standard CRL file.
  - You may use your own OCSP store, see the `examples` folder.
4. CA
  - Please follow the setup instruction. Please upload the log files of CA.

**Comment by xipki** [comment]
I close this issue due to inactivity.
