### ISSUE TITLE
The assemblies artifacts were not pushed to central for 6.4.0

### ISSUE THREAD

**Issue by stustison** [xipki/xipki#300]
Building an image for the OCSP or anything else is much more difficult without the associated assemblies artifacts being pushed to central so they can be pulled down in another project. It means you have to clone and build them yourself locally as part of building the image, which causes a lot of unnecessary work since they've already been built for 6.4.0 anyways. I see 6.3.0 and previous releases have these artifacts. Is there any way you can just push up the artifacts for 6.4.0?

**Comment by xipki** [comment]
Which assembly binaries do you mean?

**Comment by stustison** [comment]
The maven artifacts under assemblies/ were never published, for example: https://central.sonatype.com/artifact/org.xipki.assembly/xipki-ocsp the latest version is 6.3.0 instead of 6.4.0. I was using those to build a Docker image. I just duplicated what those modules are doing as a workaround, but it is easier to just use the zip file that is produced.

**Comment by xipki** [comment]
The best way is to use the released zip file, e.g. `https://github.com/xipki/xipki/releases/download/v6.4.0/xipki-setup-6.4.0.zip.
