### ISSUE TITLE
could not remove user <>, error: remote management is not permitted to the client without valid certificate

### ISSUE THREAD

**Issue by sanjiths** [xipki/xipki#301]
xipki version: 5.3.15

We are facing below error while deleting a xipki user. Could you pls share any workaround to overcome this error
[karaf.log.txt](https://github.com/xipki/xipki/files/13188771/karaf.log.txt)
?

```
karaf@root()> ca:causer-rm --user t1hs05 --ca t1zh01
Do you want to remove user t1hs05 from CA t1zh01 (Yes/No)? yes
Error executing command: could not remove user t1hs05 from CA t1zh01, error: remote management is not permitted to the client without valid certificate
karaf@root()> ca:user-rm --name t1hs05
Do you want to remove user t1hs05 (Yes/No)? yes
Error executing command: could not remove user t1hs05, error: remote management is not permitted to the client without valid certificate
karaf@root()>
sh-4.2$
```

Errors in karaf logs:
```
2023-09-28T10:35:38,305 | WARN  | pipe-ca:causer-rm --user t1hs05 --ca t1zh01 | jline                             117 | 28 - org.jline - 3.21.0 | The Parser of class org.apache.karaf.shell.impl.console.ConsoleSessionImpl$$Lambda$638/0x000000010068d840 does not support the CompletingParsedLine interface. Completion with escaped or quoted words won't work correctly.
2023-09-28T10:35:38,941 | ERROR | Karaf local console user karaf | ShellUtil                         152 | 27 - org.apache.karaf.shell.core - 4.3.6 | Exception caught while executing command
org.xipki.shell.CmdFailure: could not remove user t1hs05 from CA t1zh01, error: remote management is not permitted to the client without valid certificate

```

**Comment by xipki** [comment]
The error mentioned above indicates the CA could not get the TLS client certificate is not among the certificates configured in the `remoteMgmt` block in the `ca.json` file.

**Comment by sanjiths** [comment]
Could you pls share command or procedure to add a certificate to the remote management?

**Comment by sanjiths** [comment]
There is a factory certificate from Xipki  [xipki-cli-5.3.15](https://bhgitlab.int.net.nokia.com/Zero_Touch_Core/ztc_certificate_authority/-/tree/master/deployment/dockerfiles/caserver/Dependancies/xipki-cli-5.3.15)/xipki/keycerts/tlskeys/client2/tls-client2-cert.der which is expiring on 7th Nov 2023. We have configured the CA using this certificate in ca.json as remoteMgmt certificate.  

Upon realizing that the certificate is about to expire, on an already configured CA, we have replaced tls-client2-cert.der with [xipki-cli-5.3.15](https://bhgitlab.int.net.nokia.com/Zero_Touch_Core/ztc_certificate_authority/-/tree/master/deployment/dockerfiles/caserver/Dependancies/xipki-cli-5.3.15)/xipki/keycerts/tlskeys/client/tls-client-cert.der which has validity until 2038 and restarted tomcat. 

But this certificate is not taking affect. We are not able to add or delete user. It gives the error “error: remote management is not permitted to the client without valid certificate”. Certificate issue is fine. 

 

Can you please suggest any workaround to recover from this issue, can we add the new certificate “tls-client-cert.der” into remote management list without reconfiguring the CA.  

We have deployed this CA in a production and clients have fetched certificates. We are looking for a solution without reconfiguring the CA, so that client certificates continue to remain valid.

**Comment by xipki** [comment]
Please make sure

**Comment by xipki** [comment]
Any update?

**Comment by xipki** [comment]
Close this issue due to inactivity.
