### ISSUE TITLE
Unable to import database to xipki:6.3.0 from 5.3.15

### ISSUE THREAD

**Issue by sanjiths** [xipki/xipki#303]
Hi @xipki ,as suggested on https://github.com/xipki/xipki/issues/269,
1) I installed xipki: 5.3.15v and exported the database using following command:

```
sh-4.4$ ./bin/karaf
karaf: JAVA_HOME not set; results may vary
Apache Karaf starting up. Press Enter to open the shell now...
100% [========================================================================]

Karaf started in 1s. Bundle stats: 18 active, 18 total
       _  __ _ ____  __ __ ____
      | |/ /(_) __ \/ //_//  _/
      |   // / /_/ / ,<   / /
     /   |/ / ____/ /| |_/ /
    /_/|_/_/_/   /_/ |_/___/

  XiPKI management-cli 6.3.0 buildNumber d16306e6 built at 2023-04-29-20:27:33

Hit '<tab>' for a list of available commands
and '[cmd] --help' for help on a specific command.
Hit '<ctrl-d>' or type 'logout' to shutdown Karaf.

karaf@root()> ca:export-ca --db-conf /opt/tomcat/xipki/etc/ca/database/ca-db.properties --out-dir /tmp/temp/
Please enter password of the ZIP file:*****
exporting CA configuration from database
    exporting table DBSCHEMA ... SUCCESSFUL
    exporting table SIGNER ... SUCCESSFUL
    exporting table REQUESTOR ... SUCCESSFUL
    exporting table PUBLISHER ... SUCCESSFUL
    exporting table CA ... SUCCESSFUL
    exporting table PROFILE ... SUCCESSFUL
    exporting table CAALIAS ... SUCCESSFUL
    exporting table CA_HAS_REQUESTOR ... SUCCESSFUL
    exporting table CA_HAS_PUBLISHER ... SUCCESSFUL
    exporting table CA_HAS_PROFILE ... SUCCESSFUL
 exported CA configuration from database
exporting CA certstore from database
exporting table CRL from ID 1
-----------------------------------------------------------------------
                        average   current      time      time    finish
          total     %     speed     speed     spent      left        at

              1  100%        10        10     00:00        --        --
-----------------------------------------------------------------------
 exported 1 entries from table CRL
exporting table CERT from ID 57285181817487360
-----------------------------------------------------------------------
                        average   current      time      time    finish
          total     %     speed     speed     spent      left        at

              8  100%     1,000     1,000     00:00        --        --
-----------------------------------------------------------------------
 exported 8 entries from table CERT
 exported CA certstore from database
Finished in 00:01

```

2)While importing the above database using following cmd from xipki-mgmt-cli-6.3.0, I am facing below err:
sh-4.4$ ls /tmp/temp/encrypted/main.zip
/tmp/temp/encrypted/main.zip

```
karaf@root()> ca:import-ca --db-conf /opt/tomcat/xipki/etc/ca/database/ca-db.properties --in-dir /tmp/temp/
Please enter password of the ZIP file:*****
importing CA configuration to database
    importing table DBSCHEMA ... SUCCESSFUL
    importing table SIGNER ... [ WARN] (pool-5-thread-1) Error: 1062-23000: Duplicate entry 'responder1' for key 'PRIMARY'
could not import SIGNER with NAME=responder1
FAILED
could not import CA configuration to database. message: DuplicateKey - SQL [INSERT INTO SIGNER (NAME,TYPE,CERT,CONF) VALUES(?,?,?,?)]; (conn=41) Duplicate entry 'responder1' for key 'PRIMARY'
Finished in 00:00
Error executing command: DuplicateKey - SQL [INSERT INTO SIGNER (NAME,TYPE,CERT,CONF) VALUES(?,?,?,?)]; (conn=41) Duplicate entry 'responder1' for key 'PRIMARY'

```
```
karaf@root()> ca:import-ca --db-conf /opt/tomcat/xipki/etc/ca/database/caconf-db.properties --in-dir /tmp/temp/
Please enter password of the ZIP file:*****
[ WARN] (pool-4-thread-1) Error: 1146-42S02: Table 'caconf.DBSCHEMA' doesn't exist
Finished in 00:00
Error executing command: BadSqlGrammar - SQL [SELECT NAME,VALUE2 FROM DBSCHEMA]; (conn=14) Table 'caconf.DBSCHEMA' doesn't exist
karaf@root()>

```

**Comment by sanjiths** [comment]
[Uploading ca-db.txt…]()

**Comment by sanjiths** [comment]
[Uploading caconf-db.txt…]()

**Comment by xipki** [comment]
You need to specify also --caconf-db-conf.

**Comment by sanjiths** [comment]
I have imported database with xipki-5.3.15v installled using following command from xipki-mgmtcli-6.3.0/karaf prompt:
```
ca:export-ca --out-dir output/dbexport/ca-v7 --password CHANGEIT \
  --db-conf ${CA_XIPKI_DIR}/etc/ca/database/ca-db.properties
```

"caconf" database has been created. While exporting the above database during xipki-6.3.0v installation, im facing following error:
```
karaf@root()> ca:import-ca --in-dir /tmp/ --password 12345 --db-conf /opt/tomcat/xipki/etc/ca/database/ca-db.properties --caconf-db-conf /opt/tomcat/xipki/etc/ca/database/caconf-db.properties
[ WARN] (pool-6-thread-1) Error: 1146-42S02: Table 'caconf.DBSCHEMA' doesn't exist
Finished in 00:00
Error executing command: BadSqlGrammar - SQL [SELECT NAME,VALUE2 FROM DBSCHEMA]; (conn=302) Table 'caconf.DBSCHEMA' doesn't exist

```

**Comment by sanjiths** [comment]
During xipki-6.3.0v installation, I have configured caconf database using the following command:
karaf@root()> ca:sql --db-conf /opt/tomcat/xipki/etc/ca/database/caconf-db.properties /home/causer/xipki-mgmt-cli-6.3.0/xipki/sql/caconf-init.mysql.sql
Do you want to execute the SQL script (Yes/No)? yes
Start executing script /home/causer/xipki-mgmt-cli-6.3.0/xipki/sql/caconf-init.mysql.sql
  End executing script /home/causer/xipki-mgmt-cli-6.3.0/xipki/sql/caconf-init.mysql.sql

Imported the database exported from "5.3.15" using command:
karaf@root()> ca:import-ca --in-dir /tmp/ --password 12345 --db-conf /opt/tomcat/xipki/etc/ca/database/ca-db.properties --caconf-db-conf /opt/tomcat/xipki/etc/ca/database/caconf-db.properties
importing CA configuration to database
    importing table DBSCHEMA ... SUCCESSFUL
    importing table SIGNER ... SUCCESSFUL
    importing table REQUESTOR ... SUCCESSFUL
    importing table PUBLISHER ... SUCCESSFUL
    importing table PROFILE ... SUCCESSFUL
    importing table CA ... SUCCESSFUL
    importing table CAALIAS ... SUCCESSFUL
    importing table CA_HAS_REQUESTOR ... SUCCESSFUL
    importing table CA_HAS_PUBLISHER ... SUCCESSFUL
    importing table CA_HAS_PROFILE ... SUCCESSFUL
    importing table KEYPAIR_GEN ... nothing to import
 imported CA configuration to database
importing CA certstore to database
importing entries to table CRL from ID 1
-----------------------------------------------------------------------
                        average   current      time      time    finish
          total     %     speed     speed     spent      left        at

[ WARN] (pool-4-thread-1) Error: 1054-42S22: Unknown column 'SHA1' in 'field list'

could not import entries from file /tmp//crls/crls_1-1.zip.
please continue with the option '--resume'
could not import CA certstore to database
Finished in 00:00
Error executing command: BadSqlGrammar - SQL [INSERT INTO CRL (ID,CA_ID,CRL_NO,THISUPDATE,NEXTUPDATE,DELTACRL,BASECRL_NO,CRL_SCOPE,SHA1,CRL) VALUES(?,?,?,?,?,?,?,?,?,?)]; (conn=450) Unknown column 'SHA1' in 'field list'

from ca.log:
sh-4.4$ tail -f ca.log
2023-11-15 07:14:04,098 INFO o.x.c.s.m.CaManagerImpl [main] ca.shardId: 0
2023-11-15 07:14:04,176 INFO c.z.h.HikariDataSource [main] HikariPool-1 - Starting...
2023-11-15 07:14:04,479 INFO c.z.h.HikariDataSource [main] HikariPool-1 - Start completed.
2023-11-15 07:14:04,489 INFO o.x.c.s.m.CaManagerImpl [main] loaded datasource.ca
2023-11-15 07:14:04,489 INFO o.x.c.s.m.CaManagerImpl [main] associate datasource ca to the file etc/ca/database/ca-db.properties
2023-11-15 07:14:04,490 INFO c.z.h.HikariDataSource [main] HikariPool-2 - Starting...
2023-11-15 07:14:04,582 INFO c.z.h.HikariDataSource [main] HikariPool-2 - Start completed.
2023-11-15 07:14:04,582 INFO o.x.c.s.m.CaManagerImpl [main] loaded datasource.caconf
2023-11-15 07:14:04,583 INFO o.x.c.s.m.CaManagerImpl [main] associate datasource caconf to the file etc/ca/database/caconf-db.properties
2023-11-15 07:14:04,595 INFO o.x.c.s.m.CaManagerImpl [main] **dbSchemaVersion: 8**
2023-11-15 07:14:04,672 INFO o.x.c.s.d.CaManagerQueryExecutor [main] added system event LOCK
2023-11-15 07:14:04,678 ERROR o.x.u.LogUtil [main] (org.xipki.ca.server.mgmt.CaManagerImpl.startCaSystem0 677) error initializing CA system, org.xipki.ca.api.mgmt.CaMgmtException: **dbSchemaVersion < 7 unsupported: 6**
2023-11-15 07:14:04,678 ERROR o.x.c.s.m.CaManagerImpl [main] could not start CA system
2023-11-15 07:14:04,681 INFO o.x.c.s.CaServletFilter [main] ca.noRA: false
2023-11-15 07:14:04,689 INFO o.x.c.s.CaServletFilter [main] remote management is enabled

Does this mean migration of data from dbschema version "6" to "8" is not possible?

**Comment by xipki** [comment]
You need to initialize the --db-conf and --caconf-db-conf use the SQL scripts of the **SAME** version.

**Comment by sanjiths** [comment]
I have initialized both --db-conf and --caconf-db-conf using the sql scripts from xipki-6.3.0v now:
```
karaf@root()>    ca:sql --db-conf /opt/tomcat/xipki/etc/ca/database/ca-db.properties /home/causer/xipki-mgmt-cli-6.3.0/xipki/sql/ca-init.sql
Do you want to execute the SQL script (Yes/No)? yes
Start executing script /home/causer/xipki-mgmt-cli-6.3.0/xipki/sql/ca-init.mysql.sql
[ WARN] (pipe-ca:sql --db-conf /opt/tomcat/xipki/etc/ca/database/ca-db.properties /home/causer/xipki-mgmt-cli-6.3.0/xipki/sql/ca-init.sql) Error: 1146-42S02: Table 'ca.CRL' doesn't exist
[ WARN] (pipe-ca:sql --db-conf /opt/tomcat/xipki/etc/ca/database/ca-db.properties /home/causer/xipki-mgmt-cli-6.3.0/xipki/sql/ca-init.sql) Error: 1146-42S02: Table 'ca.CERT' doesn't exist
[ WARN] (pipe-ca:sql --db-conf /opt/tomcat/xipki/etc/ca/database/ca-db.properties /home/causer/xipki-mgmt-cli-6.3.0/xipki/sql/ca-init.sql) Error: 1146-42S02: Table 'ca.CERT' doesn't exist
[ WARN] (pipe-ca:sql --db-conf /opt/tomcat/xipki/etc/ca/database/ca-db.properties /home/causer/xipki-mgmt-cli-6.3.0/xipki/sql/ca-init.sql) Error: 1146-42S02: Table 'ca.CERT' doesn't exist
  End executing script /home/causer/xipki-mgmt-cli-6.3.0/xipki/sql/ca-init.mysql.sql
karaf@root()> ca:sql --db-conf /opt/tomcat/xipki/etc/ca/database/ca-db.properties /home/causer/xipki-mgmt-cli-6.3.0/xipki/sql/ca-init.sql
Do you want to execute the SQL script (Yes/No)? yes
Start executing script /home/causer/xipki-mgmt-cli-6.3.0/xipki/sql/ca-init.mysql.sql
  End executing script /home/causer/xipki-mgmt-cli-6.3.0/xipki/sql/ca-init.mysql.sql
karaf@root()> ca:sql --db-conf /opt/tomcat/xipki/etc/ca/database/caconf-db.properties /home/causer/xipki-mgmt-cli-6.3.0/xipki/sql/caconf-init.mysql.sql
Do you want to execute the SQL script (Yes/No)? yes
Start executing script /home/causer/xipki-mgmt-cli-6.3.0/xipki/sql/caconf-init.mysql.sql
[ WARN] (pipe-ca:sql --db-conf /opt/tomcat/xipki/etc/ca/database/caconf-db.properties /home/causer/xipki-mgmt-cli-6.3.0/xipki/sql/caconf-init.mysql.sql) Error: 1146-42S02: Table 'caconf.CA' doesn't exist
[ WARN] (pipe-ca:sql --db-conf /opt/tomcat/xipki/etc/ca/database/caconf-db.properties /home/causer/xipki-mgmt-cli-6.3.0/xipki/sql/caconf-init.mysql.sql) Error: 1146-42S02: Table 'caconf.CAALIAS' doesn't exist
[ WARN] (pipe-ca:sql --db-conf /opt/tomcat/xipki/etc/ca/database/caconf-db.properties /home/causer/xipki-mgmt-cli-6.3.0/xipki/sql/caconf-init.mysql.sql) Error: 1146-42S02: Table 'caconf.CA_HAS_REQUESTOR' doesn't exist
[ WARN] (pipe-ca:sql --db-conf /opt/tomcat/xipki/etc/ca/database/caconf-db.properties /home/causer/xipki-mgmt-cli-6.3.0/xipki/sql/caconf-init.mysql.sql) Error: 1146-42S02: Table 'caconf.CA_HAS_REQUESTOR' doesn't exist
[ WARN] (pipe-ca:sql --db-conf /opt/tomcat/xipki/etc/ca/database/caconf-db.properties /home/causer/xipki-mgmt-cli-6.3.0/xipki/sql/caconf-init.mysql.sql) Error: 1146-42S02: Table 'caconf.CA_HAS_PUBLISHER' doesn't exist
[ WARN] (pipe-ca:sql --db-conf /opt/tomcat/xipki/etc/ca/database/caconf-db.properties /home/causer/xipki-mgmt-cli-6.3.0/xipki/sql/caconf-init.mysql.sql) Error: 1146-42S02: Table 'caconf.CA_HAS_PUBLISHER' doesn't exist
[ WARN] (pipe-ca:sql --db-conf /opt/tomcat/xipki/etc/ca/database/caconf-db.properties /home/causer/xipki-mgmt-cli-6.3.0/xipki/sql/caconf-init.mysql.sql) Error: 1146-42S02: Table 'caconf.CA_HAS_PROFILE' doesn't exist
[ WARN] (pipe-ca:sql --db-conf /opt/tomcat/xipki/etc/ca/database/caconf-db.properties /home/causer/xipki-mgmt-cli-6.3.0/xipki/sql/caconf-init.mysql.sql) Error: 1146-42S02: Table 'caconf.CA_HAS_PROFILE' doesn't exist
  End executing script /home/causer/xipki-mgmt-cli-6.3.0/xipki/sql/caconf-init.mysql.sql
karaf@root()> ca:sql --db-conf /opt/tomcat/xipki/etc/ca/database/caconf-db.properties /home/causer/xipki-mgmt-cli-6.3.0/xipki/sql/caconf-init.mysql.sql
Do you want to execute the SQL script (Yes/No)? yes
Start executing script /home/causer/xipki-mgmt-cli-6.3.0/xipki/sql/caconf-init.mysql.sql
  End executing script /home/causer/xipki-mgmt-cli-6.3.0/xipki/sql/caconf-init.mysql.sql
```

Still database import is failing:
```
karaf@root()> ca:import-ca --in-dir /tmp/temp/ --password 12345 --db-conf /opt/tomcat/xipki/etc/ca/database/ca-db.properties --caconf-db-conf /opt/tomcat/xipki/etc/ca/database/caconf-db.properties
importing CA configuration to database
    importing table DBSCHEMA ... SUCCESSFUL
    importing table SIGNER ... [ WARN] (pool-11-thread-1) Error: 1062-23000: Duplicate entry 'responder1' for key 'PRIMARY'
could not import SIGNER with NAME=responder1
FAILED
could not import CA configuration to database. message: DuplicateKey - SQL [INSERT INTO SIGNER (NAME,TYPE,CERT,CONF) VALUES(?,?,?,?)]; (conn=258) Duplicate entry 'responder1' for key 'PRIMARY'
Finished in 00:00
Error executing command: DuplicateKey - SQL [INSERT INTO SIGNER (NAME,TYPE,CERT,CONF) VALUES(?,?,?,?)]; (conn=258) Duplicate entry 'responder1' for key 'PRIMARY'
```

**Comment by sanjiths** [comment]
Attaching the file!
[Uploading main.zip…]()
password: 12345

**Comment by xipki** [comment]
main.zip is not attached.

**Comment by xipki** [comment]
To import the data to database:
1. Initialize both caconf-db and ca-db. 
2. Call the import-ca command, once failed, you need to reinitialize the databases.

**Comment by xipki** [comment]
Please try to use the latest beta version (6.5.0-SNAPSHOT), which can be downloaded from
https://oss.sonatype.org/content/repositories/snapshots/org/xipki/assembly/xipki-setup/

I have tested this version to export the database from version 5.3.15, and then import it to the database of version 6.5.0-SNAPSHOT.

**Comment by xipki** [comment]
I just released v6.5.0. Please try this version.

**Comment by sanjiths** [comment]
Export is working! Pls close the issue

**Comment by sanjiths** [comment]
Export is working! Pls close the issue

Thanks for your support!
