### ISSUE TITLE
Error while changing ca with new masterpassword. v6.3.0

### ISSUE THREAD

**Issue by heiy2018** [xipki/xipki#305]
When I change CA with a signer conf created  by a new masterpassword, the xipki server could not decrypt the password.
If there is a way to clear xipki server memory of master password before I change CA?

**Comment by heiy2018** [comment]
I user my self-made callback function to send my new master password to xipki server, but it seems to be unused. 
Though I send a signerconf created by the new masterpassword, but xipki server is using the old masterpassword.

**Comment by xipki** [comment]
Is is possible to use XiPKI v6..5.0? In this version I simplified the configuration of password.

**Comment by heiy2018** [comment]
> Is is possible to use XiPKI v6.5.0? In this version I simplified the configuration of password.

Thank you for your answer. I will try to use v6.5.0 later.

**Comment by heiy2018** [comment]
Issue done.
