### ISSUE TITLE
v6.4.0: Exception in ca-server SdkResponder while updating an existing certificate

### ISSUE THREAD

**Issue by MartenLeckebusch-DB** [xipki/xipki#307]
I am using xipki in the v6.4.0 version, running an adjusted cmp gateway and ca server in apache tomcat.
Trying to update a certificate using xi:cmp-update-p12 in the karaf xipki cli results in an exception in the ca server.

The SdkResponder.enroll() method tries to create a X500Name out of the old certificate using `X500Name issuer = X500Name.getInstance(ocIsn.getIssuer());` resulting in the following exception:

```
java.lang.IllegalArgumentException: unknown object in getInstance: org.xipki.ca.sdk.X500NameType
	at org.bouncycastle.asn1.ASN1Sequence.getInstance(ASN1Sequence.java:105) ~[bcprov-jdk18on-1.76.jar:1.76.0.0]
	at org.bouncycastle.asn1.x500.X500Name.getInstance(Unknown Source) ~[bcprov-jdk18on-1.76.jar:1.76.0.0]
	at org.xipki.ca.server.SdkResponder.enroll(SdkResponder.java:395) ~[ca-server-6.4.0.jar:?]
        ...
```

I belive that the line should instead be: `X500Name issuer = ocIsn.getIssuer().toX500Name();`
Same goes for line 404:
` X500Name oldSubject = X500Name.getInstance(ocSubject.getSubject());` 
-> 
` X500Name oldSubject = ocSubject.getSubject().toX500Name();`

I have not tried this with newer xipki versions, but I would assume that the error persists.

Kind Regards!

**Comment by xipki** [comment]
Thanks. Fixed in bc35a96.
