### ISSUE TITLE
do you have an example of ocsp client call server

### ISSUE THREAD

**Issue by goldgreatscode** [xipki/xipki#309]
in this project ,i can not find this ,the code is too difficult

**Comment by xipki** [comment]
Do you mean the Java code or the openssl command?

**Comment by normasw98** [comment]
README.md in xipki-ocsp :

```
You can use the openssl command to check whether the OCSP server answers as expected: openssl ocsp -VAfile <PEM encoded OCSP signer certificate> -issuer <PEM encoded CA certificate> -url <URL> --serial <hex serial number>

e.g. openssl ocsp -VAfile ocsp-signer.pem -issuer ca.pem -url http://localhost:8080/ocsp/ -serial 0x123456789abc
```

Xi CLI command :
`ocsp-status --issuer output/test/cacert.der --cert output/test/rsa-p12.der`

result :
```
response is equipped with valid signature
produced at Fri Jan 05 11:31:11 KST 2024
issuer matched: true
serialNumber: 0x6f8e4e5803cce622855d58001313cc1afe229971
Certificate status: revoked, reason = keyCompromise, revocationTime = Thu Jan 04 16:28:01 KST 2024
```

openssl command :
```
openssl ocsp -VAfile /home/keycerts/ocsp1.p12 -issuer cacert.der -cert rsa-p12.der -url http://localhost:8080/ocsp/
Enter pass phrase for PKCS12 import pass phrase: *********
```

result :
```
Response verify OK
rsa-p12.der: revoked
        This Update: Jan  5 02:29:17 2024 GMT
        Next Update: Jan  6 02:29:17 2024 GMT
        Reason: keyCompromise
        Revocation Time: Jan  4 07:28:01 2024 GMT
```

**Comment by goldgreatscode** [comment]
Thank you very much

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: normasw98 ***@***.***>
发送时间: Friday, January 26, 2024 8:21:18 AM
收件人: xipki/xipki ***@***.***>
抄送: goldgreatscode ***@***.***>; Author ***@***.***>
主题: Re: [xipki/xipki] do you have an example of ocsp client call server (Issue #309)


README.md in xipki-ocsp :

You can use the openssl command to check whether the OCSP server answers as expected: openssl ocsp -VAfile <PEM encoded OCSP signer certificate> -issuer <PEM encoded CA certificate> -url <URL> --serial <hex serial number>

e.g. openssl ocsp -VAfile ocsp-signer.pem -issuer ca.pem -url http://localhost:8080/ocsp/ -serial 0x123456789abc


Xi CLI command :
ocsp-status --issuer output/test/cacert.der --cert output/test/rsa-p12.der

result :

response is equipped with valid signature
produced at Fri Jan 05 11:31:11 KST 2024
issuer matched: true
serialNumber: 0x6f8e4e5803cce622855d58001313cc1afe229971
Certificate status: revoked, reason = keyCompromise, revocationTime = Thu Jan 04 16:28:01 KST 2024


openssl command :

openssl ocsp -VAfile /home/keycerts/ocsp1.p12 -issuer cacert.der -cert rsa-p12.der -url http://localhost:8080/ocsp/
Enter pass phrase for PKCS12 import pass phrase: *********


result :

Response verify OK
rsa-p12.der: revoked
        This Update: Jan  5 02:29:17 2024 GMT
        Next Update: Jan  6 02:29:17 2024 GMT
        Reason: keyCompromise
        Revocation Time: Jan  4 07:28:01 2024 GMT


―

**Comment by xipki** [comment]
It seems the problem has been solved.
