### ISSUE TITLE
Considerations on update and renewal in CMP

### ISSUE THREAD

**Issue by normasw98** [xipki/xipki#310]
![image](https://github.com/xipki/xipki/assets/117900193/c0274ef4-940e-42c9-a405-760e398420fe)

- Karaf 6.5.2 includes the CMP command.
- Karaf 6.5.3 does not have the CMP command.
- Therefore, tests were conducted with Karaf 6.5.2 and XiPKI 6.5.3 (CA, Gateway, OCSP).
- After generating a certificate through cmp-client.script, the result when executing cmp-update-p12 is as follows.
```
command:
cmp-update-p12 --ca "myca" \
  --p12 output/cmp-20240126-102150/cmp-csr-tls.p12 \
  --password CHANGEIT \
  --oldcert output/cmp-20240126-102150/cmp-csr-tls.der \
  --out cmp-csr-tls-update.der \
  --signer-p12 xipki/keycerts/cmp-client.p12 \
  --signer-password 1234 \
  --req-out req.log --resp-out res.log


1. input : X KeyPair P12 file(cmp-csr-tls.p12), X Certificate(cmp-csr-tls.der)
2. request message
3. response message : Y Certificate + (Encrypted Y PrivateKey)
4. output : Y Certificate(cmp-csr-tls-update.der)
```
![image](https://github.com/xipki/xipki/assets/117900193/148c6f27-dc2b-4be3-a1d8-54d0c6291610)

- The public key of the input certificate differs from the public key of the certificate that was output.
- The user cannot obtain the private key for the updated certificate.

- Even if the above scenario works correctly, I cannot understand the cmp-update-p12 method.

- cmp-enroll-P12
    - The server issues a certificate using the already created key pair (P12) as input.
- cmp-enroll-serverkeygen
    - The server generates a key pair and issues a certificate.
- cmp-update-P12
    - Currently: The server issues a new key pair and certificate using the existing certificate and key pair (P12) as input.
    - Proposed change: The server issues a certificate using the existing certificate and key pair (P12) as input while maintaining the existing key pair.
        
        > **Shouldn't it operate this way?**
        > 
- cmp-update-serverkeygen
    - The server generates a key pair and issues a certificate.
    
- cmp-update-p12 and cmp-update-serverkeygen must consider the requirements below.
    - RFC4210 defines the following:

> in RFC4210
> 
> 3.1.3. PKI Management Operations
> 
> ...
> 
> **key pair update**: Every key pair needs to be updated regularly (i.e., replaced with a new key pair), and a new certificate needs to be issued.
> 
> **certificate update**: As certificates expire, they may be "refreshed" if nothing relevant in the environment has changed.
> 
> ...
> 
> 5.3.5. Key Update Request Content
> 
> For key update requests the CertReqMessages syntax is used. Typically, SubjectPublicKeyInfo, KeyId, and Validity are the template fields that may be supplied for each key to be updated (see the profiles defined in [RFCBBBB] Section 4.1.3 and Appendix C.6 for further information). This message is intended to be used to request updates to existing (non-revoked and non-expired) certificates (therefore, it is sometimes referred to as a "Certificate Update" operation). ***An update is a replacement certificate containing either a new subject public key or the current subject public key*** (although the latter practice may not be appropriate for some environments).
> 
> 6.9. Key Update
> 
> When a key pair is due to expire, the relevant end entity MAY request a key update***that is, it MAY request that the CA issue a new certificate for a new key pair (or, in certain circumstances, a new certificate for the same key pair)*** The request is made using a key update request (kur) message (referred to, in some environments, as a "Certificate Update" operation). If the end entity already possesses a signing key pair (with a corresponding verification certificate), then this message will typically be protected by the entity's digital signature. The CA returns the new certificate (if the request is successful) in a key update response (kup) message, which is syntactically identical to a CertRepMessage.

The diagram below helps to understand the differences between Update and Renewal:

![image](https://github.com/xipki/xipki/assets/117900193/bff4743a-8572-45c5-9796-604612e6c101)

- I drew this carefully myself for you and anyone else who may be viewing this : )
- As a PKI expert, you will be able to immediately understand this diagram.
- Update (Key Update) generates a new key pair and certificate.
- Renewal (Certificate Update) maintains the key pair and only generates a new certificate.
- I would like to hear your thoughts on the above matters.
    - Do you intend to preserve the existing protocol?
    - Are you considering implementing the suggested key update and certificate update functionalities?
    - Or perhaps you have a different approach in mind?

**Comment by xipki** [comment]
Hi, thanks for the detailed comment. As you may know, I use my spare time to maintain this project (for free). I will come back to you in the next days when I find time.

**Comment by xipki** [comment]
> Karaf 6.5.2 includes the CMP command.
> Karaf 6.5.3 does not have the CMP command.
Karaf 6.5.3 does provide the CMP commands. You need to call the `./prepare.sh`before starting `xipki-cli` at the first time.
Can you upload the log file `data/log/karaf.log` of `xipki-cli`.

**Comment by xipki** [comment]
And to your figure and description above:
 - The `renewal`and `update` processes in you figure above are correct, however, CMP does not provide explict APIs for both cases. They share the same API. So the best is even you do the `update`, also includes the public key in the request.
 - On the right of you figure, the computation of `Hash` is only for Hash-then-Sign signatures, e.g. RSA and ECDSA. But not for EdDSA. And if the `E`-Box is for Encryption, it does only to some signature algorithms, e.g. RSA, but not to ECDSA, EDDSA and DSA.

**Comment by normasw98** [comment]
I'd like to review the information you provided right away, but it seems difficult to do so immediately due to other tasks. I will examine it as soon as possible and get back to you with my feedback. Thank you

**Comment by normasw98** [comment]
Thank you for your reply.
I confirmed that the problem was resolved.
