### ISSUE TITLE
In xipki-6.5.1, cert does not get generated with SAN configuration

### ISSUE THREAD

**Issue by sanjiths** [xipki/xipki#311]
I created csr and generated cert using below commands:

csr command:
`openssl req -new -sha256 -key key.pem -outform der -out test.csr -subj "/CN=abc.com/O=abc/C=IN" -addext 'subjectAltName=DNS:abc.svc.cluster.local'`

csr has the configured SAN:
```
 Attributes:
            Requested Extensions:
                X509v3 Subject Alternative Name:
                    DNS:abc.svc.cluster.local
```

cert command:
`curl --insecure --user user1:password1 --header "Content-Type: application/pkcs10" --data-binary @test.csr --output cert.der "${CA_URL}/enroll-cert?profile=tls"`

Generated cert does not have SAN configuration:
`X509v3 Subject Alternative Name:`

**Comment by xipki** [comment]
I can not reproduce it in the latest version 6.5.4. Please upload the CSR file and the certprofile file for `tls` (export it using the commapd `ca:profile-export`, I will then test it in the v6.5.1.

**Comment by sanjiths** [comment]
I have attached a tar file containing test.csr & tls-profile.
[csr.tgz](https://github.com/xipki/xipki/files/14151896/csr.tgz)

**Comment by xipki** [comment]
I can repoduce the error with provided certificate profile provided here. Please update the certificate profile via `ca:profile-up` using the `--profile-file` pointing to the file `xipki/ca-setup/certprofile/certprofile-tls.json` contained in the `xipki-mgmt-cli`.

**Comment by xipki** [comment]
Shall be resolved using the method mentioned above.
