### ISSUE TITLE
Ibm QradarDLC certificate apply error

### ISSUE THREAD

**Issue by Rohi4777** [xipki/xipki#312]
problem parsing cert: java.io.IOException: unknown tag 13 encountered
Cannot set permission to the file /opt/ibm/si/services/dlc/keystore/dlc-client.pfx
getting this error when apply .crt certificate in the client located ibm qradar DLC.

**Comment by Rohi4777** [comment]
We installed IBM Qradar disconnected log collector. For setting up certificate-based authentication on Disconnected Log Collector we raised CSR and get the signed certificate in .crt format. we tried to apply certificate by IBM providing scripts/commands. but getting an error problem parsing cert: java.io.IOException: unknown tag 13 encountered
Cannot set permission to the file /opt/ibm/si/services/dlc/keystore/dlc-client.pfx
getting this error when apply .crt certificate in the client located ibm qradar DLC.

**Comment by Rohi4777** [comment]
we tried by /opt/ibm/si/services/dlc/current/script/generateCertificate.sh -p12 uuid.crt. but unable to apply. we can't set a connection with the SIEM console without a certificate apply.

**Comment by xipki** [comment]
1. In which step is XiPKI involved? And which XiPKI component?
2. Which protocol do you use to apply for the certificate?
3. And do you have XiPKI log files?

**Comment by xipki** [comment]
I close this issue due to inactivity. Re-open it if needed.
