### ISSUE TITLE
What set own dataSource.password ?

### ISSUE THREAD

**Issue by Ales999** [xipki/xipki#47]
Hello.

In file "ca-db.properties":
....
\#encrypted password 123456
dataSource.password = PBE:B9A/zfIDGOTc+xhshvJGWMMdft32EjtEZPWGH9M0JvoWFA==
...

What crypt my own password for this set ?

**Comment by Ales999** [comment]
Using xipki-pki-2.1.1-SNAPSHOT version

karaf@root()> xipki-tk:deobfuscate --password-file xipki/security/masterpassword.secret
the password is: 'qwert'
karaf@root()> 

Use for master: qwert
Use for Password: 123456
karaf@root()> xipki-tk:pbe-enc
Master password:*****
Password:******
the encrypted password is: '**PBE:B9CMiX1D3ohNCP7M7yyh3A/JP+ZKKDeudKcmkELy7xRALA==**'
karaf@root()> 

cat ca-db.properties 
\# encrypted password 123456
dataSource.password = **PBE:B9B3GLTSTCrjEB53BiirBAxt5XxNP+KjcPkPbGfRBEz+pA==**

Hm... not match ... Why ? What correct ?

**Comment by xipki** [comment]
Password-based encryption algorithm is used here to encrypt the password. Both are correct, since random nonce is also part of the input for the encryption.
