### ISSUE TITLE
REST interface: get/list certificates

### ISSUE THREAD

**Issue by kaspro** [xipki/xipki#53]
I'm unable to get or list certificates via the REST interface (using version 3.0.0).
I have tried the same logic as in the command line, with no luck, for example:
* https://localhost:8443/rest/MYCA1/list-cert
* https://localhost:8443/rest/MYCA1/get-cert/<serial>
* https://localhost:8443/rest/MYCA1/get-cert?serial-number=<serial>

Am I missing something, or is this simply not implemented?

Thanks in advance,
Regrads Chris

**Comment by xipki** [comment]
Support of this function is too complicated for a CA. I do not have any plan to implement this in this year.

**Comment by xipki** [comment]
will not fix
