### ISSUE TITLE
Enroll certificate: set validity

### ISSUE THREAD

**Issue by kaspro** [xipki/xipki#54]
Is it possible to set the validity of a certificate on request (command line and REST interface)?
It would be a great addition, thank you!

**Comment by xipki** [comment]
Please  add parameters not-before and/or not-after to the URI. Both should be utc time of the form yyyyMMddhhmmss.

**Comment by kaspro** [comment]
That's working fine, thank you!
Is there any document where I can find these options?

**Comment by xipki** [comment]
Sorry, I did not have time to document them. You can find the details in https://github.com/xipki/xipki/blob/master/ca-server/src/main/java/org/xipki/ca/server/impl/rest/RestImpl.java.
