### ISSUE TITLE
[v.3.0.0] Duplicate file warning when extracting 3.0.0.tar

### ISSUE THREAD

**Issue by paulvi** [xipki/xipki#58]
Duplicate file warning when extracting 3.0.0.tar

![image](https://user-images.githubusercontent.com/1614482/39687514-59101260-5201-11e8-94aa-6e93fd3fedac.png)

**Comment by paulvi** [comment]
OK, pax is extention format for storing file attributes.  It should not be cared for on Windows anyways.

**Comment by xipki** [comment]
Could not reproduce.
