### ISSUE TITLE
Continious build

### ISSUE THREAD

**Issue by paulvi** [xipki/xipki#59]
There are many free CI servers for open source projects, e.g. https://travis-ci.org/

Please consider to set up one, and add badge to README, so build status is noticeable

**Comment by xipki** [comment]
Thanks for the suggestion. I will consider this later.

**Comment by paulvi** [comment]
See (more for ) why

- https://softwareengineering.stackexchange.com/questions/308515/whats-the-point-of-running-unit-tests-on-a-ci-server

In my wards, Unit tests without continuously running them is wasting. 
And when the build is not small, it is unlikely that all tests are run on every change.
