### ISSUE TITLE
Should XiPKI work on Windows?

### ISSUE THREAD

**Issue by paulvi** [xipki/xipki#61]
This is Java project, so it should work on Windows

README says that it is tested with Linux.

Is there any reason why it should fail on Windows (as major OS for development) ?

**Comment by xipki** [comment]
It should work on Windows. But since I don't have Windows OS, I didn't get many chances to test it. Could you please execute some tests on Windows?

**Comment by paulvi** [comment]
Well, first full build (with tests) should pass.
But without CI server #59, it is not clear if it is because of environment, or because there are some tests that fail always.

**Comment by paulvi** [comment]
full build with test is OK

```
[INFO] XiPKI :: dist :: xipki-sdk ......................... SUCCESS [  4.806 s]
[INFO] XiPKI :: dist :: xipki-p11proxy .................... SUCCESS [  6.719 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:19 min
[INFO] Finished at: 2018-05-09T14:28:37+08:00
[INFO] Final Memory: 97M/1032M
[INFO] ------------------------------------------------------------------------
```
