### ISSUE TITLE
[question] pkcs11-constants

### ISSUE THREAD

**Issue by paulvi** [xipki/xipki#67]
Started at https://github.com/xipki/xipki/issues/60#issuecomment-387640138

Looking for pkcs11-constants

https://javalibs.com/search?searchFor=everything&q=pkcs11-constants

https://oss.sonatype.org/#nexus-search;quick%7Epkcs11-constants

the lib seems to be at https://github.com/xipki/pkcs11wrapper

Please open issue tracker for https://github.com/xipki/pkcs11wrapper repository

**Comment by xipki** [comment]
DONE.
