### ISSUE TITLE
Badge for CI

### ISSUE THREAD

**Issue by paulvi** [xipki/xipki#68]
If CI #59 is configured , then it is nice to put badge of build status into README, e.g.

```markdown
[![Build Status](https://secure.travis-ci.org/winterstein/Eclipse-Markdown-Editor-Plugin.png)](http://travis-ci.org/winterstein/Eclipse-Markdown-Editor-Plugin)
```

[![Build Status](https://secure.travis-ci.org/winterstein/Eclipse-Markdown-Editor-Plugin.png)](http://travis-ci.org/winterstein/Eclipse-Markdown-Editor-Plugin)

**Comment by xipki** [comment]
Thanks. DONE.

**Comment by paulvi** [comment]
Markdown is `[name](URL)`
