### ISSUE TITLE
generate ecc/sm2 key on jdk 1.8.0_171

### ISSUE THREAD

**Issue by tangzhanguo** [xipki/xipki#69]
I git the master code XiPKI 4.0.0  for testing ECC/SM2 ca root generation.
There was a issure when i execute the setup script.

karaf@root()> source file:./xipki/setup/cacert-none/setup-ec-p12.script

Env:
[dev@pki ~]$ java -version
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
[dev@pki ~]$ cat /etc/redhat-release 
CentOS release 6.9 (Final)
[dev@pki ~]$ mvn -version
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-18T02:33:14+08:00)
Maven home: /opt/maven
Java version: 1.8.0_171, vendor: Oracle Corporation, runtime: /home/dev/app/jdk1.8.0_171/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "2.6.32-696.30.1.el6.x86_64", arch: "amd64", family: "unix"

**Comment by tangzhanguo** [comment]
Error:
Karaf started in 0s. Bundle stats: 8 active, 8 total
       _  __ _ ____  __ __ ____      
      | |/ /(_) __ \/ //_//  _/     
      |   // / /_/ / ,<   / /        
     /   |/ / ____/ /| |_/ /         
    /_/|_/_/_/   /_/ |_/___/         

  XiPKI PKI 4.0.0-SNAPSHOT buildNumber 51f783a1 build at 2018-07-05-10:30:58

Hit '<tab>' for a list of available commands
and '[cmd] --help' for help on a specific command.
Hit '<ctrl-d>' or type 'logout' to shutdown Karaf.

karaf@root()> source file:./xipki/setup/cacert-none/setup-ec-p12.script                                                                             
#################################################################
#                     Generate Key and CSR                      #
#################################################################
Error executing command: parameter object not a ECParameterSpec

**Comment by tangzhanguo** [comment]
[karaf.log](https://github.com/xipki/xipki/files/2164805/karaf.log)
![xipki](https://user-images.githubusercontent.com/20964092/42301213-a9585f2a-8046-11e8-9362-ecc15cbbcd8d.jpg)

**Comment by tangzhanguo** [comment]
Download the latest code and compile,There is another error occurred, but  rsa root generation is normal.

![image](https://user-images.githubusercontent.com/20964092/42483760-f387cc8c-8421-11e8-985b-87f4dab1c312.png)

log file
[karaf.log](https://github.com/xipki/xipki/files/2178509/karaf.log)

**Comment by xipki** [comment]
Any update from your side?

**Comment by xipki** [comment]
Fixed in the commit bc1166a3e36e01620c520a52074357674d56ac96
