### ISSUE TITLE
Can this be used as OCSP/CRL proxy

### ISSUE THREAD

**Issue by shauntarves** [xipki/xipki#72]
Hi -

We have been using httpd CRLs to support our clients using PKI certificates to connect to our site. We'd like to migrate to OCSP but the responders on our client's certificates are not always reliable. Can this product be used to take third-party CRL files and build our own OCSP responder? Is the responder on the certificate the only one that can make a response?

**Comment by xipki** [comment]
F1. Can this product be used to take third-party CRL files and build our own OCSP responder?
Q1: You can use any CRL files as OCSP source.

F2. Is the responder on the certificate the only one that can make a response?
Q2: In general, the responder is the CA itself who issues the certificate, or some identity derives from the CA.
