### ISSUE TITLE
Is there an interface document with http mode?

### ISSUE THREAD

**Issue by banshifuhua** [xipki/xipki#74]
Hello author！
     Is there an interface document with HTTP mode?

**Comment by xipki** [comment]
What do you mean HTTP mode?

**Comment by banshifuhua** [comment]
Oh Sorry, actually I want to ask if there is a Restful API interface document!
Similar to what is written in the link below!
https://docs.atlassian.com/software/jira/docs/api/REST/7.6.1/#api/2/groupuserpicker-findUsersAndGroups

**Comment by xipki** [comment]
Currently no such document is available. In the next month, I will try to document the REST interface. But right now you can look at the REST example `https://github.com/xipki/xipki/blob/master/examples/lite-caclient-example/src/main/java/org/xipki/litecaclient/RestCaClient.java`, or the script `https://github.com/xipki/xipki/blob/master/assemblies/xipki-sdk/src/main/unfiltered/xipki/client-script/rest.sh`. Note that SSL connection is required.

**Comment by banshifuhua** [comment]
ok, I know, thank you！
