### ISSUE TITLE
openssl can't decoding x509Certificate file

### ISSUE THREAD

**Issue by mr-tan4** [xipki/xipki#75]
system:osx
openssl version:OpenSSL 1.1.2-dev
error info:
> `140735770256320:error:0909006C:PEM routines:get_name:no start line:crypto/pem/pem_lib.c:745:Expecting: TRUSTED CERTIFICATE`
I hope that you can modify the way the certificate file is generated. Can you change the X509Certificate byte[] to base64 encoding before outputting it to a file?

I would like to ask a question, why the key chain that comes with the osx system does not recognize the certificate generated by the sm2 key pair. Is there any way to solve this problem?

**Comment by xipki** [comment]
please provide detailed information.

**Comment by mr-tan4** [comment]
I didn't find the openssl log file, but I guess the reason why openssl doesn't recognize the certificate file is because there is no BEGIN CERTIFICATE and END CERTIFICATE identifier in the certificate file.


The certificate encoded in the PEM encoding format is like this：

> -----BEGIN CERTIFICATE-----
MIIC8zCCApqgAwIBAgIGAWZ3JHlOMAoGCCqBHM9VAYN1MIGDMRcwFQYDVQQDDA5z
bTIuc3NsZGVtby5jbjEzMDEGA1UECgwq5Lqa5pWw5L+h5oGv56eR5oqA77yI5LiK
5rW377yJ5pyJ6ZmQ5YWs5Y+4MRIwEAYDVQQHDAnkuIrmtbfluIIxEjAQBgNVBAgM
CeS4iua1t+W4gjELMAkGA1UEBhMCQ04wHhcNMTgxMDE1MDk1MjUxWhcNMTkxMDE1
MDk1MjUxWjCBgzEXMBUGA1UEAwwOc20yLnNzbGRlbW8uY24xMzAxBgNVBAoMKuS6
muaVsOS/oeaBr+enkeaKgO+8iOS4iua1t++8ieaciemZkOWFrOWPuDESMBAGA1UE
BwwJ5LiK5rW35biCMRIwEAYDVQQIDAnkuIrmtbfluIIxCzAJBgNVBAYTAkNOMIIB
UTATBgcqhkjOPQIBBggqgRzPVQGCLQOCATgAMIIBMzCB7AYHKoZIzj0CATCB4AIB
ATAsBgcqhkjOPQEBAiEA/////v////////////////////8AAAAA//////////8w
RAQg/////v////////////////////8AAAAA//////////wEICjp+p6dn140TVqe
S89lCafzl4n1FauPkt28vUFNlA6TBEEEMsSuLB8ZgRlfmQRGajnJlI/jC7/yZgvh
cVpFiTNMdMe8Nzai9PZ3nFm9zuNraSFT0KmHfMYqR0AC3zLlITnwoAIhAP////7/
//////////////9yA99rIcYFK1O79Ak51UEjAgEBA0IABLJ1LCS9/7mz51GWFlJU
VFju3cdI1KF3wDICL++msXOiJYaCOnIpG1hCDkeacLR7/Xvi3jSSSZq7P5m1psga
Kf8wCgYIKoEcz1UBg3UDRwAwRAIgYWqskFvcbqVZqg8R+00V/YBjUmcvc+Q4Y8aa
HOFGdicCICb9XqIlEsjbdzrRMRvdyIZ1KG92Pu4tPYEEBmmnINFD
-----END CERTIFICATE-----

A certificate file that is not encoded in PEM format is opened in vim like this:

> 0<82>^AÑ0<82>^Av ^C^B^A^B^B^A^A0
^F^H*<81>^\ÏU^A<83>u0-1^K0      ^F^CU^D^F^S^BDE1^N0^L^F^CU^D
^L^Exipki1^N0^L^F^CU^D^C^L^Emyca10^^^W^M181011091947Z^W^M281011091946Z0-1^K0    ^F^CU^D^F^S^BDE1^N0^L^F^CU^D
^L^Exipki1^N0^L^F^CU^D^C^L^Emyca10Y0^S^F^G*<86>HÎ=^B^A^F^H*<81>^\ÏU^A<82>-^CB^@^D[°°^Y$Ó5AìûÛðàK^Rç3Tí6¬&lV@Hh<96>^[VÓåøÅá&yõ+c§^^^QÖ<85><80>2<9a>þ#¿Óï*^Aâ6ÁÚ
^]®¥£<81><86>0<81><83>0^O^F^CU^]^S^A^Aÿ^D^E0^C^A^Aÿ0A^F^H+^F^A^E^E^G^A^A^D50301^F^H+^F^A^E^E^G0^A<86>%http://localhost:8080/ocsp/responder10^]^F^CU^]^N^D^V^D^T<94>T:.õCïM<8f>ºcù¸û½<8b>¥ú^Vy0^N^F^CU^]^O^A^Aÿ^D^D^C^B^A^F0
^F^H*<81>^\ÏU^A<83>u^CI^@0F^B!^@ë~<95>ýrO<9e>õ!<99>ÿ/(^U²<93>°¥<97>8u~l~ À^<9d>8yKÔ^B!^@Å^F<93><87>¤ÆY<85><8a>^YS<90>^@<98>¹´7Í±^TG^C-]x<85><9d>^A"Khc


So I think the certificate object should use PEM encoding when converting to a file.

**Comment by xipki** [comment]
Please add the option `-inform der` to the openssl command.

**Comment by mr-tan4** [comment]
Thanks
