### ISSUE TITLE
Authentication Vulnerability in SCEP

### ISSUE THREAD

**Issue by rnsquery** [xipki/xipki#79]
Could you please clarify how strongly does XiPki authenticate the clients? Does XiPki take care of the vulnerability mentioned in https://www.kb.cert.org/vuls/id/971035/? If so, how?

I am building a custom PKI system and evaluating XiPki for the same at the moment. I am glad to say that almost all of our requirements are met. 

Thanks,
Raghunath

**Comment by xipki** [comment]
XiPKI has a very accurate authentication system. You can specify exact which certificate profiles a user is allowed to apply. In this context the problem does not exist in XiPKI.

**Comment by rnsquery** [comment]
Thank you. 
I have another question. It is about synchronization across sites. 
If I deploy my CA in two locations geographically apart, how to achieve geo-redundancy? For example:
Lets say CA1 and CA2 are two instances in two different geographic sites. I have a client service that is connected to CA1 but if the site where CA1 is running is down, then I need my client service to go to CA2 running in site 2. And my client service should now be able to
   - get new certificates
   - get CRL
   - get OCSP response

So, how can I achieve the following?
  - How can my client use the same OTP provided by SCEP server on site1 to request for new certificates from CA2 in site 2? Or do I need to get fresh OTP from SCEP server on site 2?
  - How can I get the CRL from site2?
  - How can I get OCSP response from site2?

To be precise, how do I synchronize the data from site1 to site2? Is there any built-in support for geo-redundancy or any interfaces provided to achieve the same?

**Comment by xipki** [comment]
In short: yes, it is by design.

Please create a new issue for questions about synchronization.
