### ISSUE TITLE
Synchronization of Certificate Data

### ISSUE THREAD

**Issue by rnsquery** [xipki/xipki#80]
If I deploy my CA in two locations geographically apart, how to achieve geo-redundancy? For example:
Lets say CA1 and CA2 are two instances in two different geographic sites. I have a client service that is connected to CA1 but if the site where CA1 is running is down, then I need my client service to go to CA2 running in site 2. And my client service should now be able to
1) get new certificates
2) get CRL
3) get OCSP response

So, how can I achieve the following?
1) Can the client service use the same shared-secret provided by SCEP server on site1 to request for new certificates from CA2 in site 2? Or do I need to get fresh OTP from SCEP server on site 2?
2) How can I get the CRL from site2?
3) How can I get OCSP response from site2?

To be precise, how do I synchronize the data from site1 to site2? Is there any built-in support for geo-redundancy or any interfaces provided to achieve the same?

Also, how is clustering supported? Is it that just DB clustering that is needed?

**Comment by xipki** [comment]
XiPKI is designed for such use cases. All configuration and data certificates, CRLs, certificate status) are centralized in the database. There is no local configuration of CA.

All you need to do is to make sure that the connected databases have the same status, e.g. use the DB clustering.

**Comment by xipki** [comment]
And all CA instances can be operated in active mode at the same time. The same for OCSP instances.
