### ISSUE TITLE
CrlDbCertStatusStore inProcess value is not reset when the ".UPDATEME" file does not exist

### ISSUE THREAD

**Issue by ezzadeen** [xipki/xipki#82]
I have added a new CRL file which is already referenced in the configuration. I created a new ".UPDATEME" file to update the CRL store. But CrlDbCertStatusStore has already set crlUpdateInProgress to true when ".UPDATEME" file was removed. And that crlUpdateInProgress remains in "true" state until I shut down the OCSP responder and start over.

When the ".UPDATEME" file doesn't exist, the code should reset "crlUpdateInProgress" back to false before it returns. See the line in bold:

   if (!updateMeFile.exists()) {
      LOG.info("The CRL will not be updated. Create new file {} to force the update",
          updateMeFile.getAbsolutePath());
      crlUpdated = true;
      crlUpdateFailed = false;
      **crlUpdateInProcess.set(false);**
      return;
    }

This way, I can overwrite the CRL file and generate a new ".UPDATEME" file without having to shut down the OCSP responder.

**Comment by xipki** [comment]
Fixed. Thanks for the report.
