### ISSUE TITLE
OCSP Server DbCertStatusStore storeUpdateInProcess is always set to true

### ISSUE THREAD

**Issue by ezzadeen** [xipki/xipki#85]
In the ocsp-server project, the org.xipki.ocsp.server.store.DbCertStatusStore sets the AtomicBoolean storeUpdateInProcess to false by default. It then sets it to true but never sets it again to false at the end of the init method unless there is an exception.

This code:
    } catch (Throwable th) {
      **storeUpdateInProcess.set(false);**
      LogUtil.error(LOG, th, "could not executing initIssuerStore()");
      initializationFailed = true;
      initialized = true;
    }

should be:
    } catch (Throwable th) {
      LogUtil.error(LOG, th, "could not executing initIssuerStore()");
      initializationFailed = true;
      initialized = true;
    **} finally {
      storeUpdateInProcess.set(false);
    }**

**Comment by xipki** [comment]
Thank for the report. Fixed in c676e86.
