### ISSUE TITLE
crluris - which url i need to configure

### ISSUE THREAD

**Issue by tsvinoth** [xipki/xipki#86]
Hi Lijun Liao,

To setup ca server i am using the code xipki/ca-setup/cacert-none/setup-ec-p12.script .. It is internally using the template file template.ca-conf.json .. On this template file , Under Cauris section , there is a parameter named "crluris" .Here what is the url i need to give .. 

1.Do i need to configure some https/ldap server and give the corresponding url ? If it so, whether the ca server itself take care of pushing crl files to this server ?

2. Or  just give my vm ip with some specific port in which my ca server is running? 

"crlUris":[
					"http://ca.example.org/crl"
				],

Could you please help me on this ..

Thanks,
Vinoth S

**Comment by xipki** [comment]
The URLs configured here will be added as certificate extension. Not for the publishing of certificate.

**Comment by tsvinoth** [comment]
Hi Lijun Liao,

Thanks for the clarification .

Regards,
Vinoth S
