### ISSUE TITLE
scep client

### ISSUE THREAD

**Issue by tsvinoth** [xipki/xipki#87]
Hello,

There is an example code (xipki/client-script/rest.sh) provided for cmp client .. Is it possible to get a sample code for scep in rest .. The sample client script provided for scep (xipki/client-script/scep-client.script) will run only on karaf terminal .. 

Thanks,
Vinoth S

**Comment by xipki** [comment]
The CA supports the standard Interfaces CMP and SCEP,  as well as the proprietary REST. Since openssl does not provide functions of CMP and SCEP, no shell script can be provided.

**Comment by tsvinoth** [comment]
Hi Lijun Liao,

Thanks for the reply .

Regards,
Vinoth S
