### ISSUE TITLE
scep client error - CMS signingTime is out of permitted period

### ISSUE THREAD

**Issue by tsvinoth** [xipki/xipki#88]
Hi Lijun Liao,

I am trying scep client from remote vm  .. Every time when i run scep client in remote vm , i am seeing this error ..

karaf@root()> source xipki/client-script/scep-client.script                                                                                                                                                        
#################################################################
#               Enroll Certificate via SCEP                     #
#################################################################
# Get CA certificate
saved certificate to file output/scep-20190208-131826/cacert.der
=====SCEP: Enroll (self-signed identity cert) =====
saved PKCS#12 keystore to file output/scep-20190208-131826/scep-tls-20190208-131826.p12
saved CSR to file output/scep-20190208-131826/scep-tls-20190208-131826.csr
# Enroll certificate via PKCSReq

 command is xi:scep-enroll --method pkcs --url http://10.131.230.101:8080/ca/scep/myca/tls/pkiclient.exe --ca-cert output/scep-20190208-131826/cacert.der 
  --p12 output/scep-20190208-131826/scep-tls-20190208-131826.p12 --password 1234 
  --csr output/scep-20190208-131826/scep-tls-20190208-131826.csr --out output/scep-20190208-131826/scep-tls-20190208-131826.der
**Error executing command: CMS signingTime is out of permitted period**
karaf@root()>

Could you please help me to debug this issue .. If i try the scep client in same vm i didn't get this error ..

Thanks,
Vinoth S

**Comment by xipki** [comment]
Please synchronize the time in both VMs

**Comment by tsvinoth** [comment]
Hi Lijun Liao,

Thanks for the clarification ..

Regards,
vinoth s
