### ISSUE TITLE
Details on Shared-Secret handling

### ISSUE THREAD

**Issue by rnsquery** [xipki/xipki#89]
Hello
wrt the question on "who generates the secret?", section 2.4 of the IETF draft (https://tools.ietf.org/html/draft-gutmann-scep-13) mentions that CA should distribute the secret to client and this secret must be uniquely associated to that client. Below is the extraction from the RFC.

"_**2.4. Enrolment authorization** PKCS #10 [6] specifies a PKCS #9 [5] challengePassword attribute to be sent as part of the enrolment request. When utilizing the challengePassword, the CA distributes a shared secret to the client which will uniquely associate the enrollment request with the client._"

Therefore, this appears to be a deviation from the RFC. Please clarify.

Also, you mentioned the token syntax in XiPki is a combination of username and password. This combination is required to be provisioned into XiPki through the conf file which is a plain text file.

1. Are these credentials used by XiPki for any kind of authentication/authorization?
2. A client a is identified by name ABC and another by name XYZ. ABC requests for certificates in the name of XYZ. Does XiPki have any kind of authentication mechanism in place to handle such situations? Will the request be declined or ABC would still be issued a certificate in the name of ABC itself instead of XYZ?
3. Storing password in plain text on the CA side is not secure. Does XiPki have any mechanism to hide it? for ex. encrypt it?
4. If Administer is to provision the secrets, is conf file the only way? If so, then every secret addition would require restarting XiPki? Or is there any other way to add the secrets on the fly without restarts?

**Comment by rnsquery** [comment]
Hello,
Could you please confirm on the 4th point above? We need to make a decision on our design.

Thank you.

**Comment by xipki** [comment]
1. The credential is used for the authentication of the client. In SCEP only credential is supported. While in CMP or REST certificate based authentication is supported additionally.
2. No relation between username and Subject in certificate.
3. Salted hash value of password is saved, but not the password.
4. a) Either configured in conf file and via the command ca:load-file, or b) via commands ca:user-add then ca:causer-add

**Comment by rnsquery** [comment]
thank you very much. That was very much helpful.

I have another query.
If XiPki is configured to be a subCA of another root CA, and the certificates issued to XiPki by the root CA are revoked at root CA, does XiPki have any mechanism to automatically get fresh certificates? 
Also, in such case, the certificates issued by the subCA become invalid too and need to be reissued. Does XiPki take care of it automatically or it is a manual action on user side?

**Comment by xipki** [comment]
1. XiPKI does not implement mechanism to get fresh CA certificate. It is much more than just the certificate itself. E.g. you need to adapt the signing key.
2. No. You need to disable the current CA and setup a new CA.

**Comment by xipki** [comment]
I close this issue. For other topic pls create new issues.
