### ISSUE TITLE
Why do I get Verify error:unable to get local issuer certificate when I run openssl ocsp?

### ISSUE THREAD

**Issue by Hyunmin-Kwak** [xipki/xipki#90]
Dear Team.
I testing xipki ocsp example in version 5.0.0.
This is the script that I'm trying to run (/client-scritp/rest.sh):
...
openssl ocsp -nonce  -CAfile ${OUT_DIR}/cacert.pem -url ${OCSP_URL} \
  -issuer ${OUT_DIR}/cacert.pem -cert ${OUT_DIR}/${CN}.pem -text
...

This is the output 

OCSP Request Data:
...
OCSP Response Data:
....
Certificate:
...
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
Response Verify Failure
139777126565704:error:27069065:OCSP routines:OCSP_basic_verify:certificate verify error:ocsp_vfy.c:126:Verify error:unable to get local issuer certificate
intermediate/certs/cert.pem: good
        This Update: Feb 11 08:10:23 2019 GMT
openssl ocsp -CAfile intermediate/certs/cacert.pem -url http://localhost:8080/ocsp/responder1

What am I doing wrong? How can I fix this?

Thank you

**Comment by xipki** [comment]
This is an openssl issue. Please check the openssl help.

**Comment by xipki** [comment]
Please check whether the Option -CAfile specifies the CA certificate which is used to verify the OCSP signer?

**Comment by xipki** [comment]
Please check whether the Option -CAfile specifies the CA certificate which is used to verify the OCSP signer?
