### ISSUE TITLE
Why nextUpdate is null in ocsp response

### ISSUE THREAD

**Issue by Hyunmin-Kwak** [xipki/xipki#91]
Dear Team 

I am testing ocsp process with sample script . (5.0.1-release)
Check the certificate with openssl ocsp command, then the nextUpdate value is null. 
How can I set the nextUpdate value in ocsp response.

Thank you

> Ocsp server responsep

`16:16:30.307 [http-nio-8080-exec-9] INFO  org.xipki.ocsp.api.OcspServer - issuer: 300906052b0e03021a050004142b73c24901f541519bd746d5e5eb7dfdaceb9bcd04140d83a396e8d9caf1d0774dfa1ffecc79b5422bd8, serialNumber: 0x0810f69c3a7c4d2d, certStatus: good, thisUpdate: Thu Feb 21 16:16:30 KST 2019, nextUpdate: null, certHash: a4cf5f8aa8b8c7b47034be641a321b2a1a35e6a4cfaeff9ed80ef90cc20b1bb5`

**Comment by xipki** [comment]
NextUpdate is only present if the server knows when the status may be changed. See Section 4.2.2.1 of RFC.

**Comment by Hyunmin-Kwak** [comment]
The specification(RFC 6960) states that nextupate is set based on crl.
> This interval corresponds to the {thisUpdate, nextUpdate}  interval in CRLs.

If so, is there a way to test CRL on the server?

Thank you.

**Comment by xipki** [comment]
Features added in the branch master (see issue #92). Please clone the project and test it.

**Comment by Hyunmin-Kwak** [comment]
I cloned the project from master branch.
But I can't build project with below message. Do you have and idea to build?
Thank you

[ERROR] Failed to execute goal on project ocsp-server: Could not resolve dependencies for project org.xipki:ocsp-server:bundle:5.0.2-SNAPSHOT: Could not find artifact org.xipki:ocsp-api:jar:5.0.2-SNAPSHOT in apache-snapshots (http://repository.apache.org/content/groups/snapshots-group) -> [Help 1]

**Comment by xipki** [comment]
Please build the whole project as described in Section 'Get Started' in project's README.

**Comment by Hyunmin-Kwak** [comment]
Dear team.
Build succeeded.
And change the binary ca/ocsp war file. 
But next update value is still null, when using existing certificate data.
Do I need to create new test data?

Thank you.

**Comment by Hyunmin-Kwak** [comment]
Dear team.
Build succeeded.
And OCSP response is OK with CertUtil on windows.

Thank you.
