### ISSUE TITLE
 Can I work with xipki ocsp server and an external CA server?

### ISSUE THREAD

**Issue by Hyunmin-Kwak** [xipki/xipki#94]
Dear Team.
I am developing my CA server.
I want to work with xipki ocsp server on my CA server.
A little bit of your project looks like xipki ocsp and xipki ca server are very closely connected.
If I modify the ocsp source a bit, is it possible to work with my ca server (using REST API)?

Thank you.

**Comment by xipki** [comment]
Yes. It is possible. An example located in https://github.com/xipki/xipki/blob/master/ocsp-server/src/main/java/org/xipki/ocsp/server/store/example/DummyStore.java has been added.

**Comment by Hyunmin-Kwak** [comment]
Thank you for your update.
My CA server supports certificate's status REST API.
Can I implement rest api communication logic with my CA server in DummyStore.java?

Thank you

**Comment by Hyunmin-Kwak** [comment]
Thank you for your update.
My CA server supports certificate's status REST API.
Can I implement rest api communication logic with my CA server in DummyStore.java?

Thank you

**Comment by Hyunmin-Kwak** [comment]
Thank you for your update.
My CA server supports certificate's status REST API.
Can I implement rest api communication logic with my CA server in DummyStore.java?

Thank you

**Comment by xipki** [comment]
Just implement your own OCSPStore as Dummy Store in your own project. You add then your project jars to the ocsp.war.

**Comment by Hyunmin-Kwak** [comment]
It means that .
1. Create a new my project my_ocsp.jar, includes new custom my_ocspStore like DummyStore.
2. Add the my_ocsp.jar to the the xipki's ocsp.war
3. Update my_ocspStore's database through My CA Server?

**Comment by xipki** [comment]
Steps 1 and 2: yes
Step 3: not sure. Depends on your application logic.

**Comment by xipki** [comment]
If you needs more detailed help related only to project, pls drop me email Lijun.liao AT gmail.com.

**Comment by Hyunmin-Kwak** [comment]
Thank you. 
I'll send to your email.

**Comment by xipki** [comment]
Please see the Section "Use OCSP with customized Certificate Status Source (OcspStore)" in the repo's [README.md](README.md).
