### ISSUE TITLE
sub ca

### ISSUE THREAD

**Issue by tsvinoth** [xipki/xipki#97]
Hi Lijun Liao,

I want to configure xipki ca as my sub ca .. Could you please share some document or instruction on how to do this .. I want to register xipki ca to the another root ca with the csr generated by xipki ca ..

Thanks,
Vinoth S

**Comment by xipki** [comment]
Hi Vinoth,

sorry I still have no time to write down the document. But I provide the example scripts in the `xipki-cli` (the last release is https://github.com/xipki/xipki/releases/download/v5.0.1/xipki-cli-5.0.1.tar.gz) to setup 1 root CA and two SubCAs. There are two versions:
 - No certificates of the root CA and SubCAs are present (in the folder `xipki/ca-setup/cacert-none`).
 - Certificates of the root CA and SubCAs are present (in the folder `xipki/ca-setup/cacert-present`).

Althougth the example scripts install 3 CAs, you can also install 1 or 2 CAs. Just adapt the scripts.

You can create a CSR using any tool at your choice, send it to to the root ca, and request the Sub CA certificate.

**Comment by tsvinoth** [comment]
Hi Lijun Liao,

Thanks for the reply .. I will get back to you in case if i need further help ..

Regards,
Vinoth S

**Comment by tsvinoth** [comment]
Hi Lijun Liao,

I have a created a root ca (self signed) and also created 1 sub ca (ztsca.p12) ..I just copied ztsca.p12 to xipki/ca-setup/cacert-present and i want to configure sub ca using xipki .. when i tried to load the config file i am getting below error ..

```
karaf@root()> source xipki/ca-setup/cacert-present/setup-ec-p12.script ztsca                                                                                                                                       
#################################################################
#                       Load ca-conf.json                       #
#################################################################
Error executing command: could not load configuration xipki/ca-setup/cacert-present/ca-conf.json, error: could not add signer responder1
karaf@root()>  
```

 FYI i have attached the configuration file which i am loading ..Could you please help me on this ..I am not sure whether i am doing it correctly .. My goal is to start xipki as sub ca of my own root ca ..

Thanks,
Vinoth S

**Comment by xipki** [comment]
It seems the signer ```responder1``` could not be added. Does the file ```xipki/keycerts/tlskeys/server/tls-server.p12```exist? Do you change or modify this file?

**Comment by tsvinoth** [comment]
Hi Lijun Liao,

Now i am not seeing the above error instead , i am getting this error

```
karaf@root()> source xipki/ca-setup/cacert-present/setup-ec-p12.script ztsca                                                                                                                                       
#################################################################
#                       Load ca-conf.json                       #
#################################################################
Error executing command: could not load configuration xipki/ca-setup/cacert-none/ca-conf.json, error: org.xipki.ca.api.OperationException: error code: SYSTEM_FAILURE, error message: ObjectCreationException: org.xipki.security.XiSecurityException: operator creation error
karaf@root()> 
```
I just copied ztsca.p12 to xipki/ca-setup/cacert-present and tried to load the config file

[ca-conf.json.txt](https://github.com/xipki/xipki/files/4169476/ca-conf.json.txt)

Thanks,
Vinoth S

**Comment by xipki** [comment]
Please check the log file first. Most errors will be indicated there.

**Comment by tsvinoth** [comment]
Hi Lijun Liao,

Thanks for the information .. I can able to create xipki ca as sub ca for my root ca ..

Regards,
Vinoth S
