### ISSUE TITLE
generate certificate : set email field

### ISSUE THREAD

**Issue by Hyunmin-Kwak** [xipki/xipki#98]
Hi Lijun

I'm testing certificate for outlook s/mime.
I set email address field ("CN=${CN},O=${org},C=${c}, E=${Email}"),  then can't create certificate with below message.
How can I set email address to the certificate.

`
WARN  org.xipki.ca.server.cmp.CmpResponder - generate certificate, OperationException: code=BAD_CERT_TEMPLATE, message=BadCertTemplateException: subject DN of type 1.2.840.113549.1.9.1 (emailAddress) is not allowed
`

Thank you.

**Comment by xipki** [comment]
1. You need to create a certprofile allowing email address in the certificate, add it to the CA system (via command `ca:profile-add`) and associate it with the specified CA (via command `ca:caprofile-add`).
2. Email address in subject is forbidden in RFC 5280. It must be specified in the extension `subjectAltName`. See Section `4.1.2.6 Subject`:
`
   Conforming implementations generating new certificates with
   electronic mail addresses MUST use the rfc822Name in the subject
   alternative name extension (Section 4.2.1.6) to describe such
   identities.  Simultaneous inclusion of the emailAddress attribute in
   the subject distinguished name to support legacy implementations is
   deprecated but permitted.
`

**Comment by Hyunmin-Kwak** [comment]
Thank you.

I change subjectAltName configuration in my cert profile, using "rfc822Name".

**Comment by xipki** [comment]
Added example to generate certificates for S/MIME. See commits on Mar 7, 2019 CET.

**Comment by Hyunmin-Kwak** [comment]
Thank you.
I'll check the update.
